IntelliJ 플러그인으로 코드 자동 리팩토링 하기
socar-inc/socar-inc.github.io pull request #103
Opened 2022-01-13 23:29 UTC by socar-jian

[노션 검토 페이지](https://www.notion.so/socarcorp/Intellij-4c494417570a416d9bdac0bb41da5f50)

IntelliJ 플러그인을 만들고 Android Studio에서 돌려서 Kotlin 코드를 수정하는 작업을 다룬 포스트입니다.
안드로이드 팀의 [개수다 내용](https://www.notion.so/socarcorp/Intellij-20ccd78e86084e0b8473e5e6874f0418)을 바탕으로 작성했습니다.

아래 PR과 내용이 동일하지만, 해당 PR이 보기 어려워져서 닫고 이 PR을 새로 올립니다.
- #101

2022-01-14 02:15 UTC, arngard commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +안녕하세요, 쏘카 안드로이드팀의 지안(전현기)입니다. 저희 안드로이드팀에서도 몇 개월 전, 처음에는 단순해 보이지만 수십에서 수백 개 파일에 걸친 변경사항을 하나하나 고치려고 하다 보면 마냥 단순하지만은 않았던 리팩토링을 수행했던 경험이 있었습니다.
보통 새로운 기능에만 적용하고 기존 코드까지 통일하지 않는 경우가 대부분일 거예요. 다른 사람들이 보기에는 그런 배경을 설명해주는 게 좋을 것 같습니다. 프로젝트 코드 전체의 통일성을 위해 모든 코드를 동시에 최신화한다는 내용.

2022-01-18 13:15 UTC, socar-hardy requested changes
너무 잘쓰셔서 술술 읽히네요. 
컨벤션도 잘 지켜주셔서 감사합니다!

코멘트만 확인해주세요~

2022-01-18 13:15 UTC, socar-hardy commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +등의 다양한 동작을 해볼 수 있습니다.
```suggestion
즉, 위에서 `Kotlin` 의존성을 추가해 줌으로써 `org.jetbrains.kotlin.psi.KtClass`와 같이 `org.jetbrains.kotlin` 패키지에 있는 내용을 우리가 만드는 플러그인 코드에서 사용할 수 있습니다. 결과적으로 우리가 만드는 플러그인에서 PSI tree에 있는 이 Kotlin PSI element에 대해 다음과 같은 동작들을 해볼 수 있습니다.

- 해당 element가 class인지 property인지 function인지 판별
- 이 element를 참조하고 있는 다른 element로 이동
- AST에 있는 하위 element들은 어떤 것들이 있는지 확인
```

이렇게 바꿔보는건 어떨까요?

2022-01-18 13:15 UTC, socar-hardy commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +클래스 안에 정의된 프로퍼티를 가져와서 그 PSI tree를 보면서 `bindView`를 사용하고 있는지, 그리고 어떤 ID를 사용하는지 확인해 보면 됩니다.
```suggestion

클래스 안에 정의된 프로퍼티를 가져와서 그 PSI tree를 보면서 `bindView`를 사용하고 있는지, 그리고 어떤 ID를 사용하는지 확인해 보면 됩니다.
```

2022-01-19 14:16 UTC, socar-jian commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +복잡한 로직을 수정하는 것이 아니라 단순한 코드 변경이라고 생각해서 예상 작업량을 짧게 잡고 덤벼들었다가도, 리팩토링의 대상이 되는 코드가 곳곳에 사용되고 있다면 코드 전체를 수정하는 것에는 최초의 예상보다 많은 시간이 소요되어 난처해지는 경우도 생기곤 합니다.
깃헙상에서 suggestion 을 반영해서 커밋하니 자동으로 resolve 처리되나보네요

2022-01-20 06:56 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +안녕하세요, 쏘카 안드로이드팀의 지안(전현기)입니다. 저희 안드로이드팀에서도 몇 개월 전, 광범위한 코드에 대한 리팩토링을 수행한 경험이 있습니다.
닉네임으로 넣는게 좋을 것 같습니다!

2022-01-20 09:07 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +- Android Studio의 rename 기능을 변수 하나하나에 적용해서 바꾸기
```suggestion
- Android Studio의 Rename 기능을 변수 하나하나에 적용해서 바꾸기
```

2022-01-20 09:07 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +- Kotlin compiler의 [parsing](https://github.com/JetBrains/kotlin/tree/master/compiler/psi/src/org/jetbrains/kotlin/parsing)을 사용하기
```suggestion
- Kotlin Compiler의 [parsing](https://github.com/JetBrains/kotlin/tree/master/compiler/psi/src/org/jetbrains/kotlin/parsing)을 사용하기
```

2022-01-20 09:07 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +이 중에서 Android Studio의 IDE 기능을 써서 renaming 하는 방식은 신뢰도가 높고 추가적인 개발이 필요 없지만, 각각의 변수들을 하나하나 수정해야 하므로 작업에 걸리는 시간이 길어진다는 단점이 있었습니다.
```suggestion
이 중에서 Android Studio의 IDE 기능을 써서 Renaming 하는 방식은 신뢰도가 높고 추가적인 개발이 필요 없지만, 각각의 변수들을 하나하나 수정해야 하므로 작업에 걸리는 시간이 길어진다는 단점이 있었습니다.
```

2022-01-20 09:08 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +그리고 정규표현식으로 찾아 바꾸는 작업은 여러 변수나 파일들을 한꺼번에 고칠 수는 있었지만, reference(usage)를 명확하게 구분해내기가 어렵고 정규표현식을 작성하는 것에도 시간이 많이 소요된다는 문제가 있었습니다.
```suggestion
그리고 정규표현식으로 찾아 바꾸는 작업은 여러 변수나 파일들을 한꺼번에 고칠 수는 있었지만, Reference(Usage)를 명확하게 구분해내기가 어렵고 정규표현식을 작성하는 것에도 시간이 많이 소요된다는 문제가 있었습니다.
```

2022-01-20 09:08 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +Kotlin compiler를 써서 parsing 하거나, LSP를 사용해서 수정하는 것은 해당 기능을 개발하기 위해 필요한 배경지식들이 과도하게 많이 필요했습니다.
```suggestion
Kotlin Compiler를 써서 Parsing 하거나, LSP를 사용해서 수정하는 것은 해당 기능을 개발하기 위해 필요한 배경 지식들이 과도하게 많이 필요했습니다.
```

2022-01-20 09:08 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +또한 Kotlin Language Server는 아직 [공식적으로 제공되지 않고 있으며](https://discuss.kotlinlang.org/t/any-plan-for-supporting-language-server-protocol/2471), 비공식 language server에서는 [rename 기능에 문제](https://github.com/fw
```suggestion
또한 Kotlin Language Server는 아직 [공식적으로 제공되지 않고 있으며](https://discuss.kotlinlang.org/t/any-plan-for-supporting-language-server-protocol/2471), 비공식 Language Server에서는 [Rename 기능에 문제](https://github.com/fwcd/kotlin-language-server/pull/319)가 있다는 이야기도 있어서 섣불리 시도해 보기도 어려웠고요.
```

2022-01-20 09:08 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +반면에 IntelliJ Platform Plugin은 기존에 IDE에서도 사용해왔던 기능들을 그대로 사용할 테니 reference를 제대로 찾아서 변경해 주는 안정성이 확보되어 있다고 볼 수 있었습니다.
```suggestion
반면에 IntelliJ Platform Plugin은 기존에 IDE에서도 사용해왔던 기능들을 그대로 사용할 테니 Reference를 제대로 찾아서 변경해 주는 안정성이 확보되어 있다고 볼 수 있었습니다.
```

2022-01-20 09:09 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +또한 이미 다양한 기능을 가진 플러그인들이 plugin marketplace에 올라와 있는 것을 보면 단지 이번 리팩토링뿐만 아니라 다른 기능을 추가해 볼 수도 있을 것이라는 생각도 들었습니다.
```suggestion
또한 이미 다양한 기능을 가진 플러그인들이 Plugin Marketplace에 올라와 있는 것을 보면 단지 이번 리팩토링뿐만 아니라 다른 기능을 추가해 볼 수도 있을 것이라는 생각도 들었습니다.
```

2022-01-20 09:09 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +물론 개발에 들어가는 시간이 있겠지만 Kotlin compiler나 LSP를 다루는 것보다는 빠르게 진행할 수 있으리라고 보았습니다.
```suggestion
물론 개발에 들어가는 시간이 있겠지만 Kotlin Compiler나 LSP를 다루는 것보다는 빠르게 진행할 수 있으리라고 보았습니다.
```

2022-01-20 09:09 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +|  | IntelliJ rename | Regex replace | Kotlin parser | Language server | IntelliJ Plugin |
```suggestion
|  | IntelliJ Rename | Regex Replace | Kotlin Parser | Language Server | IntelliJ Plugin |
```

2022-01-20 09:09 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +이러한 비교를 바탕으로 개발 시간이 많이 필요하지 않으면서도 자동화가 가능한 IntelliJ Platform Plugin 방식을 선택했고, 이를 통해 view binding으로의 리팩토링을 진행해 보기로 했습니다.
```suggestion
이러한 비교를 바탕으로 개발 시간이 많이 필요하지 않으면서도 자동화가 가능한 IntelliJ Platform Plugin 방식을 선택했고, 이를 통해 View Binding으로의 리팩토링을 진행해 보기로 했습니다.
```

2022-01-20 09:10 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +그 항목을 선택하고 `Run` 버튼을 눌러서 이를 실행시키면 예제 플러그인이 설치되어 동작할 IntelliJ Community Edition이 자동으로 다운로드되고, 그 sandbox 인스턴스 IDE가 새로 뜨며, 그 위에서 예제 플러그인이 돌아가는 것을 확인해 볼 수 있습니다.
```suggestion
그 항목을 선택하고 `Run` 버튼을 눌러서 이를 실행시키면 예제 플러그인이 설치되어 동작할 IntelliJ Community Edition이 자동으로 다운로드되고, 그 Sandbox 인스턴스 IDE가 새로 뜨며, 그 위에서 예제 플러그인이 돌아가는 것을 확인해 볼 수 있습니다.
```

2022-01-20 09:10 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +[설명](https://github.com/JetBrains/intellij-platform-plugin-template/tree/v1.1.0#plugin-configuration-file)에도 나와있듯이 `/src/main/resources/META-INF/plugin.xml` 파일에 `applicationService`로 지정된 `MyApplicati
```suggestion
[설명](https://github.com/JetBrains/intellij-platform-plugin-template/tree/v1.1.0#plugin-configuration-file)에도 나와있듯이 `/src/main/resources/META-INF/plugin.xml` 파일에 `applicationService`로 지정된 `MyApplicationService.kt`, `projectService`로 지정된 `MyProjectService.kt`가 Sandbox IDE의 로드 시점에 수행되며, `println`으로 출력하는 메시지가 바깥쪽 IDE의 Run 탭에 출력되는 것을 확인할 수 있었습니다.
```

2022-01-20 09:10 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +기존에 Android Studio를 비롯한 IntelliJ 계열 IDE에도 renaming 기능이 있기 때문에, 플러그인에도 관련 내용이 있으리라 판단했고, 아니나 다를까 [이 문서](https://plugins.jetbrains.com/docs/intellij/kotlin.html#handling-kotlin-code)에서 Kotlin 관련 내용을 찾을
```suggestion
기존에 Android Studio를 비롯한 IntelliJ 계열 IDE에도 Renaming 기능이 있기 때문에, 플러그인에도 관련 내용이 있으리라 판단했고, 아니나 다를까 [이 문서](https://plugins.jetbrains.com/docs/intellij/kotlin.html#handling-kotlin-code)에서 Kotlin 관련 내용을 찾을 수 있었습니다.
```

2022-01-20 09:11 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +여기서 PSI란 [공식 문서](https://plugins.jetbrains.com/docs/intellij/implementing-parser-and-psi.html)에 적혀있는 것처럼 특정 언어를 다루기 쉽도록 IntelliJ platform이 파싱한 AST 요소들 위에 부가정보(문법적인 정보나, 언어 특유의 속성)들을 더한 것입니다.
```suggestion
여기서 PSI란 [공식 문서](https://plugins.jetbrains.com/docs/intellij/implementing-parser-and-psi.html)에 적혀있는 것처럼 특정 언어를 다루기 쉽도록 IntelliJ Platform이 파싱한 AST 요소들 위에 부가정보(문법적인 정보나, 언어 특유의 속성)들을 더한 것입니다.
```

2022-01-20 09:11 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +저희는 위에서 적었던 `platformPlugins = ..., Kotlin`을 통해서 IntelliJ Kotlin plugin이 제공하는 Kotlin PSI를 사용할 수 있게 되었습니다.
```suggestion
저희는 위에서 적었던 `platformPlugins = ..., Kotlin`을 통해서 IntelliJ Kotlin Plugin이 제공하는 Kotlin PSI를 사용할 수 있게 되었습니다.
```

2022-01-20 09:11 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +결과적으로 우리가 만드는 플러그인에서 PSI tree에 있는 이 Kotlin PSI element에 대해 다음과 같은 동작들을 해볼 수 있습니다.
```suggestion
결과적으로 우리가 만드는 플러그인에서 PSI tree에 있는 이 Kotlin PSI Element에 대해 다음과 같은 동작들을 해볼 수 있습니다.
```

2022-01-20 09:12 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +- AST에 있는 하위 element들은 어떤 것들이 있는지 확인
```suggestion
- 해당 Element가 Class인지 Property인지 Function인지 판별
- 이 Element를 참조하고 있는 다른 Element로 이동
- AST에 있는 하위 Element들은 어떤 것들이 있는지 확인
```

2022-01-20 09:12 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +Kotlin PSI를 사용해서 프로젝트에 있는 모든 `.kt` 파일에 정의된 Kotlin class의 이름을 출력해 보려면 아래와 같은 함수를 만들어서 사용해 볼 수 있습니다.
```suggestion
Kotlin PSI를 사용해서 프로젝트에 있는 모든 `.kt` 파일에 정의된 Kotlin Class의 이름을 출력해 보려면 아래와 같은 함수를 만들어서 사용해 볼 수 있습니다.
```

2022-01-20 09:13 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +아래의 스크린샷은 기본 예제 프로젝트의 `MyProjectService.kt`파일을 수정한 뒤에 `Run Plugin`을 통해 실행된 테스트용 sandbox IDE에서 동일한 프로젝트를 열었을 때 바깥쪽 IDE에 값들이 출력되는 모습입니다.
```suggestion
아래의 스크린샷은 기본 예제 프로젝트의 `MyProjectService.kt`파일을 수정한 뒤에 `Run Plugin`을 통해 실행된 테스트용 Sandbox IDE에서 동일한 프로젝트를 열었을 때 바깥쪽 IDE에 값들이 출력되는 모습입니다.
```

2022-01-20 09:13 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +다만 프로젝트가 열리는 시점에는 indexing이 끝나지 않아 모듈이나 파일 목록들이 아직 구성되지 않은 상태일 수도 있기 때문에 위와 같이 `DumbService.getInstance(project).runWhenSmart()`를 사용해서 indexing이 완료된 후에 실행될 수 있도록 했습니다.
```suggestion
다만 프로젝트가 열리는 시점에는 Indexing이 끝나지 않아 모듈이나 파일 목록들이 아직 구성되지 않은 상태일 수도 있기 때문에 위와 같이 `DumbService.getInstance(project).runWhenSmart()`를 사용해서 Indexing이 완료된 후에 실행될 수 있도록 했습니다.
```

2022-01-20 09:14 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +이러한 기능을 바탕으로 PSI tree를 확인해서 우리가 수정할 대상인 `bindView` delegate를 사용하는 프로퍼티 목록을 가져올 수 있습니다.
```suggestion
이러한 기능을 바탕으로 PSI tree를 확인해서 우리가 수정할 대상인 `bindView` Delegate를 사용하는 프로퍼티 목록을 가져올 수 있습니다.
```

프로퍼티도 Property로 다 통일하면 어떨까요?

2022-01-20 09:14 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +위쪽 단락에서 받아온 Kotlin PSI의 `KtProperty` 타입은 `PsiNamedElement`를 implement한 타입입니다.
```suggestion
위쪽 단락에서 받아온 Kotlin PSI의 `KtProperty` 타입은 `PsiNamedElement`를 구현한 타입입니다.
```

implement한 타입입니다라는 표현이 영어와 한국어의 혼재인 것 같아 구현이라고 제안드려봅니다!!

2022-01-20 09:15 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +따라서 아래와 같이 함수를 만들어서 reference를 포함한 모든 장소의 이름을 변경하고, 그 변경사항을 반영할 수 있습니다.
```suggestion
따라서 아래와 같이 함수를 만들어서 Reference를 포함한 모든 장소의 이름을 변경하고, 그 변경사항을 반영할 수 있습니다.
```

2022-01-20 09:16 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +`plugins.xml`에 아래와 같이 작성하고 `Run Plugin`을 돌려서 켜진 sandbox IntelliJ를 확인해 보면, 상단의 Tools 메뉴 가장 위에 action이 등록된 것을 볼 수 있습니다.
```suggestion
`plugins.xml`에 아래와 같이 작성하고 `Run Plugin`을 돌려서 켜진 Sandbox IntelliJ를 확인해 보면, 상단의 Tools 메뉴 가장 위에 Action이 등록된 것을 볼 수 있습니다.
```

2022-01-20 09:16 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +이제 `class`에 지정한 클래스로 가서 action에서 수행할 내용을 적어주면 됩니다.
```suggestion
이제 `class`에 지정한 클래스로 가서 Action에서 수행할 내용을 적어주면 됩니다.
```

2022-01-20 09:16 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +- View binding migration 페이지에 있는 것처럼 레이아웃을 `R.layout.~` resource 대신 `...Binding` 클래스로부터 받아와서 초기화하는 코드 삽입 기능
```suggestion
- View Binding Migration 페이지에 있는 것처럼 레이아웃을 `R.layout.~` resource 대신 `...Binding` 클래스로부터 받아와서 초기화하는 코드 삽입 기능
```

2022-01-20 09:17 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +PR에서 코드 리뷰 과정을 거치는 도중, view binding 초기화 코드를 수정하면 좋겠다는 의견이 있어서 이를 전체적으로 반영할 때에도 하나하나 파일을 찾아가며 고칠 필요가 없던 것도 큰 이득이었습니다.
```suggestion
PR에서 코드 리뷰 과정을 거치는 도중, View Binding 초기화 코드를 수정하면 좋겠다는 의견이 있어서 이를 전체적으로 반영할 때에도 하나하나 파일을 찾아가며 고칠 필요가 없던 것도 큰 이득이었습니다.
```

2022-01-20 09:17 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +그뿐만 아니라 현재는 이 플러그인을 확장해서 live template으로 하기에는 까다로운 템플릿 코드 기능을 추가하는 등, 더 다양한 형태로 활용하고 있습니다.
```suggestion
그뿐만 아니라 현재는 이 플러그인을 확장해서 Live Template으로 하기에는 까다로운 템플릿 코드 기능을 추가하는 등, 더 다양한 형태로 활용하고 있습니다.
```

2022-01-20 09:17 UTC, socar-kyle commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +짧은 지원자 신청 기간을 거쳐 현재는 closed preview를 진행 중인데요, Fleet에서 plugin 지원은 어떻게 진행할지, language server에 대한 정책은 어떻게 바뀔지 흥미롭습니다.
```suggestion
짧은 지원자 신청 기간을 거쳐 현재는 Closed Preview를 진행 중인데요, Fleet에서 Plugin 지원은 어떻게 진행할지, Language Server에 대한 정책은 어떻게 바뀔지 흥미롭습니다.
```

2022-01-20 12:56 UTC, socar-jian commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +안녕하세요, 쏘카 안드로이드팀의 지안(전현기)입니다. 저희 안드로이드팀에서도 몇 개월 전, 광범위한 코드에 대한 리팩토링을 수행한 경험이 있습니다.
넵 닉네임으로 할게요!

2022-01-20 13:05 UTC, socar-jian commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +이 부분만 놓고 보면 단순하게 regex를 사용해서 치환해도 어떻게든 가능할 것 같다는 생각이 듭니다.
문장 흐름으로 보았을 때 아래쪽의 '그런데 이 작업~'이 다른 줄로 분리되어야 할 것 같다는 뜻인거죠?

2022-01-20 13:11 UTC, socar-jian commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +리팩토링 작업은 한두 개의 함수를 개선하는 것으로 충분한 때도 있지만, 때로는 여러 개의 파일을 전체적으로 고치고 나서야 끝이 나는 경우도 있습니다.
자기소개를 먼저 넣어보니 개인적으로 조금 어색한 느낌이 들어서, 일반적인 상황을 설명하고 자기소개를 한 뒤 제가 겪었던 경험을 적는 순서로 작성해보았습니다. 만약 필요하다면 자기소개를 앞으로 옮기는 것도 가능합니다!

2022-01-20 13:11 UTC, socar-jian commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +# 리팩토링 검토
오 이 부분은 어떻게 하면 되나요? 가이드는 어디서 볼 수 있을까요?

2022-01-20 13:17 UTC, socar-jian commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +안드로이드에서 뷰에 접근하는 방식은 [계속해서 바뀌어](https://medium.com/mobile-app-development-publication/how-android-access-view-item-the-past-to-the-future-bb003ae84527) 왔습니다.
그러네요 혼용해서 사용하고 있었군요...!

2022-01-20 13:17 UTC, socar-jian commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +그리고 자칫 길어질 뻔했던 그 반복적인 작업은 IntelliJ platform plugin을 통해서 훨씬 수월해질 수 있었습니다.
이런 컨벤션이 있었군요...

2022-01-24 02:31 UTC, socar-hardy commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +리팩토링 작업은 한두 개의 함수를 개선하는 것으로 충분한 때도 있지만, 때로는 여러 개의 파일을 전체적으로 고치고 나서야 끝이 나는 경우도 있습니다.
전 상관없다고 생각이 들어서, 카일 판단에 맡깁니다!

2022-01-24 05:32 UTC, socar-hardy approved these changes

2022-01-28 01:41 UTC, socar-jian commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +이 부분만 놓고 보면 단순하게 regex를 사용해서 치환해도 어떻게든 가능할 것 같다는 생각이 듭니다.
일단 의도는 한줄로 쓰는 것이었습니당

2022-01-28 01:41 UTC, socar-hardy commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +# 리팩토링 검토
따로 디엠 드렸씁니다.

2022-01-28 01:43 UTC, socar-hardy commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +이 부분만 놓고 보면 단순하게 regex를 사용해서 치환해도 어떻게든 가능할 것 같다는 생각이 듭니다.
네. '개행'을 의도하신거 같은데, 실수로 적용을 안하신게 아닌가해서 카일이 더블 체킹해주신거 같아요.
마크다운에서 '개행'은 띄어쓰기 두번을 해야합니다. 개행을 의도하신게 아니라면 이 커멘트는 패스하셔도 됩니다.

2022-01-28 03:43 UTC, socar-jian commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +이 부분만 놓고 보면 단순하게 regex를 사용해서 치환해도 어떻게든 가능할 것 같다는 생각이 듭니다.
앗 그렇군요. 저같은 경우에는 수정시 표시되는 diff 를 줄이고, 한 문장의 길이가 얼마나 되나 직관적으로 파악하기 위해서 매 문장 뒤에 엔터를 한번씩 치고 있었어요. 문단 구분때는 두번씩 치구요.

그렇지만 그와는 별개로 문장을 수정해서 14a3d47 에 적용했습니당

2022-01-28 03:44 UTC, socar-jian commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +# 리팩토링 검토
83c7e21 에서 제목을 한단계씩 추가했습니다. 왼쪽에 보이는 목차는 `###` 까지만 보이나보네요 ㅋㅋ

2022-02-03 06:42 UTC, socar-kyle approved these changes

2022-02-03 06:42 UTC, socar-kyle commented
/맞춤법

2022-02-03 06:51 UTC, arngard commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +안녕하세요, 쏘카 안드로이드 팀의 지안입니다. 저희 안드로이드 팀에서도 몇 개월 전, 광범위한 코드에 대한 리팩토링을 수행한 경험이 있습니다.
"안녕하세요, 쏘카 안드로이드 팀의 지안입니다." 이 소개가 맥락에 어긋나게 들어가 있는 것 같고, 없어야 자연스럽게 쭉 읽힐 것 같습니다. 글 하단에 소개 섹션을 두거나, 그냥 이 문장만 처음 단락으로 두는 게 나을 것 같습니다.

2022-02-03 06:53 UTC, arngard commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +그러나 ButterKnife의 README 파일에도 적혀있듯이, View Binding을 사용하라는 권고는 늘 마음 한편(과 기술 부채 목록)에 남아있었죠.
```suggestion
그러나 ButterKnife의 README 파일에도 적혀있듯이, View Binding을 사용하라는 권고는 늘 마음 한편과 기술 부채 목록에 남아있었죠.
```
괄호가 없어도 될 것 같습니다.

2022-02-03 07:02 UTC, arngard commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +#### 모든 KtClass 이름 출력
이 부분이 ### 아닌가요? 아래도 #### 인 것들 모두 ### 아닌가 싶습니다. 설령 다른 준위로 구분지을 수 있더라도, 내용이 줄글로 쓰인 만큼, 깊은 준위를 두지않고 그냥 동등한 준위를 사용해도 될 것 같습니다.

2022-02-03 07:13 UTC, socar-jian commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +#### 모든 KtClass 이름 출력
넵 ###까지만 써도 될 것 같네요. 왼쪽의 목차에서도 보이게 되었군요.

2022-02-03 07:18 UTC, socar-jian commented on _posts/2021-12-29-refactoring-with-intellij-plugin.md
> +안녕하세요, 쏘카 안드로이드 팀의 지안입니다. 저희 안드로이드 팀에서도 몇 개월 전, 광범위한 코드에 대한 리팩토링을 수행한 경험이 있습니다.
[위의 코멘트](https://github.com/socar-inc/socar-inc.github.io/pull/103#discussion_r788415734)에서도 같은 내용이 나온 것을 보니 중간에 있는 것이 일반적으로 어색하게 보이나보네요. [8ca4440](https://github.com/socar-inc/socar-inc.github.io/pull/103/commits/8ca44403a8c707f0c6cdcd9d9db38314c7acc0fe)에서 맨앞으로 당겨왔습니다.

2022-02-03 07:32 UTC, arngard approved these changes

2022-02-03 08:21 UTC, merged