쏘카의 데이터 디스커버리 플랫폼 도입기 - 1편. 데이터 디스커버리란? (feat.Datahub VS Amundsen)
socar-inc/socar-inc.github.io pull request #115
Opened 2022-01-17 01:47 UTC by socar-dini

* `메타데이터 플랫폼` 보다는 `데이터 디스커버리 플랫폼` 이 더 보편적으로 쓰이는 것 같아, 전체적으로 용어를 수정하였습니다. 
* 스크린샷을 어떻게 사용할지가 조금 고민입니다. - 비교 항목마다 1개 이상의 스크린샷을 첨부할지, 아니면 생략하고 넘어가는 항목도 있을지를 고민하고 있습니다.

2022-01-20 03:09 UTC, socar-hardy requested changes

2022-01-20 03:09 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> + 흥미로운 점은, 같은 기능을 수행할때 Datauhb 와 Amundsen 의 script 길이 차이였습니다 Datahub 에서는 10줄 내외의 직관적인 yaml 코드로 가능한 반면, Amundsen의 script는 때에 따르지만 기본적으로 50 줄 이상이었습니다. 개인적으로 스크립트가 긴 만큼 섬세한 커스텀이 가능하거나 필요하다는 생각은 들지 않았고, 오
```suggestion
 흥미로운 점은, 같은 기능을 수행할때 Datauhb 와 Amundsen 의 **script 길이 차이**였습니다 Datahub 에서는 10줄 내외의 직관적인 yaml 코드로 가능한 반면, Amundsen의 script는 때에 따르지만 기본적으로 50 줄 이상이었습니다. 개인적으로 스크립트가 긴 만큼 섬세한 커스텀이 가능하거나 필요하다는 생각은 들지 않았고, 오히려 읽기 무겁다는 생각이 들었습니다. (공식 깃헙에 있는 샘플이 400줄이었습니다.)
```

대상 독자에게 중요하다고 생각되는거 볼드처리 부탁드림다 (전체적으로)

2022-01-20 03:09 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +개인 차가 있을 수 있으나, 내부 의견으로는 Datahub 이 훨씬 깔끔하고 보기 편하다는 의견이 많았습니다. Datahub UI 는 [공식 데모 사이트](https://demo.datahubproject.io/)에서 좀더 확인하실 수 있습니다. (Amundsen은 따로 데모사이트를 제공하지 않습니다.)
```suggestion
개인 차가 있을 수 있으나, 팀원들의 의견으로는 Datahub 이 훨씬 깔끔하고 보기 편하다는 의견이 많았습니다. Datahub UI 는 [공식 데모 사이트](https://demo.datahubproject.io/)에서 좀더 확인하실 수 있습니다. (Amundsen은 따로 데모사이트를 제공하지 않습니다.)
```

2022-01-20 03:09 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +![amundsen-main](/img/data-discovery-platform-01/amundsen-main.png)*아문센 상세 UI*
```suggestion
![amundsen-main](/img/data-discovery-platform-01/amundsen-main.png)*Amundsen 상세 UI*
```

전체적으로 용어 한/영 한쪽으로 통일시켜주세여

2022-01-20 03:09 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +* Amundsen 역시 테이블 별 / 칼럼 별 마크다운 제한적인 문서 작성이 가능하고, 원본소스의 description 을 보존하지 않습니다.
```suggestion
- Datahub 
  - 테이블 별 / 칼럼 별 태그 부여가 가능합니다.
  - 테이블 별 / 칼럼 별 풍부한 마크다운 문서 작성이 가능하고, 원본 소스의 description 을 보존합니다.
- Amundsen 
  - 테이블 별 태그 부여가 가능합니다.
  - 역시 테이블 별 / 칼럼 별 마크다운 제한적인 문서 작성이 가능하고, 원본소스의 description 을 보존하지 않습니다.
```

1) 을 보면 이런식으로 불렛 비교가 되어있습니다. 2)~ 모두 이런식으로 일관되게 적어주시는게 읽기 좋을듯 합니다.

2022-01-20 03:09 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +중요한 점은, 플랫폼 UI 상에서 테이블 혹은 칼럼의 설명을 작성했을 때 원본 소스의 description 을 따로 확인할 수 있는지의 여부였습니다. Datahub 는 다음과 같은 방식으로 original description 을 동시에 보여주지만, Amundsen 은 딱히 그런 기능이 없었습니다. 또한 Datahub 는 원본 description 과 U
```suggestion
중요한 점은, 플랫폼 UI 상에서 테이블 혹은 칼럼의 설명을 작성했을 때 원본 소스의 description 을 따로 확인할 수 있는지의 여부였습니다. Datahub는 다음과 같은 방식으로 original description 을 동시에 보여주지만, Amundsen 은 딱히 그런 기능이 없었습니다. 또한 Datahub는 원본 description 과 UI 상 description이 별개로 버전 관리가 되고 있어서, 한쪽의 수정이 다른 쪽에 영향을 끼치지 않았습니다. 
```

명사 뒤에 "은, 는"이 다 띄워져있는데 붙여주세욥. 아 이건 맞춤법 검사로 가능하려나...?

2022-01-20 03:09 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +여기 테스트 스크린샷을 첨부하려다가, 괜히 이 기능을 시각적으로 보여줬다가 보안상으로 안 좋아보일까봐 고민하고 있는데요, 어떻게 생각하시나요?
@socar-kyle 카일에 판단에 맡깁니다.

2022-01-20 03:09 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +* Amundsen 의 경우 datafold 를 연동할 수 있습니다.
두개 스크린샷 있음 좋을듯요

2022-01-20 03:09 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +dbt 는 데이터 ETL 과정에서 T(Transform) 과정을 효율화하는 도구입니다. dbt 를 이용하면 SQL 쿼리 모듈화, 테스트, 계보 확인을 편하게 할 수 있습니다. 데이터 엔지니어링 그룹 내에서 dbt 를 PoC 하고 있었기 때문에, 이 측면에서 Datahub 가 좀더 매력적으로 보였습니다.
dbt 공홈 링크걸어주시면 좋을거 같아여

2022-01-20 03:09 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +![datahub-slack-03](/img/data-discovery-platform-01/datahub-slack-03.png)*디니 콜3*
```suggestion
![datahub-slack-01](/img/data-discovery-platform-01/datahub-slack-01.png)*디니 콜 1*

![datahub-slack-02](/img/data-discovery-platform-01/datahub-slack-02.png)*디니 콜 2*

![datahub-slack-03](/img/data-discovery-platform-01/datahub-slack-03.png)*디니 콜 3*
```

2022-01-20 03:09 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +혹시 신입 데이터 엔지니어가 어떤 일을 하는지 궁금하시다면, [쏘카 신입 데이터 엔지니어 디니의 4개월 회고](https://tech.socarcorp.kr/data/2021/12/28/data-engineering-team-onboarding.html) 에서 확인하실 수 있습니다. (데이터 엔지니어링팀이 데이터 엔지니어링 그룹으로 바뀌고 데이터 웨어하우
```suggestion
> 쏘카에서 신입 데이터 엔지니어가 어떤 일을 하는지 궁금하시다면, [쏘카 신입 데이터 엔지니어 디니의 4개월 회고](https://tech.socarcorp.kr/data/2021/12/28/data-engineering-team-onboarding.html)에서 확인하실 수 있습니다. (데이터 엔지니어링팀이 데이터 엔지니어링 그룹으로 바뀌고 데이터 웨어하우스 팀, 데이터 플랫폼 팀, 모비딕 팀으로 세분화 되었어요.) 
```

2022-01-20 03:09 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +고민 : 3.비교분석 부분에 이상적으로는 매 항목마다 스크린샷을 넣고 싶은데, 그렇게 하면 글이 너무 길어지고 스크린샷이 차지하는 비중이 너무 많아지는 것 같아 고민입니다. 어떻게 하는게 좋을까요?(지금처럼 가끔씩 넣는다 / 글이 길어지더라도 모든 항목에 스크린샷을 넣는다)
노노 다 넣으면 좋을거같음. 충분히 좋아여

2022-01-21 01:11 UTC, socar-dini commented on _posts/2022-01-13-metadata-platform-01.md
> +## 데이터 디스커버리 플랫폼의 정의
Data Discovery Platform (DDP) 라는 용어가 있기는 합니다. (https://news.hada.io/topic?id=3247, https://blog.banksalad.com/tech/the-starting-of-datadiscoveryplatform-era-in-banksalad/)

2022-01-21 01:12 UTC, socar-dini commented on _posts/2022-01-13-metadata-platform-01.md
> +이런 데이터 디스커버리에는 "메타데이터"라는 개념이 중요합니다. 메타데이터는 간단히 말해서 테이블 정보, 칼럼 정보, 코멘트, 테이블을 만든 사람(오너), 테이블 사이의 관계 (데이터 리니지) 등을 말합니다. 이러한 메타데이터가 잘 관리되는 것이 데이터 디스커버리의 초석입니다.
두 의미 모두 쓰일 수 있을 것 같습니다.

2022-01-21 01:13 UTC, socar-dini commented on _posts/2022-01-13-metadata-platform-01.md
> +* Datahub는 yaml 파일을 실행하여 메타데이터를 주입합니다.
실행 설정에 가깝습니다. 정확하게는 메타데이터 소스의 주소와 접근 계정, 기타 설정이 들어가 있습니다.

2022-01-21 02:23 UTC, socar-dini commented on _posts/2022-01-13-metadata-platform-01.md
> +## 데이터 디스커버리 플랫폼의 정의
(왜 댓글이 지워졌을까요...!) Data Discovery Platform 이라는 말이 있기는 합니다. (https://whatis.techtarget.com/definition/data-discovery-platform, https://news.hada.io/topic?id=3247, https://blog.banksalad.com/tech/the-starting-of-datadiscoveryplatform-era-in-banksalad/)

2022-01-21 03:24 UTC, socar-dini commented on _posts/2022-01-13-metadata-platform-01.md
> +* Datahub는 yaml 파일을 실행하여 메타데이터를 주입합니다.
실행 설정에 가깝습니다 . 메타데이터를 끌어올 데이터 소스의 주소, 관련 계정, datahub 서버 주소, 주입 관련 설정 등이 모두 포함되어 있습니다.

2022-01-21 03:43 UTC, socar-hardy requested changes

2022-01-21 03:43 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +* Amundsen 은 아직 자체적으로 권한 설정을 지원하지 않습니다.
여기도 위처럼 Datahub, Amundsen 두개 불렛으로 나눠서 써주시는게 일관적일듯요!

2022-01-21 03:43 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +Data Discovery에서는 데이터 사용자의 이용 패턴도 중요한 요소 중 하나로 꼽힙니다. Datahub 는 시각화된 이용 분석 페이지가 따로 존재하여 자주 검색된 데이터셋  / 자주 수행된 액션 등을 그래프로 확인 할 수 있었습니다.(데모사이트 에서 [해당 페이지](https://demo.datahubproject.io/analytics)를 직접 확
여기도!

2022-01-21 03:43 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +* Databook : Uber에서 만든 인하우스 플랫폼 입니다.
얘는 링크 없는거강용?

2022-01-21 03:43 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +* [Amundsen](https://github.com/amundsen-io/amundsen) :  Lyft에서 만든 플랫폼입니다.
```suggestion
* [Amundsen](https://github.com/amundsen-io/amundsen) : Lyft에서 만든 플랫폼입니다.
```

2022-01-21 03:45 UTC, socar-dini commented on _posts/2022-01-13-metadata-platform-01.md
> +* Databook : Uber에서 만든 인하우스 플랫폼 입니다.
넵..

2022-01-21 03:45 UTC, socar-dini commented on _posts/2022-01-13-metadata-platform-01.md
> +* Amundsen 은 아직 자체적으로 권한 설정을 지원하지 않습니다.
아하 알겠습니다

2022-01-21 03:55 UTC, socar-dini commented on _posts/2022-01-13-metadata-platform-01.md
> +* Databook : Uber에서 만든 인하우스 플랫폼 입니다.
https://eng.uber.com/databook/ <-이런 우버 기술 블로그 소개글이 있긴 한데.. 다른 플랫폼 처럼 공식 사이트도 아니고 4년 전 글이기도 해서 생략했습니다.

2022-01-21 03:56 UTC, socar-dini commented on _posts/2022-01-13-metadata-platform-01.md
> +* Databook : Uber에서 만든 인하우스 플랫폼 입니다.
이거라도 걸어놓는게 나을까요?

2022-01-24 02:24 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +* Databook : Uber에서 만든 인하우스 플랫폼 입니다.
넵 저는 이거라도 ...

2022-01-24 02:25 UTC, socar-hardy commented
디니 git fetch & git rebase origin/master 한번 해주세요.

2022-01-24 02:30 UTC, socar-hardy requested changes

2022-01-24 02:30 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +```
요거 이제 컨펌 받아주세요 ㅋㅋㅋㅋ

2022-01-24 02:30 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +* Amundsen 은 아직 자체적으로 권한 설정을 지원하지 않습니다.
여기도 위처럼 일관되게.. 수정해주시며 좋을거가타여

- Datahub 는..
- Amundsen 은 ...

2022-01-24 02:30 UTC, socar-hardy commented on _posts/2022-01-13-metadata-platform-01.md
> +  - 역시 테이블 별 / 칼럼 별 마크다운 제한적인 문서 작성이 가능하고, 원본소스의 description 을 보존하지 않습니다.
두 개의 차이점을 드러내는 단락에서 전체적으로 이 처럼 수정해주시면 좋을거 같아요. 

- Datahub ..
- Amundsen ...

2022-01-24 02:43 UTC, socar-dini commented on _posts/2022-01-13-metadata-platform-01.md
> +* Amundsen 은 아직 자체적으로 권한 설정을 지원하지 않습니다.
아이고 바보인가 푸시를 안해놨네요..

2022-01-24 03:18 UTC, socar-dini commented on _posts/2022-01-13-metadata-platform-01.md
> +```
이거 두분 다 컨펌 받았습니다!

2022-01-24 05:07 UTC, socar-hardy commented
가운데에 디니가 메모해두신 부분(사진 관련)만 해결되면 Approve 드립니다!

2022-01-24 05:27 UTC, socar-hardy approved these changes

2022-01-27 13:56 UTC, socar-kyle requested changes
고생하셨습니다! 일단 몇개 피드백드렸습니다!! :) 좋은 글이라 기대되네요..!!

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +title:  "쏘카의 데이터 디스커버리 플랫폼 도입기 - 1편. 데이터 디스커버리란? "
데이터 디스커버리랑 메타데이터 플랫폼 고민되긴 하네요 ㅋㅋㅋㅋ 이건 좀 더 이야기해보시죵!!!

데이터허브엔 메타데이터 플랫폼이라고 해서 저는 그걸 따라주면 어떨까 싶었어요
제목에 Datahub vs Amudsen을 넣고 싶긴 하네요..!

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +회사의 데이터베이스에서 원하는 데이터를 찾으려고 할때도 비슷한 일이 발생합니다. 어느 데이터가 어디에 있는지, 이 데이터는 무슨 의미인지에 대한 안내가 없으면 데이터를 이용하기가 불편할 것입니다. 이런 문제를 해결하기 위해 데이터의 위치와 의미를 한눈에 보게 돕는 플랫폼이 **"데이터 디스커버리 플랫폼"(DDP, Data Discovery Platform
```suggestion
데이터 분석, 머신러닝을 위해 회사의 데이터베이스에서 원하는 데이터를 찾으려고 할때도 비슷한 일이 발생합니다. 어느 데이터가 어디에 있는지, 이 데이터는 무슨 의미인지에 대한 안내가 없으면 데이터를 이용하기가 불편할 것입니다. 이런 문제를 해결하기 위해 데이터의 위치와 의미를 한눈에 보게 돕는 플랫폼이 **"데이터 디스커버리 플랫폼"(DDP, Data Discovery Platform)**입니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +**데이터 디스커버리(Data Discovery)**란, "원하는 데이터를 쉽고 빠르게 찾을 수 있다" 의 개념입니다. 빅 데이터 시대라는 흐름에 맞게, 회사에도 많은 양의 데이터가 여러 형태로 존재하게 되었습니다. 그리고 많은 사람이 데이터를 생산 및 소비하고 시간이 지나게 되면서 히스토리 파악도 점점 복잡해지기 시작합니다. 이런 상황에서 데이터 디스커
빅 데이터 => 빅데이터

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +**데이터 디스커버리(Data Discovery)**란, "원하는 데이터를 쉽고 빠르게 찾을 수 있다" 의 개념입니다. 빅 데이터 시대라는 흐름에 맞게, 회사에도 많은 양의 데이터가 여러 형태로 존재하게 되었습니다. 그리고 많은 사람이 데이터를 생산 및 소비하고 시간이 지나게 되면서 히스토리 파악도 점점 복잡해지기 시작합니다. 이런 상황에서 데이터 디스커
```suggestion
**데이터 디스커버리(Data Discovery)**란, "원하는 데이터를 쉽고 빠르게 찾을 수 있다" 의 개념입니다. 빅데이터 시대라는 흐름에 맞게, 회사에도 많은 양의 데이터가 여러 형태로 존재하게 되었습니다. 그리고 많은 사람이 데이터를 생산 및 소비하고 시간이 지나게 되면서 히스토리 파악도 점점 복잡해지기 시작합니다. 이런 상황에서 데이터 디스커버리는 데이터 이용자에게 **"어떤 데이터"가 "어디에" "어떻게 존재"하는지에 대한 정보를 편리하게 제공**합니다. 
```

빅데이터...빅데이터................... 빅을 뺄까요?

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +이런 데이터 디스커버리에는 **"메타데이터"**라는 개념이 중요합니다. 메타데이터는 간단히 말해서 테이블 정보, 칼럼 정보, 코멘트, 테이블을 만든 사람(오너), 테이블 사이의 관계 (데이터 리니지) 등을 말합니다. 이러한 메타데이터를 잘 관리하는 것이 데이터 디스커버리의 초석입니다.
```suggestion
이런 데이터 디스커버리에는 **"메타데이터"**라는 개념이 중요합니다. 메타데이터는 간단히 말해서 테이블 정보, 컬럼 정보, 코멘트, 테이블을 만든 사람(오너), 테이블 사이의 관계(데이터 리니지) 등을 말합니다. 이러한 메타데이터를 잘 관리하는 것이 데이터 디스커버리의 핵심 역할입니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +이런 데이터 디스커버리에는 **"메타데이터"**라는 개념이 중요합니다. 메타데이터는 간단히 말해서 테이블 정보, 칼럼 정보, 코멘트, 테이블을 만든 사람(오너), 테이블 사이의 관계 (데이터 리니지) 등을 말합니다. 이러한 메타데이터를 잘 관리하는 것이 데이터 디스커버리의 초석입니다.
- 칼럼 => 컬럼으로 모두 수정해주세요
- 괄호는 항상 붙여주세요!
- 초석..? 살짝 덜 와닿네요

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +데이터를 적극적으로 활용하는 기업에서, 업무 효율성에 있어서 데이터 디스커버리는 매우 중요한 부분입니다. 사내에 많은 직원들이 데이터를 활용하여 분석, 기획 등의 업무에 이용하려고 할텐데, 자신에게 필요한 데이터가 "어디에 있는지", "이 데이터가 어떤 의미인지"를 파악하는 데에 대부분의 시간을 소요하게 된다면, 업무 효율성이 매우 떨어지게 될 겁니다.
```suggestion
데이터를 적극적으로 활용하는 기업은 데이터 디스커버리의 존재에 따라 업무 효율성이 크게 달라집니다. 사내에 많은 직원들이 데이터를 활용해 데이터 분석, 머신러닝, 데이터 기반 기획 등을 하고 있습니다. 각자의 목적에 맞는 데이터가 "어디에 있는지", "이 데이터가 어떤 의미인지"를 파악하는 데에 대부분의 시간을 소요하게 된다면, 업무 효율성이 매우 떨어지게 될 겁니다.  
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +데이터 디스커버리를 가능하게 하는 플랫폼입니다. 주로 웹 형태로 제공되며, 데이터의 구조와 관계 등 메타데이터를 한 곳에서 쉽게 보고 검색할 수 있습니다. (같은 이유로, 메타데이터 플랫폼 이라는 용어로 쓰이기도 합니다.) 예시로는 다음이 있습니다.
```suggestion
데이터 디스커버리를 가능하게 하는 플랫폼입니다. 웹 UI 환경을 제공하며, 데이터의 구조와 관계 등 메타데이터를 한 곳에서 쉽게 보고 검색할 수 있습니다. (같은 이유로 데이터 디스커버리는 메타데이터 플랫폼이라는 용어로 쓰이기도 합니다.) 대표적인 데이터 디스커버리 프레임워크는 다음과 같습니다.
```

- 주로 웹 형태? 라는게 조금 어색하기도 한 느낌이에요. 웹 UI 환경을 제공하며, 라고 하면 어떨까 싶네요
- 디니가 쉼표를 많이 사용하셔서 삭제할게요

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +#### Data Discovery 의 관점
```suggestion
#### Data Discovery의 관점 
```

여기서 영어로 쓰신 이유가 있을까요?

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +쏘카에서는 PM, 마케터, 분석가 등 여러 직군이 업무에 데이터를 활용합니다. 하지만 쏘카 안에서 데이터가 다양한 형식으로 존재하기도 하고, 비개발 직군 입장에서는 DB에 직접 접근하는 것도 허들이 있었습니다. 따라서  "어떤 데이터를 어디서 찾아야 하는지", 혹은 "이 테이블의 데이터가 어떤 의미인지" 에 대한 질문을 기존에는 슬랙 채널을 이용하여 수기
```suggestion
쏘카에서는 데이터 분석가, PM, 마케터 등 여러 직군이 업무에 데이터를 활용합니다. 하지만 데이터가 다양한 형식으로 존재하고, 비개발 직군 입장에서는 DB에 직접 접근하는 것도 어려움이 있습니다. 기존에 스키마에 대한 정보를 알려주는 어드민이 있었지만, 유지보수가 되고 있지 않았습니다. 이런 이유로  "어떤 데이터를 어디서 찾아야 하는지", 혹은 "이 테이블의 데이터가 어떤 의미인지" 에 대한 질문을 기존에는 슬랙 채널을 이용해 받곤 했습니다. 이런 방식은 히스토리 파악도 쉽지 않고, 답변하는 사람의 시간을 많이 사용하게 됩니다.
```

- 이런 글에선 과거형이 아니라 현재형을 사용할 수 있으면 현재형을 쓰셔도 괜찮아요
- 기존에 없진 않아서 내용 추가

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +background : "/assets/images/discovery-bg.jpg"
세로로 너무 길어서 잘라주시면 좋을듯하네요!

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +![data-ask-jung](/img/data-discovery-platform-01/data-ask-jung.png)*데이터의 의미를 찾아 헤매는 정*
브라운, 일론, 정, 디펜과 이야기해보셨나요? 정의 테이블 이름은 삭제해주시면 좋을 것 같아요
데이터 그룹분들이 질문한 것을 찾아보시는 것도 좋을듯!

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +데이터 디스커버리 플랫폼을 도입하면, 개발에 대한 도메인이 없더라도 간편한 UI 를 통해서 메타데이터를 확인할 수 있습니다.
```suggestion
데이터 디스커버리 플랫폼을 도입하면 개발에 대한 도메인이 없더라도 간편한 UI를 통해서 메타데이터를 확인할 수 있습니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +#### Data Governance 의 관점
```suggestion
#### Data Governance의 관점
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +디스커버리 플랫폼을 선정하기 전, 공식 문서 등의 지원이 풍부하고, 일반적으로 많이 쓰이는 Datahub와 Amundsen을 직접 배포하고 테스트하며 비교하는 PoC 과정을 거쳐보기로 했습니다.
```suggestion
디스커버리 플랫폼을 선정하기 전, 공식 문서 등의 지원이 풍부하고 일반적으로 많이 쓰이는 Datahub와 Amundsen을 직접 배포하고 테스트하며 비교하는 PoC 과정을 거쳐보기로 했습니다. 
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +### 0) 구조
왜 0부터죠........................ㅎ?

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +반면에 차이점은, Datahub 는 데이터를 주입할때 Kafka 를 사용한다는 점입니다. 즉 메타데이터 플랫폼 프레임워크의 히스토리를 살펴봤을 때, Amundsen 은 1세대 (Monolith) 방식인 반면, Datahub는 3세대 (Event-based) 방식입니다. 메타데이터 플랫폼의 히스토리에 대해서 좀더 궁금하신 분들은, LinkedIn 의 엔지니
```suggestion 
차이점은 Datahub는 데이터를 주입할때 Kafka를 사용하고 Amundsen은 XXX을 사용하는 점입니다. 메타데이터 플랫폼 프레임워크의 히스토리를 살펴봤을 때, Amundsen 은 Monolith 방식인 반면 Datahub는 Event-based 방식입니다. 메타데이터 플랫폼의 히스토리에 대해서 좀더 궁금하신 분들은, LinkedIn의 엔지니어링 블로그에 작성된 [DataHub: Popular metadata architectures explained](https://engineering.linkedin.com/blog/2020/datahub-popular-metadata-architectures-explained) 글을 보시는 것을 추천합니다. 
```

1세대와 3세대를 쓰는게 좋을지, Monolith, Event Based라고 할지 고민되긴 하네요!

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +  * `datahub CLI` 를 이용하여 yaml 파일을 실행합니다.
```suggestion
  * `datahub CLI`를 이용하여 yaml 파일을 실행합니다. 
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +  * 연결하는 데이터 소스에 따라 Datahub 라이브러리에 따라오는 연결 플러그인 설치가 한두개 필요합니다.
```suggestion
  * 연결하는 데이터 소스에 따라 Datahub 라이브러리에 따라오는 연결 플러그인 설치가 필요합니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +* Amundsen 은 `python` 파일 를 실행하여 메타데이터를 주입합니다.
```suggestion
* Amundsen은 `python` 파일을 실행하여 메타데이터를 주입합니다. 
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +  * 기본적으로 `amundsen databuilder` 라는 python 라이브러리 (ETL framework) 를 사용하며, Extract, Transform, Load 각 과정에 여러 자체 모듈을 끌어와서 사용하는 방식입니다.
```suggestion
  * 기본적으로 `amundsen databuilder` 라는 Python 라이브러리 (ETL framework) 를 사용하며, Extract, Transform, Load 각 과정에 여러 자체 모듈을 끌어와서 사용하는 방식입니다. 
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +  * 이 외에도 종종 여러 디펜던시가 필요했습니다.
```suggestion
  * 이 외에도 종종 여러 디펜던시가 필요했습니다. 
```

이 내용을 담으려면 디펜던시(xxx)라고 써주시면 좋을듯하네요!

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +![datahub-ingestion-script](/img/data-discovery-platform-01/datahub-ingestion-script.png)*Datahub -  Bigquery 데이터 주입 script*
```suggestion
![datahub-ingestion-script](/img/data-discovery-platform-01/datahub-ingestion-script.png)*Datahub -  BigQuery 데이터 주입 script*
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +![amundsen-ingestion-script](/img/data-discovery-platform-01/amundsen-ingestion-script.png)*Amundsen - Bigquery 데이터 주입 script*
```suggestion
![amundsen-ingestion-script](/img/data-discovery-platform-01/amundsen-ingestion-script.png)*Amundsen - BigQuery 데이터 주입 script*
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> + 흥미로운 점은, 같은 기능을 수행할때 Datauhb 와 Amundsen 의 **script 길이 차이**였습니다 Datahub 에서는 10줄 내외의 직관적인 yaml 코드로 가능한 반면, Amundsen의 script는 때에 따르지만 기본적으로 50 줄 이상이었습니다. 개인적으로 스크립트가 긴 만큼 섬세한 커스텀이 가능하거나 필요하다는 생각은 들지 않았
```suggestion
 흥미로운 점은 같은 기능을 수행할 때 Datahub와 Amundsen의 **script 길이 차이**였습니다. Datahub는 10줄 내외의 직관적인 yaml 코드로 가능한 반면, Amundsen의 script는 기본적으로 50 줄 이상이었습니다. 개인적으로 스크립트가 긴 만큼 섬세한 커스텀이 가능하거나 필요하다는 생각은 들지 않았고, 오히려 읽기 무겁다는 생각이 들었습니다(공식 깃헙에 있는 샘플이 400줄이었습니다)
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +개인 차가 있을 수 있으나, 팀원들의 의견으로는 **Datahub 이 훨씬 깔끔하고 보기 편하다**는 의견이 많았습니다. Datahub UI 는 [공식 데모 사이트](https://demo.datahubproject.io/)에서 좀더 확인하실 수 있습니다. (Amundsen은 따로 데모사이트를 제공하지 않습니다.)
```suggestion
개인 차가 있을 수 있으나, 팀원들의 의견으로는 **Datahub가 훨씬 깔끔하고 보기 편하다**는 의견이 많았습니다. Datahub UI는 [공식 데모 사이트](https://demo.datahubproject.io/)에서 더 확인하실 수 있습니다. (Amundsen은 따로 데모 사이트를 제공하지 않습니다)
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +  - 테이블 별 / 칼럼 별 풍부한 마크다운 문서 작성이 가능하고, 원본 소스의 description 을 보존합니다.
영단어는 대문자로 시작해주세요!
```suggestion
  - 테이블 별 / 칼럼 별 풍부한 마크다운 문서 작성이 가능하고, 원본 소스의 Description을 보존합니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +  - 역시 테이블 별 / 칼럼 별 마크다운 제한적인 문서 작성이 가능하고, 원본소스의 description 을 보존하지 않습니다.
```suggestion
  - 역시 테이블 별 / 칼럼 별 마크다운 제한적인 문서 작성이 가능하고, 원본 소스의 Description을 보존하지 않습니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +중요한 점은, 플랫폼 UI 상에서 테이블 혹은 칼럼의 설명을 수정했을 때 **원본 소스의 description 을 따로 확인할 수 있는지**의 여부였습니다. Datahub는 다음과 같은 방식으로 original description 을 동시에 보여주지만, Amundsen 은 딱히 그런 기능이 없었습니다. 또한 Datahub는 원본 description 과
```suggestion
중요한 점은 플랫폼 UI 상에서 테이블 혹은 칼럼의 설명을 수정했을 때 **원본 소스의 Description을 따로 확인할 수 있는지**의 여부였습니다. Datahub는 다음과 같은 방식으로 Original Description을 동시에 보여주지만, Amundsen은 이런 기능이 없습니다. 또한 Datahub는 원본 Description과 UI 상 Description이 별개로 버전 관리가 되고 있어서, 한쪽의 수정이 다른 쪽에 영향을 끼치지 않았습니다. 
```

- 이런 기능이 없었습니다 => 현재는 있을까요? 글에서 과거형을 쓸 때는 과거와 현재가 다를 때 쓴다고 보시면 될 것 같아요!
- 이 부분 Original Description이라고 설명하는 내용이 조금 더 어려운 것 같아요. 사람들이 쓰는 패턴으로 설명하면 어떨까요? (A라는 사람이 수정하면 덮어쓰기가 될까요? 이런 내용)

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +![datahub-dataset](/img/data-discovery-platform-01/datahub-description.png)*Datahub - UI 상 수정을 하더라도 "Original"(원본 코멘트) 이 함께 표기됩니다.*
```suggestion
![datahub-dataset](/img/data-discovery-platform-01/datahub-description.png)*Datahub - UI 상에서 수정하더라도 "Original"(원본 코멘트)이 함께 표기됩니다.*
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +* Datahub 는 테이블에 유저 / 그룹 단위로 오너십을 지정할 수 있습니다.
```suggestion
* Datahub는 테이블에 유저 / 그룹 단위로 오너십을 지정할 수 있습니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +* Amundsen 은 테이블에 유저 단위로만 오너십을 지정할 수 있습니다.
```suggestion
* Amundsen은 테이블에 유저 단위로만 오너십을 지정할 수 있습니다.
```

여기서 오너십은 무엇일까요? 권한 관리..?

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +Datahub 는 메타데이터 주입 시 사용하는 yaml 파일에서 SQL profiling 기능을 활성화 할 수 있습니다. 이 기능을 이용하면 컬럼 별 통계와 해당 컬럼의 샘플 데이터를 볼 수 있습니다. 현재는 이 기능은 보안상 사용하지 못하도록 막아두었습니다. Amundsen 은 pandas 를 연결하여 비슷한 기능을 구현할 수 있다고 합니다.
```suggestion
Datahub는 메타데이터 주입 시 사용하는 yaml 파일에서 SQL profiling 기능을 활성화 할 수 있습니다. 이 기능을 이용하면 컬럼 별 통계와 해당 컬럼의 샘플 데이터를 볼 수 있습니다. Amundsen 은 Pandas를 연결하여 비슷한 기능을 구현할 수 있다고 합니다. 
```

이 내용은 굳이 작성하지 않아도 될 것 같아요

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +#### 6) 데이터 계보 (Data Lineage)
```suggestion
#### 6) 데이터 계보(Data Lineage)
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +데이터 계보 (Data Lineage) 란 데이터의 흐름을 시각화한 개념으로, 특정 테이블이 어떤 테이블들을 참조하는지, 데이터가 어디에서 와서 어디로 흘러가는 지를 편리하게 알 수 있습니다.
```suggestion
데이터 계보(Data Lineage)란 데이터의 흐름을 시각화한 개념으로 특정 테이블이 어떤 테이블들을 참조하는지, 데이터가 어디에서 와서 어디로 흘러가는지를 편리하게 알 수 있습니다. 
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +Datahub 와 Amundsen 모두, dbt* 등을 연동하여 데이터 계보를 시각화 할 수 있습니다. (최근에는 Datahub에 dbt 없이 BigQuery 자체에서도 데이터 계보를 가져오는 기능이 추가되었습니다.)
```suggestion
Datahub와 Amundsen 모두 dbt* 등을 연동하여 데이터 계보를 시각화 할 수 있습니다. (최근에는 Datahub에 dbt 없이 BigQuery 자체에서도 데이터 계보를 가져오는 기능이 추가되었습니다) 
```

dbt 우측에 *은 무엇일까요?

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +* Datahub 은 SSO 지원 및 세부적인 권한 설정이 가능합니다.
```suggestion
* Datahub는 SSO 지원 및 세부적인 권한 설정이 가능합니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +  * 사용자 / 그룹 단위로 정책 부여가 가능합니다. 현재는 view 관련 권한은 설정할 수 없고, 테이블이나 컬럼에 대한 설명, 오너, 태그 들을 수정할 수 있는 edit 권한을 세부적으로 조정 가능합니다.
요 부분과 오너십이 다른 부분인가요?
```suggestion
  * 사용자 / 그룹 단위로 정책 부여가 가능합니다. 현재는 View 관련 권한은 설정할 수 없고, 테이블이나 컬럼에 대한 설명, 오너, 태그 등을 수정할 수 있는 Edit 권한을 세부적으로 조정 가능합니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +  * SSO(Single Sing-On)로 keycloak, okta, google auth 를 지원합니다.
```suggestion
  * SSO(Single Sing-On)로 Keycloak, Okta, Google Auth를 지원합니다. 
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +  * Amundsen 은 아직 자체적으로 권한 설정을 지원하지 않습니다.
```suggestion
* Amundsen은 SSO을 지원하나 세부적인 권한 설정은 지원하지 않습니다.
  * SSO 로 Keycloack, Okta, Flask_oidc를 지원합니다.
  * Amundsen은 자체적인 권한 설정을 지원하지 않습니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +* Amundsen 은 pandas, neo4j 등의 조금 더 다양한 형태를 지원합니다.
```suggestion
* Amundsen은 pandas, neo4j 등의 더 다양한 형태를 지원합니다. 
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +* Datahub 는 시각화된 이용 분석 페이지가 따로 존재합니다.
```suggestion
* Datahub는 시각화된 이용 분석 페이지가 따로 존재합니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +* Amundsen 은 단편적인 이용 통계를 제공합니다.
```suggestion
* Amundsen은 단편적인 이용 통계를 제공합니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +* 공식 github repository 의 star 수를 비교했을 때 Datahub가 4.5K, Amundsen 이 3K 로 Datahub 가 좀더 우세했습니다.
```suggestion
* 공식 Github Repository의 Star 수를 비교했을 때 Datahub가 4.5K, Amundsen이 3K 로 Datahub가 더 많은 Star를 보유하고 있었습니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +* 두 플랫폼 모두 공식 슬랙, 웹사이트, github repository 등의 다양한 채널을 지원했으나, 슬랙에서 질답의 활발함이나 공식 문서의 체계성 측면에서 Datahub 가 좀더 우세했습니다.
```suggestion
* 두 플랫폼 모두 공식 슬랙, 웹사이트, Github Repository 등의 다양한 채널을 지원했으나, 슬랙의 활성화(질문, 답변의 활발함)나 공식 문서의 체계성 측면에서 Datahub가 우세했습니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +## 4. 최종 결정 : Datahub 결정 이유  <a name="final-decision"></a>
```suggestion
## 4. 최종 결정 : Datahub!  <a name="final-decision"></a>
많은 논의 후, 저희는 Datahub를 도입하기로 결정했습니다. Datahub를 도입한 결정적인 이유는 다음과 같습니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +데이터 이용자 측면에서는 위에서도 비교했듯이, Datahub 가 문서화, 오너십, 권한, 통계, 데이터 계보 관점에서 **더 다양하고 풍부한 기능들을 지원**합니다. 이런 기능들이 실제로 도입됐을 때, 이용자가 원하는 데이터를 빠르게 찾고 쏘카의 데이터 디스커버리를 발전시키는 데에 더 많은 도움을 얻을 수 있을거라 판단했습니다.
```suggestion
데이터 이용자 측면에서는 위에서도 비교했듯이, Datahub가 문서화, 오너십, 권한, 통계, 데이터 계보 관점에서 **더 다양하고 풍부한 기능들을 지원**합니다. 이런 기능들이 실제로 도입됐을 때, 이용자가 원하는 데이터를 빠르게 찾고 쏘카의 데이터 디스커버리를 발전시키는 데에 더 많은 도움을 얻을 수 있을거라 판단했습니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +플랫폼 개발자 측면에서도 **메타데이터 주입 시 Datahub가 더 편리**했습니다. 동일한 메타데이터를 주입한다고 가정했을 때 Datahub 는 10 줄 내외의 yaml 파일로 가능한 반면, Amundsen 은 100줄 이상의 python script가 필요했습니다. Amundsen script 가 긴 만큼 세세한 설정이 가능한지, 또 그런 세세한 설정
```suggestion
플랫폼 개발자 측면에서도 **메타데이터 주입 시 Datahub가 더 편리**했습니다. 동일한 메타데이터를 주입한다고 가정했을 때 Datahub는 10줄 내외의 yaml 파일로 가능한 반면, Amundsen은 100줄 이상의 Python Script가 필요했습니다. Amundsen Script가 긴 만큼 세세한 설정이 가능한지, 또 그런 세세한 설정이 가능하다고 해도 현재 상황에 필요한지를 고민해봤을 때는 의문점이 있었습니다. 따라서 쏘카의 상황에는 Datahub가 더 적절하다고 판단했습니다. 
```

쏘카의 상황에는 <- 내용이 있어서 쏘카의 상황에 대해 작성해주시면 좋을 것 같네요!

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +많은 사람이 이용하는 솔루션이나 플랫폼을 도입할때는 UI 도 무시할 수 없다고 생각합니다. PoC시 Datahub UI 가 훨씬 깔끔하다는 반응이 많았고, 매 버전마다 UI가 개선되고 있는 점도 Datahub으로 결정힌 이유 중 하나였습니다.
```suggestion
### UI의 깔끔함

많은 사람이 이용하는 솔루션이나 플랫폼을 도입할때는 UI도 무시할 수 없다고 생각합니다. PoC시 Datahub UI가 훨씬 깔끔하다는 반응이 많았고, 매 버전마다 UI가 개선되고 있기 때문에 Datahub으로 결정했습니다. 
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +Datahub 의 공식 슬랙 채널에는 현재 2000명이 넘는 사람이 활동하고 있고, 주제별로 분리된 다양한 채널에서 질답과 오류 대응이 활발하게 이루어지는 편입니다. 또한 새로운 기능을 제안 (feature request) 하는 채널도 따로 있어서, 사용자의 피드백을 풍부하게 반영하려는 노력이 느껴졌습니다. 이 뿐만 아니라 최근 발생한 Log4j 취약점
```suggestion
Datahub의 공식 슬랙 채널에는 현재 2,000명이 넘는 사람이 활동하고 있고, 주제별로 분리된 다양한 채널에서 질답과 오류 대응이 활발하게 이루어지는 편입니다. 또한 새로운 기능을 제안(Feature Request)하는 채널도 따로 있어서, 사용자의 피드백을 풍부하게 반영하려는 노력이 느껴졌습니다. 이 뿐만 아니라 최근 발생한 Log4j 취약점 사태에도 빠르게 해당 취약점을 보완한 패치가 반영되고, 모든 진행 상황이 슬랙을 통해 공유되었습니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +개인적인 경험으로는 공식 채널에 질문을 올리면 답이 안달리는 경우가 거의 없었던 것 같습니다. 국내에 데이터 디스커버리 플랫폼 관련 자료가 많지 않고, 팀에 합류하지 얼마 되지 않은 신입 엔지니어의 입장에서는 이런 활발한 서포트가 있다는 것이 매우 중요했습니다. 여담으로 PoC 과정에서 Datahub 공식 슬랙에 질문을 100개정도 던진 것 같은데, 이제
```suggestion
개인적인 경험으로는 공식 채널에 질문을 올리면 답이 안달리는 경우가 거의 없었던 것 같습니다. 국내에 데이터 디스커버리 플랫폼 관련 자료가 많지 않고, 팀에 합류하지 얼마 되지 않은 신입 엔지니어의 입장에서는 이런 활발한 서포트가 있다는 것이 매우 중요했습니다. 여담으로 PoC 과정에서 Datahub 공식 슬랙에 질문을 100개정도 한 것 같은데, 이제는 사람들이 질문이 있으면 저를 호출합니다(!) 
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +이렇게 쏘카는 데이터 디스커버리 플랫폼으로 Datahub 을 선정하게 되었습니다. 다음 편에는 구체적으로 Datahub 를 어떻게 사내 인프라 환경에 구축했는지, 메타데이터 주입 방식을 어떻게 자동화하고 효율화 했는지 설명하려고 합니다.
```suggestion
이렇게 쏘카는 데이터 디스커버리 플랫폼으로 Datahub로 선정하게 되었습니다. 다음 편에는 구체적으로 Datahub를 어떻게 사내 인프라 환경에 구축했는지, 메타데이터 주입 방식을 어떻게 자동화하고 효율화 했는지 설명하려고 합니다.
```

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +![datathub-vs-amundsen](/img/data-discovery-platform-01/datahub-vs-amundsen.png)
요거 슬랙 캡쳐보다 키노트나 슬라이드에서 정리하고, 쏘카 로고 넣으면 어떨까요?(디니 닉네임도 쓰고~)

2022-01-27 13:56 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +title:  "쏘카의 데이터 디스커버리 플랫폼 도입기 - 1편. 데이터 디스커버리란? "
디스커버리란? " <-   마지막에 띄어쓰기도 수정..!

2022-01-28 01:45 UTC, socar-kyle commented
/맞춤법

2022-01-28 01:52 UTC, socar-kyle commented
맞춤법이랑 저랑 중복이 있을 수 있습니다^_ㅠ

2022-01-28 02:10 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +#### 9) 사용자 이용 통게
오 이걸 잡아주다니

2022-01-28 02:11 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +> 쏘카에서 신입 데이터 엔지니어가 어떤 일을 하는지 궁금하시다면, [쏘카 신입 데이터 엔지니어 디니의 4개월 회고](https://tech.socarcorp.kr/data/2021/12/28/data-engineering-team-onboarding.html)에서 확인하실 수 있습니다. (데이터 엔지니어링팀이 데이터 엔지니어링 그룹으로 바뀌고 데이터 웨
엔지니어링 팀은 붙여쓰도록 하시지요!

2022-01-28 02:12 UTC, socar-kyle commented on _posts/2022-01-24-metadata-platform-01.md
> +  * 이 외에도 종종 여러 디펜던시가 필요했습니다.
이건 좀 잘못하네요

2022-02-25 04:19 UTC, socar-kyle approved these changes

2022-02-25 04:28 UTC, merged