post: 쏘카의 데이터 디스커버리 플랫폼 도입기 - 2편. GKE에 플랫폼 구축하기
socar-inc/socar-inc.github.io pull request #133
Opened 2022-03-07 09:07 UTC by socar-dini

초안을 완성하고, 퍼블리시 리뷰 요청드립니다. 
웹은 여기서 확인하실 수 있습니다: https://socar-dini.github.io/data/2022/03/15/metdata-platform-02.html

고민 포인트 
* 코드 첨부한 것이 너무 뜬금없지 않은지? -> 맥락을 더 설명하려면 DAG 코드들이 더 들어가야 할 것 같은데 너무 늘어지는 것 같아 일단 뺐음
* 스크린샷이 너무 없지 않은지? -> 코드 첨부가 이미 많은데 스크린샷이 더 들어가면 복잡하지 않을까 생각했음 . 그런데 전체적으로 도식화를 통한 설명이 부족한것 같아 고민이긴 합니다 .

2022-03-08 08:26 UTC, socar-hardy commented
일단 제목을 이전 글과 일관되고 좀 더 명확한 네이밍으로 수정해주시면 좋을거 같습니다.

**as-is**
쏘카의 데이터 디스커버리 플랫폼 도입기 - 2편. GKE에 플랫폼 구축하기

**to-be**
데이터 디스커버리 플랫폼 도입기 - 2편. GKE에 Datahub 구축하기

<img width="878" alt="image" src="https://user-images.githubusercontent.com/62049738/157196479-deabf8a2-700f-4d65-a885-6a0e7c40f540.png">

2022-03-08 08:27 UTC, socar-hardy commented
@socar-thomas 

앞으로 블로그 글은 팀장에게 Approve를 받고 나가려고 합니다.

2022-03-08 09:00 UTC, socar-hardy requested changes
일단 ##2 전까지 리뷰했습니다. 목요일에 마저 할게용.

2022-03-08 09:00 UTC, socar-hardy commented on _posts/2022-03-07-metdata-platform-02.md
> +> SSO(Single Sign-On): 한 번의 인증 과정으로 여러 컴퓨터 상의 자원을 이용 가능하게 하는 인증 기능
```suggestion
```

요 내용도 굳이 ..? 란 생각이 듭니다 ㅋㅋ

2022-03-08 12:28 UTC, socar-dini commented on _posts/2022-03-07-metdata-platform-02.md
> +#### 1.2.1 MySQL -> CloudSQL data dump
이부분 externaldatabase 지원하는지 다시 시도해보고 수정하기로 함

2022-03-10 09:03 UTC, yoonhyejin commented on _posts/2022-03-07-metdata-platform-02.md
> + 이렇게 helm chart 까지 수정하고 배포된 helm chart 를 upgrade 하면 (ex. `helm upgrade datahub`)  migration 작업은 완료되었습니다. 최종적으로 다음을 통해 정상 작동을 확인합니다.
이거 lens UI 로 직접 정의해서 yaml 파일을 굳이 올려야 할까 고민인데요.. 꼭 필요할까요?

2022-03-10 09:18 UTC, socar-dini commented on _posts/2022-03-07-metdata-platform-02.md
> + 이렇게 helm chart 까지 수정하고 배포된 helm chart 를 upgrade 하면 (ex. `helm upgrade datahub`)  migration 작업은 완료되었습니다. 최종적으로 다음을 통해 정상 작동을 확인합니다.
이거 lens UI 로 직접 정의해서 yaml 파일을 굳이 올려야 할까 고민인데요.. 꼭 필요할까요?

2022-03-14 06:32 UTC, socar-hardy commented on _posts/2022-03-07-metdata-platform-02.md
> + 이렇게 helm chart 까지 수정하고 배포된 helm chart 를 upgrade 하면 (ex. `helm upgrade datahub`)  migration 작업은 완료되었습니다. 최종적으로 다음을 통해 정상 작동을 확인합니다.
예시라도 써주시면 좋을거 같아요.

2022-03-14 06:51 UTC, socar-hardy requested changes
리뷰할거 많이 없네요! 코멘트 봐주시고 DM도 따로 드렸습니다!

2022-03-14 06:51 UTC, socar-hardy commented on _posts/2022-03-07-metdata-platform-02.md
> +데이터플랫폼 팀에서는 이런 경우 airflow 에 직접 의존성을 설치하지 않고, 필요한 의존성을 담은 docker image 를 실행하는 K8sPodOperator 를 만들어 해결하고 있습니다. 이렇게 하면 DAG 가 아무리 많아도 의존성의 충돌을 방지할 수 있습니다.
```suggestion
데이터플랫폼 팀에서는 이런 경우 airflow 에 직접 의존성을 설치하지 않고, 필요한 의존성을 담은 docker image 를 실행하는 K8sPodOperator 를 만들어 해결하고 있습니다. 이렇게 하면 DAG 가 아무리 많아도 DAG 간 사용하는 라이브러리나 환경의 의존성 충돌을 방지할 수 있습니다. 
```

2022-03-14 06:51 UTC, socar-hardy commented on _posts/2022-03-07-metdata-platform-02.md
> +COPY datahub-ingestion-bigquery /datahub-ingestion-bigquery
datahub-ingestion-bigquery 에는 어떤 파일들이 들어있나요? 이거 한번 보여주시면 좋을거 같아요.

2022-03-14 06:51 UTC, socar-hardy commented on _posts/2022-03-07-metdata-platform-02.md
> +![metadata-ingestion-flow](/img/data-discovery-platform-02/metadata-ingestion-flow.png) *메타데이터 주입 흐름*
이거 위에 이게 사용한 Dockerfile 파일임을 알려주면 좋을거 같습니다.
ex. 작성한 Dockerfile 은 다음처럼 간단합니다.

2022-03-14 06:51 UTC, socar-hardy commented on _posts/2022-03-07-metdata-platform-02.md
> +스크린샷 (제이든 허락맡기)
여기에 데이터허브에 연동되어서 보이는 사진 있으면 될거 같네요.
테이블 , 컬럼 명은 블러처리해서 가리고 제이든에게 허락 받아보심이..

2022-03-14 07:04 UTC, socar-kyle commented
2편도 고생하셨습니다!!! 좋은 글 감사해요 디니! 제 의견을 공유드리면
- 1) 쉼표를 조금 정리해도 좋을 것 같아요. 예를 들어 첫번째로는, <- 여기서 쉼표는 필요 없을 것 같아요.  + GKE 환경에 배포한 과정과, 
- 2) 영어 단어는 항상 대문자로 시작해주세요(db -> DB, 기존 datahub 의 Helm Chart 는 sql host 로 mysql pod 을 가리키고 있습니다. 위에서 만든 cloudsql db -> 붙여쓰기와 대문자 사용하기)
- 3) 영어 단어 이후엔 띄어쓰기가 아닌 붙여주세요 (Datahub 를 -> Datahub를)
- 4) 목차는 이렇습니다 아래에 Datahub on GKE 배포 과정이 작성되어 있는데, "문제 정의" 부분을 추가하면 어떨까 싶어요. 현재 해야하는 문제와 그걸 위해 고려해야 하는 부분, 제약 조건 등을 한번 정의하고 그 밑에 글이 전개되면 더 좋을 것 같아요
- 5) 마무리에 Datahub를 도입하려는 분들에게 Tip을 더 작성해주면 좋을 것 같아요(새로운 Tip이 아닌 기존에 작성된 내용을 간단히 정리하기 정도? 위에 문제 정의를 잘 해두면 다시 말하면서 쓸 수 있을 것 같아요. 글 마지막에 읽으면서 아 이제 데이터허브 도입하려면 기존 1편 글을 읽고, 어떤 것을 고려하면 괜찮겠다! 이런 느낌으로 끝날 수 있도록!)

1~3번은 저번엔 제가 수정했는데 직접 해주시면 좋을 것 같아요

2022-03-15 08:28 UTC, socar-hardy requested changes
어렵지 않고 잘 읽히는 넘나 훌륭한 글이라고 느껴집니다! ㅎ_ㅎ
코멘트만 확인해주샤요!

2022-03-15 08:28 UTC, socar-hardy commented on _posts/2022-03-07-metdata-platform-02.md
> +secret yaml 파일은 다음과 같습니다. (helm secret 으로 정의하지 않고, kubectl secret 으로 정의하였습니다.)
```suggestion
secret yaml 파일은 다음과 같습니다.
```

굳이 빼도 될듯요? 게다가 helm secret 은 helm-secret 이라고 하는 별도의 플러그인이 있어서 이걸로 착각할거 같아요.

2022-03-15 08:28 UTC, socar-hardy commented on _posts/2022-03-07-metdata-platform-02.md
> +  selfLink: /api/v1/namespaces/datahub/secrets/mysql-secrets
```suggestion
```

이거 이미 생성된 secret을 kubectl describe 보면 나오는 정보 ㅋㅋㅋㅋ....
아래 type:Opaque 를 위로 올리고 data: 가 마지막으로 남도록 수정해보심이..

2022-03-15 08:28 UTC, socar-hardy commented on _posts/2022-03-07-metdata-platform-02.md
> +main.py 의 내용은 다음과 같습니다.
```suggestion
`main.py` 의 내용은 다음과 같습니다.
```

2022-03-15 08:28 UTC, socar-hardy commented on _posts/2022-03-07-metdata-platform-02.md
> +     			  f.write(json_result)
```suggestion
     	f.write(json_result)
```

2022-03-15 08:28 UTC, socar-hardy commented on _posts/2022-03-07-metdata-platform-02.md
> +        ORDER  BY schemaname,
```suggestion
        ORDER BY schemaname,
```

2022-03-15 08:41 UTC, socar-dini commented
해당 코멘트 모두 반영하였습니다!

2022-03-15 09:35 UTC, socar-dini commented
/맞춤법

2022-03-15 09:38 UTC, socar-dini commented on _posts/2022-03-15-metdata-platform-02.md
> +안녕하세요, 데이터 플랫폼 팀의 디니입니다.
이거 자꾸 왜이럼 ㅠ

2022-03-16 07:53 UTC, socar-hardy approved these changes
고생하셨습니다!

2022-03-16 08:06 UTC, socar-kyle approved these changes
디테일한 부분 마지막으로 체크했습니다!
일자도 3월 16일로 수정해주세요~~! 하디도 체크해주시고 배포 가시지요

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +이렇게 Datahub을 클라우드 상에 안정적으로 구축했습니다. 하지만 아직 데이터 디스커버리 플랫폼으로서의 기능을 하지는 못합니다. 데이터 소스에서 실제로 메타데이터를 가져와서 플랫폼에서 보여줘야 하고, 이렇게 메타데이터를 가져오는 과정(=metadata ingestion)이 자동화되어야 합니다.
```suggestion
이렇게 Datahub를 클라우드 상에 안정적으로 구축했습니다. 하지만 아직 데이터 디스커버리 플랫폼으로서의 기능을 하지는 못합니다. 데이터 소스에서 실제로 메타데이터를 가져와서 플랫폼에서 보여줘야 하고, 이렇게 메타데이터를 가져오는 과정(=metadata ingestion)이 자동화되어야 합니다. 
```

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +쏘카에서는 주요 데이터 소스로 MySQL Aurora(운영)와 BigQuery(분석)을 사용하고 있습니다. 하지만 이 데이터 소스의 모든 테이블을 가져올 필요는 없었습니다. 예를 들면 DB에 따라서 개인 정보 관련 민감한 데이터들도 있고, 분석 DB 쪽에는 굳이 전사에 공유될 필요는 없는 임시 테이블들도 다수 존재했습니다. 따라서 각 데이터 소스 별 DB
```suggestion
쏘카에서는 주요 데이터 소스로 MySQL Aurora(운영)와 BigQuery(분석)를 사용하고 있습니다. 하지만 이 데이터 소스의 모든 테이블을 가져올 필요는 없었습니다. 예를 들면 DB에 따라서 개인 정보 관련 민감한 데이터들도 있고, 분석 DB 쪽에는 굳이 전사에 공유될 필요는 없는 임시 테이블들도 다수 존재했습니다. 따라서 각 데이터 소스 별 DB의 목록을 사전에 정하고, 해당 DB의 메타데이터를 주입하기로 했습니다.
```

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +참고로, 다음과 같이 Table 혹은 DB의 이름을 `regex pattern`으로 감지하여 선택적 메타데이터 주입이 가능합니다. (물론 데이터 소스마다 방법이 약간 다를 수 있습니다 - 예시는 BigQuery의 경우입니다.)
```suggestion
참고로, 다음과 같이 Table 혹은 DB의 이름을 `regex pattern`으로 감지하여 선택적 메타데이터 주입이 가능합니다. (물론 데이터 소스마다 방법이 약간 다를 수 있습니다 - 예시는 BigQuery입니다)
```

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +하루에 한 번 Batch 성 주입이라면 `Airflow DAG`로 간단하게 구현할 수 있었습니다. 데이터 소스에서 메타데이터를 주입하는 Task를 만들고, 하루 한 번만 돌려주면 됐습니다. 그런데 이 작업에는 `datahub` 패키지를 설치해야 하는 의존성이 필요합니다.
```suggestion
하루에 한 번 Batch 단위의 주입이라면 `Airflow DAG`로 간단하게 구현할 수 있었습니다. 데이터 소스에서 메타데이터를 주입하는 Task를 만들고, 하루 한 번만 돌려주면 됐습니다. 그런데 이 작업에는 `datahub` 패키지를 설치해야 하는 의존성이 필요합니다. 
```

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +당시 데이터 엔지니어링 팀 팀장 (이시고 지금은 그룹장이신) 토마스가 아이디어를 주셨습니다.
```suggestion
당시 데이터 엔지니어링 팀 팀장(이시고 지금은 그룹장이신) 토마스가 아이디어를 주셨습니다.
```

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +# datahub을 포함한 필요한 의존성을 설치합니다.
```suggestion
# datahub를 포함한 필요한 의존성을 설치합니다. 
```

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +information_schema에서는 Table 정보, Column 정보, Constraint (Primary Key 등) 정보 등 여러 가지 정보를 추출해오는데요. 예를 들어 Column 정보는 다음과 같은 쿼리로 추출합니다. 이렇게 실행한 쿼리 결과를 Datahub에서 이용하는 json 형식에 맞게 바꿔줍니다.
```suggestion
information_schema에서는 Table 정보, Column 정보, Constraint (Primary Key 등) 정보 등 여러 가지 정보를 추출합니다. 예를 들어 Column 정보는 다음과 같은 쿼리로 추출합니다. 이렇게 실행한 쿼리 결과를 Datahub에서 이용하는 json 형식에 맞게 바꿔줍니다.
```

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +이렇게 기능을 구현한 뒤 프로젝트에 같이 참여하시고 계시는 인프라팀(현재 CloudDB 팀)의 제이든과 직접 테스트를 해보았습니다. 마지막으로 MySQL 계정 권한에 변경이 필요했습니다.
```suggestion
이렇게 기능을 구현한 뒤 프로젝트에 같이 참여하시고 계시는 DBA 제이든과 직접 테스트를 해보았습니다. 마지막으로 MySQL 계정 권한에 변경이 필요했습니다. 
```

팀명은 구체적으로 언급하지 않아도 무방합니다!

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +이러한 여러 과정 끝에, Datahub가 쏘카에 도입될 준비를 마쳤습니다. 현재는 이렇게 테스트 배포를 마치고 사내 공개를 위한 준비 작업을 하고 있습니다. 이 자리를 빌려 Datahub 도입에 힘써주신 모든 분들과 부족한 저를 도와주신 분들에게 감사드립니다.
```suggestion
이러한 여러 과정 끝에, Datahub가 쏘카에 도입될 준비를 마쳤습니다. 현재는 이렇게 테스트 배포를 마치고 사내 공개를 위한 준비 작업을 하고 있습니다. 이 자리를 빌려 Datahub 도입에 힘써주신 저를 도와주신 모든 분들에게 감사드립니다. 
```

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +마지막으로 Datahub을 도입하려는 분들에게 팁을 드리자면 다음과 같습니다.
```suggestion
마지막으로 Datahub를 도입하려는 분들에게 팁을 드리자면 다음과 같습니다.
```

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +* 하루 한 번 정도의 Batch 성 작업이라면 `Airflow DAG` 로도 충분합니다.
```suggestion
* 하루 한 번 정도의 Batch 작업이라면 `Airflow DAG`로도 충분합니다.
```

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +* 최근에는 Datahub UI 상에서 Ingestion 을 설정할 수 있는 기능도 나왔습니다. 장단점을 비교해 보고 결정하시면 좋을 것 같습니다.
```suggestion
* 최근에는 Datahub UI 상에서 Ingestion을 설정할 수 있는 기능도 나왔습니다. 장단점을 비교해 보고 결정하시면 좋을 것 같습니다.
```

2022-03-16 08:06 UTC, socar-kyle commented on _posts/2022-03-15-metdata-platform-02.md
> +* 권한에 민감한 DB라면, information_schema에서 바로 메타데이터를 뽑는 로직을 구현하는 방법이 있습니다.
```suggestion
* 권한에 민감한 DB라면 information_schema에서 바로 메타데이터를 뽑는 로직을 구현하는 방법이 있습니다.
```

2022-03-16 08:27 UTC, merged