post: React Icon Component 개발기 초안 (시에나, 블랑)
socar-inc/socar-inc.github.io pull request #148
Opened 2022-07-14 07:25 UTC by socar-blanc

React Icon Component 개발기 초안입니다.

2022-07-15 07:02 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +쏘카의 디자인 시스템은 디자이너, Ios 개발자 Android 개발자, 웹프론트엔드 개발자가 협업하여 구축했습니다. 사용자가 일관된 UI/UX를 경험할 수 있도록 Ios, Android, 웹에서 모두 같은 형태의 컴포넌트들을 개발하여 사용합니다. 이번 글에서 다룰 아이콘 또한 디자인시스템에 포함되어있습니다.
디자인 시스템의 구축 방식 부터 설명하고 있는데, 디자인 시스템의 정의가 한문장 정도로 추가되면 좋을것 같습니다.

2022-07-15 07:02 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +svg를 이루는 기본적인 도형들 중에 path element는 여러 개의 직선과 곡선을 합쳐서 **복잡한 도형을 그릴 수 있다는 큰 장점**을 갖고 있습니다. 다양한 element들을 path element 하나로 나타낼 수 있다는 뜻 입니다.
- svg와 svg 를 이루는 도형들에 대해 간단한 설명이 있으면 좋겠습니다.
- path element 를 선택한 이유 (아이콘을 다루는 일반적인 방법 )와 레퍼런스를 달아주면 좋을 것 같아요. (cf. 깃험) 
- path element / circle element 말고 무엇이 있는지?
- Path element 의 장점이 바로 나오는데, 정의를 먼저 설정해주고 장점이 나왔으면 좋겠습니다.

2022-07-15 07:02 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +```
- path element vs circle element 를 시각화로 만들어서 추가하기 (각 숫자가 어떤 것을 나타내는지)

2022-07-18 04:31 UTC, socar-kyle reviewed
전반적으로 글 흐름이나 문구가 끊김없이 잘 읽히는 글이네요..!

디니가 써주신 부분만 조금 더 보강해서 친절함을 한스푼 더 얹으면 더 좋은 글이 될 것 같네요

- 영어 단어 통일(리액트, React)
- 영어 단어는 대문자로 시작
- json 같은 단어는 JSON, css는 CSS로 해주셔도 좋을 것 같네요
- 디자인시스템 => 디자인 시스템 : 이 부분은 디니가 띄어쓰기 검사 돌려주시면 될 것 같네요
- convertSvgPath.js 스크립트 자체를 공개할 생각은 없으시겠죠? 스크립트를 돌린다고 하는데 코드가 없어서, 이것을 추가하면 더 많은 분들이 도움받지 않을까 싶네요
- 3, 4 파트는 더 보강하면 좋을 것 같아요! 마무리 부분만..!
고생하셨습니다 :)

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +title: "React Icon Component 개발기"
구글 검색어를 한번 보니
React Custom Icon Component 개발기
Reat Icon Component 만들기

이 두개 정도가 어떨까 싶네요

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +subtitle: "React Icon Component 개발기"
이 부분은 제목과 다르게 가져가도 좋겠네요!

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +background: "/img/reservation-tetris/background.jpg"
마지막에 백그라운드 배경 수정하시지요~

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +이 글에 다룰 내용은 쏘카에서 공통적으로 사용하는 **웹 아이콘 컴포넌트 개발 과정**입니다. 아이콘 컴포넌트를 어떻게 개발했으며 어떤 점들을 개선했는지에 대해서 중점적으로 다룰 예정입니다.
```suggestion
이 글에 다룰 내용은 쏘카에서 공통적으로 사용하는 **React Web Icon Component 개발 과정**입니다. 아이콘 컴포넌트를 어떻게 개발했으며 어떤 점들을 개선했는지에 대해서 중점적으로 다룰 예정입니다.
```

검색의 다양성을 위해 영어로 키워드 넣어보아요.

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +- 쏘카 웹프론트엔드 팀이 궁금하신 분
```suggestion
- 쏘카 웹 프론트엔드 팀이 궁금하신 분
```

회사에선 웹 프론트엔드라는 이름을 붙이는데, 보는 분들이 여기서 띄어쓰기가 없으면 음?할 수 있어서 맞춰보았어요

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +  - [2.1 다양한 element 도형을 path element로 변경해보자](#2.1-다양한-element-도형을-path-element로-변경해보자)
```suggestion
  - [2.1 다양한 Element 도형을 Path Element로 변경해보자](#2.1-다양한-element-도형을-path-element로-변경해보자)
```

영어는 대문자로 시작해주시지요!

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +쏘카의 디자인 시스템은 디자이너, Ios 개발자 Android 개발자, 웹프론트엔드 개발자가 협업하여 구축했습니다. 사용자가 일관된 UI/UX를 경험할 수 있도록 Ios, Android, 웹에서 모두 같은 형태의 컴포넌트들을 개발하여 사용합니다. 이번 글에서 다룰 아이콘 또한 디자인시스템에 포함되어있습니다.
```suggestion
쏘카의 디자인 시스템은 디자이너, IOS 개발자 Android 개발자, 웹프론트엔드 개발자가 협업하여 구축했습니다. 사용자가 일관된 UI/UX를 경험할 수 있도록 Ios, Android, 웹에서 모두 같은 형태의 컴포넌트들을 개발하여 사용합니다. 이번 글에서 다룰 아이콘 또한 디자인 시스템에 포함되어있습니다.

디자인 시스템에 궁금하신 분은 프로덕트디자인팀의 글인 [[SOCAR FRAME 만들기 #1] 쏘카의 디자인 시스템 맛보기](https://tech.socarcorp.kr/design/2020/06/23/socar-design-system-01.html) 시리즈 글을 모두 보시는 것을 추천합니다.
```

디자인 시스템으로 수정했고, 프디팀 글을 추가했습니다

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +쏘카의 디자인 시스템은 디자이너, Ios 개발자 Android 개발자, 웹프론트엔드 개발자가 협업하여 구축했습니다. 사용자가 일관된 UI/UX를 경험할 수 있도록 Ios, Android, 웹에서 모두 같은 형태의 컴포넌트들을 개발하여 사용합니다. 이번 글에서 다룰 아이콘 또한 디자인시스템에 포함되어있습니다.
@socar-dini 이건 프디팀 글이 있으니 추가하면 다 해소될 것 같아요-! (프디팀 글도 레퍼런스로 삼아서 Chaining 효과 가져갈 수 있음)

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +쏘카에서 기존에 사용하던 방식은 아이콘을 웹폰트로 변환하여 사용하는 방식입니다. 해당 방식으로도 아이콘을 등록하고 사용하는 데에는 큰 무리가 없지만, 디자인시스템은 여러 개발자가 공동으로 사용하기 때문에 개발자 경험(Developer Experience, DX) 또한 중요합니다. 기존의 방식에는 개발자 경험에 문제가 있었기 때문에 아이콘 방식 개선에 대한
```suggestion
쏘카에서 기존에 사용하던 방식은 아이콘을 웹폰트로 변환하여 사용하는 방식입니다. 해당 방식으로도 아이콘을 등록하고 사용하는 데에는 큰 무리가 없지만, 디자인 시스템은 여러 개발자가 공동으로 사용하기 때문에 개발자 경험(Developer Experience, DX) 또한 중요합니다. 기존의 방식에는 개발자 경험에 문제가 있었기 때문에 아이콘 방식 개선에 대한 필요성을 느끼게 되었습니다.
```

오 DX라는 개념 처음 듣는데 인상 깊네요!! 👍

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +_참고: [[SOCAR FRAME 만들기 #1] 쏘카의 디자인 시스템 맛보기](/design/2020/06/23/socar-design-system-01.html)_
아항 여기 링크가 있었군요..! 디자인 시스템 관련 내용은 아예 디자인 시스템 내용 처음 나올 때로 옮기시지요
```suggestion
```

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +기존에는 쏘카에서 아이콘을 폰트로 변환하여 사용하고 있었습니다. 기존의 방식을 먼저 설명드린 후에 어떤 문제점이 있었는지에 대해 말씀드리겠습니다.
```suggestion
기존엔 아이콘을 폰트로 변환하여 사용하고 있었습니다. 기존의 방식을 먼저 설명드린 후에 어떤 문제점이 있었는지에 대해 말씀드리겠습니다.
```

쏘카 블로그 이야기라 쏘카에서라는 말이 없어도 될 것 같네요!

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +   > 외부 서비스를 이용해서 아이콘 svg 파일들을 웹폰트로 변환합니다.
이 서비스는 무엇인지도 궁금해할 수 있겠네요! 간단히 URL 넣어도 괜찮을 것 같아요

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +   > 웹폰트로 변환하면 폰트 파일과 css 파일이 생성됩니다.
```suggestion
   > 웹폰트로 변환하면 폰트 파일과 CSS 파일이 생성됩니다.
```

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +   > 생성된 파일들을 디자인 시스템 저장소에 넣어줍니다. 이 때, 아이콘 폰트에 원하는 컬러를 주입할 수 있도록 하기 위해 css의 color 속성을 제거해줍니다.
```suggestion
   > 생성된 파일들을 디자인 시스템 저장소에 넣어줍니다. 이 때, 아이콘 폰트에 원하는 컬러를 주입할 수 있도록 하기 위해 CSS의 color 속성을 제거해줍니다.
```

디자인시스템 => 디자인 시스템 전반적으로 수정해야겠네용~

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +2. 휴먼에러가 발생할 여지가 많다.
```suggestion
2. 휴먼 에러가 발생할 여지가 많다.
```

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +- 아이콘 등록 방식의 자동화
```suggestion
- **아이콘 등록 과정의 간소화**
- **아이콘 등록 방식의 자동화**
```

핵심인 것 같아 Bold하면 어떨까요?

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +### 2.1 다양한 element 도형을 path element로 변경해보자 <a name="2.1-다양한-element-도형을-path-element로-변경해보자" />
```suggestion
### 2.1 다양한 Element 도형을 Path Element로 변경해보자 <a name="2.1-다양한-element-도형을-path-element로-변경해보자" />
```

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +
여기에 그린 원 아이콘 하나 추가하면 어떨까요?

저는 글을 읽다가 생각해야하는 내용이 많아지더라구요. 이 화면에 여백이 적어서 더 복잡해져서, 글 보는 분에게 여유를 줄 겸 그린 circle 아이콘을 공유해도 좋을 것 같아요

영어 단어는 첫 시작 거의 다 대문자로 수정해주세요~

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +이 때 생각한 것이 아이콘 이름을 타입으로 지정하면 IDE의 도움을 받을 수 있을 것이라 예상했습니다.
이렇게 입력해주시면 엔터 처리가 안되는데, 인지하고 계시지요? (다 한줄로 표시됨)

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +스크립트 실행을 자동화함으로서 아이콘 등록 전 과정을 자동화할 수 있었고, 수동으로 작성했을 때 발생하는 휴먼 에러를 방지할 수 있다는 점에서 의미있는 작업이었습니다. 또한 외부 서비스를 이용하지 않고 코드 한 줄로 직접 빌드가 가능했고, svg 파일을 사용하게 되어 아이콘 화질 저하 문제, 오래 걸리는 빌드 시간, css 불편함 등이 해결되어 사용성이
여기에 이런 내용이 추가되면 좋을 것 같아요

- 기존엔 웹프론트엔드 팀 한명이 약 N시간을 사용해야 했던 시간이 M분까지 줄었다!(효율을 수치화)

문제점이 해결되었는가?랑 추후 개선점 내용이 갑자기 적어지는 느낌이라 보강하면 좋을 것 같네요

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +## 4. 추후 개선점 <a name="4.-추후-개선점" />
추후 개선점은 아직 완성되지 않은 것이라 보면 되겠지요..? (제가 리뷰를 드릴 수 있는 날이 마지막이라..)

여기서는 개선점을 "하다보니 또 어떤 문제가 생겼는지, 그 문제는 어떤 관점으로 중요한지, 왜 해결해야 하는지" + 어떤 방식으로 고려하고 있는지 위주로 작성해주시면 될 것 같네요!

2022-07-18 04:31 UTC, socar-kyle commented on _posts/2022-07-06-react-icon-component.md
> +쏘카 웹 프론트엔드 팀에서 리액트 아이콘 컴포넌트를 개발한 과정에 대해 알아보았습니다. 외부 서비스는 사용자 경험을 중요시하는 것처럼, 회사 내 개발자들이 사용하는 서비스는 개발자 경험이 중요합니다.
리액트, React 단어를 통일하면 좋은데 검색어 자체에 영어가 많이 나와서 React로 하면 좋을 것 같습니다!

2022-07-18 04:34 UTC, socar-kj commented on _posts/2022-07-06-react-icon-component.md
> +쏘카의 디자인 시스템은 디자이너, Ios 개발자 Android 개발자, 웹프론트엔드 개발자가 협업하여 구축했습니다. 사용자가 일관된 UI/UX를 경험할 수 있도록 Ios, Android, 웹에서 모두 같은 형태의 컴포넌트들을 개발하여 사용합니다. 이번 글에서 다룰 아이콘 또한 디자인시스템에 포함되어있습니다.
Ios > iOS 로 전반적으로 모두 맞춤법 수정해주셨으면 합니다 :)

2022-08-08 08:42 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +- [0. React Icon Component란?](#0.-react-icon-component란?)
목차는 1번부터 시작하는 것이 좋을 것 같습니다 :)

2022-08-08 09:21 UTC, socar-dini requested changes

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +`Object.key()`를 활용해 아이콘 이름을 가져오는 스트립트를 작성하였고, 실행시키면 아래와 같은 파일이 만들어집니다.
```suggestion
`Object.key()`를 활용해 아이콘 이름을 가져오는 스크립트를 작성하였고, 실행시키면 아래와 같은 파일이 만들어집니다. 
```

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +- [3. 아이콘 등록은 어떻게 하는걸까?](#3-아이콘-등록은-어떻게-하는걸까?)
최상위 목차를 전체적으로 단어로 끝나도록 수정하면 좋을 것 같습니다. 
차상위 목차가 문장 형태여서, 최상위 목차가 질문형으로 끝나는 것보다는 단어로 끝내는게 좀더 깔끔해 보일 것 같아요. 
목차에서 쓰이는 단어의 영/한문 및 표현도 통일하면 좋을 것 같네요1 ( 아이콘 -> Icon Component)

예시) 
- React Icon Component 개발의 필요성
- Icon Component 개발 과정
- Icon Component 등록 방법
- 문제 해결 효과
- 개선할 점
- 마무리

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +디자인 시스템이란, 재사용 가능한 UI 요소들을 미리 정의하여 일관된 디자인을 할 수 있도록 도와주는 규칙을 말합니다.
```suggestion
디자인 시스템이란, 재사용 가능한 UI 요소들을 미리 정의하여 일관된 디자인을 할 수 있도록 도와주는 규칙을 말합니다. 쏘카의 디자인 시스템에 대한 자세한 내용은 프로덕트 디자인 팀이 작성해주신 _[<U>쏘카의 디자인 시스템 맛보기</U>](/design/2020/06/23/socar-design-system-01.html)_ 를 참고해주세요. 
```

다른 글에 대한 링크를 유도할때 좀더 서술형으로 작성해 주는 것도 좋아보입니다!

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +우선 기존의 방식을 먼저 설명드린 후에 어떤 문제점이 있었는지에 대해 말씀드리겠습니다.
```suggestion
구체적으로 기존의 방식에 어떤 문제점이 있었는지 말씀드리겠습니다.
```
이 문장을 이렇게 수정하고, 위의 문단과 붙이는 것이 좀더 매끄러울 것 같은데 어떠신가요? 
`기존의 방식은 개발자 경험 측면에서 불편한 점이 있어` 라는 문장을 읽었을 때, 즉각적으로 "어떤 게 불편했던 거지? 설명은 어디있지?" 라는 생각이 들수 있을 것 같아요. 여기서 한 호흡 떼고 다음 내용을 들어가는 것보다, 같은 문단에서 바로 설명해주겠다! 라고 연결하는 것이 자연스러워 보입니다.

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +3. 아이콘 폰트 자체의 문제점
```suggestion
3. 아이콘 폰트 이용 시 불편한 점이 많다.
```

1,2번은 문장 형식인데 요게 단어로 끝나고 있어서 이것도 수정하는게 깔끔할 것 같습니다!

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +위와 같은 문제점들을 겪으면서 디자인 시스템에 아이콘을 등록하는 방식 자체를 개선해야겠다고 생각했습니다. 개선의 목표는
```suggestion
위와 같은 문제점들을 겪으면서 디자인 시스템에 아이콘을 등록하는 방식 자체를 개선해야겠다고 생각했습니다. 개선의 목표는 다음과 같았습니다.
```

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +정도로 생각하고, 위의 목표를 달성하면서도 기존에 사용중인 아이콘들에 영향을 미치지 않는 방식으로 개선을 시도했습니다.
```suggestion
위의 목표를 달성하면서도 기존에 사용중인 아이콘들에 영향을 미치지 않는 방식으로 개선을 시도했습니다.
```

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +쏘카의 아이콘은 쏘카 앱 내 곳곳에서 찾아볼 수 있고, [쏘카 플랜](https://plan.socar.kr/)에서도 사용되고 있습니다.
```suggestion
쏘카의 아이콘은 쏘카 앱 내 곳곳에서 찾아볼 수 있고 [쏘카 플랜](https://plan.socar.kr/)에서도 사용되고 있습니다.
```

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +   > 생성된 파일들을 디자인 시스템 저장소에 넣어줍니다. 이 때, 아이콘 폰트에 원하는 컬러를 주입할 수 있도록 하기 위해 CSS의 color 속성을 제거해줍니다.
```suggestion
   > 생성된 파일들을 디자인 시스템 저장소에 넣어줍니다. 이때 아이콘 폰트에 원하는 컬러를 주입할 수 있도록 하기 위해 CSS의 color 속성을 제거해줍니다.
```

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +   - 아이콘 폰트 등록이 완료되었으면, 디자인 시스템의 배포를 진행합니다. 디자인 시스템을 사용중인 모든 서비스들도 디자인 시스템 버전을 최신화해서 같이 배포를 진행합니다.
```suggestion
   - 아이콘 폰트 등록이 완료되었으면 디자인 시스템의 배포를 진행합니다. 디자인 시스템을 사용중인 모든 서비스들도 디자인 시스템 버전을 최신화해서 같이 배포를 진행합니다.
```

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +벡터 그래픽은 크기를 크게 조절하더라도 이미지 품질이 저하되지 않고, 용량도 래스터 그래픽보다 작다는 장점을 갖습니다. 이에 더하여 애니메이션이 가능하고, 수정이 용이하며, 출력이 빠르기 때문에 **아이콘 파일 포맷**으로 사용되고 있습니다.
```suggestion
벡터 그래픽은 크기를 크게 조절하더라도 이미지 품질이 저하되지 않고 용량도 래스터 그래픽보다 작다는 장점을 갖습니다. 이에 더하여 애니메이션이 가능하고, 수정이 용이하며, 출력이 빠르기 때문에 **아이콘 파일 포맷**으로 사용되고 있습니다.
```

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +아이콘 갯수와 색상이 수백개인데 사용할 때마다 일일이 적는 것이 번거로웠고, 이것을 해결해야만 했습니다.
```suggestion
아이콘 갯수와 색상이 수백개인데 사용할 때마다 일일이 적는 것이 번거로웠습니다.
```

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +![image](/img/icon-component/storybookTest.png)
요 이미지가 웹에서 깨지는 것 같습니다 이미지는 StroybookTest.png 로 저장되어 있네요 (대소문자)

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +  - 아이콘을 등록하는 방식 중 대부분을 자동화하는데 성공했지만, SVG 파일을 디렉토리에 넣는 과정은 여전히 수기로 진행해야 합니다.
```suggestion
  - 아이콘을 등록하는 방식 중 대부분을 자동화하는데 성공했지만 SVG 파일을 디렉토리에 넣는 과정은 여전히 수기로 진행해야 합니다.
```

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +  - 디자이너분들이 아이콘 파일을 Figma를 통해 전달해주시기 때문에 Figma와 연동, 혹은 다른 방법을 통해 모든 과정을 자동화할 예정입니다.
```suggestion
  - 디자이너분들이 아이콘 파일을 Figma를 통해 전달해주시기 때문에, Figma와 연동 혹은 다른 방법을 통해 모든 과정을 자동화할 예정입니다.
```

2022-08-08 09:21 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +쏘카 웹 프론트엔드 팀에서 React Icon Component를 개발한 과정에 대해 알아보았습니다. 외부 서비스는 사용자 경험을 중요시하는 것처럼, 회사 내 개발자들이 사용하는 서비스는 개발자 경험이 중요합니다.
```suggestion
쏘카 웹 프론트엔드 팀에서 React Icon Component를 개발한 과정에 대해 알아보았습니다. 외부 서비스는 사용자 경험을 중요시하는 것처럼 회사 내 개발자들이 사용하는 서비스는 개발자 경험이 중요합니다.
```

2022-08-08 09:25 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +  <img src="/img/icon-component/iconNameJson.png" width="600">
요 스크립트가 밑에서 한번 더 링크되고 있는데, 코드로 임베딩 해주는 게 어떠신가요? 
(요거를 참고하고 싶은 사람들이 있을 것 같아요 ㅎㅎ)

2022-08-11 01:57 UTC, socar-blanc commented on _posts/2022-07-06-react-icon-component.md
> +SVG를 이루는 기본적인 도형의 종류로는 Path, Rect, Circle, Ellipse, Line, Polyline, Polygon Element가 있습니다.
@socar-sienna 숫자 하나씩 뒤로 미뤄서 3.2 아래로 봐주시면 될거 같아요~

2022-08-11 02:00 UTC, socar-blanc commented on _posts/2022-07-06-react-icon-component.md
> +- [3. 아이콘 등록은 어떻게 하는걸까?](#3-아이콘-등록은-어떻게-하는걸까?)
@socar-sienna 3, 4, 5 최상위 목차 제목만 변경 부탁드려요~

2022-08-11 02:08 UTC, socar-blanc commented on _posts/2022-07-06-react-icon-component.md
> +여기서 발생하는 휴먼 에러도 많고, 리소스도 많이 드는 작업이었습니다.
@socar-sienna `이 과정에서 휴먼 에러도 발생하고 리소스도 많이 필요했습니다.` 이런 느낌으로 써주면 조금 더 자연스럽게 읽힐 것 같습니다

2022-08-23 03:09 UTC, socar-sienna commented
@socar-dini 안녕하세요 디니! 마지막으로 리뷰 주신 것까지 반영했습니다! 최종 확인 부탁드려도 될까요~? 🙏

2022-08-31 01:01 UTC, socar-dini commented
/맞춤법

2022-08-31 01:12 UTC, socar-dini commented
마지막 체크 
[] 맞춤법 / 쉼표 / 문장 수정
[] 배포일에 맞춰 본문/파일 날짜 수정
[] 본문/부제 확정

2022-08-31 01:16 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +디자인 시스템이란, 재사용 가능한 UI 요소들을 미리 정의하여 일관된 디자인을 할 수 있도록 도와주는 규칙을 말합니다.
```suggestion
디자인 시스템이란 재사용 가능한 UI 요소들을 미리 정의하여 일관된 디자인을 할 수 있도록 도와주는 규칙을 말합니다.
```

2022-08-31 01:17 UTC, socar-dini commented on _posts/2022-07-06-react-icon-component.md
> +벡터 그래픽이란 수학적 표현을 통해 점, 직선, 곡선을 사용하여 이미지를 만드는 그래픽을 말합니다. 흔히 알고 있는 또 다른 그래픽 파일 포맷으로는 래스터 그래픽, 즉 비트맵으로 PNG, JPEG가 있는데요, 이것은 픽셀로 구성된 이미지로 작은 컬러 사각형인 픽셀이 무수히 많이 모여 만들어지는 그래픽입니다.
```suggestion
벡터 그래픽이란 수학적 표현을 통해 점, 직선, 곡선을 사용하여 이미지를 만드는 그래픽을 말합니다. 흔히 알고 있는 또 다른 그래픽 파일 포맷으로는 래스터 그래픽, 즉 비트맵으로 PNG, JPEG가 있습니다. 이것은 픽셀로 구성된 이미지로 작은 컬러 사각형인 픽셀이 무수히 많이 모여 만들어지는 그래픽입니다.
```

2022-09-06 02:36 UTC, socar-dini approved these changes

2022-09-06 04:53 UTC, merged