post: iOS 웹 뷰 세션쿠키 소실되는 이유
socar-inc/socar-inc.github.io pull request #199
Opened 2024-07-17 01:48 UTC by socar-rio

# 개요
> web에서 해당 포스트를 확인할 수 있는 url 을 남겨주세요.
[socar-rio.github.io](https://socar-rio.github.io/dev/2024/07/13/ios-webView-cookie.html)

# PR 리뷰 전 Checklist

> PR 시, 아래 부분을 확인해주세요! 

- [x] PR 제목을 `post: <글_제목>` 으로 해주셨나요? 
- [x] 파일명과 metadata의 date가 현재 시점 전으로 설정 되었나요? (현재 시점 이후라면 웹에서 확인이 되지 않습니다)
- [x] fork 한 repository의 url 로 확인이 가능한가요?  
- [x] 웹에서 이미지가 깨지지 않고 확인이 잘 되나요? (만약 깨진다면 경로를 다시 확인해주세요!)
- [] 목차가 컨벤션을 맞춰서 잘 설정되어 있나요? (1, 1.1, 1.1.1 ...)
(짧은 글이라 목차는 생략했습니다! 혹시 정의가 되어야한다면 말씀해주세요~!)   

# 배포 전 Checklist

> 아래 부분이 모두 체크 되면 배포 준비가 완료됩니다!

- [ ] 파일명과 metadata의 date가 배포 날짜로 설정되어 있는지 확인
- [x] 보안 관련 내용 최종 확인
- [x] 웹상에서 이미지 크기 및 화질, 저작권 확인
- [ ] 목차 컨벤션 확인 
- [x] 맞춤법/비문 확인
- [x] 제목/부제 최종 확정
- [x] Background image 확정 및 저작권 확인

# TO DO 
> 머지하기 전 추가로 의논해야 될 점이 있다면 남겨주세요.

2024-07-17 08:21 UTC, socar-kj requested changes
초벌로 봤습니다. 제 의견이 정답은 아니니 참고해주세요. 고생하셨습니다.

2024-07-17 08:21 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +- **iOS 기기에서만 발생(안드로이는 발생하지 않음)**
문제 원인 단락 다음에 iOS 기기에서만 발생이 나오는게 앞뒤가 안 맞는 것 같습니다.

문제 원인 자체를 맨 윗줄에 적는게 나아보입니다.

2024-07-17 08:21 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +> - iOS 메모리 정리 시점은 공개된 바가 없어서 정확히는 모르지만, 테스트 결과 앱을 여러 개 실행시켜 메모리를 많이 사용하는 경우 발생합니다.
옛날 iOS 개발자로서.. 👴 
아이폰 메모리가 부족할 때 메모리 정리를 한다는 건 애플 공식 문서에도 나와있습니다, 
https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle/responding_to_memory_warnings
시뮬레이터에서 메모리 부족 테스트를 할 수도 있구요.

앱 메모리 정리 시점에 백그라운드 웹 세션 쿠키가 사라진다는 결론만 적는게 어떨까 싶습니다.

2024-07-17 08:21 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +영상을 보시면 알 수 있듯이, 포그라운드로 돌아왔을 때 잠시 새로고침되는 UI를 확인할 수 있습니다. 이후 해당 페이지가 렌더링 되고 서버 요청 시 정상적으로 동작하는 것을 확인할 수 있습니다. 즉 쿠키가 유지되어 있음을 확인할 수 있습니다.
영상을 보시면 알 수 있듯이 포어그라운드로 돌아왔을 때 UI가 잠시 새로고침 됩니다. 이후 해당 페이지가 렌더링 되고 서버 요청 시 정상적으로 동작합니다. 즉 유실되던 쿠키가 잘 유지됨을 확인할 수 있습니다.

ㄴ제안입니다.

2024-07-17 08:21 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +<p style='text-align: center; color: #646f7c;'>포그라운드 -> 웹 뷰 리프레시 -> 쿠기 유지 -> 서버 호출 시 정상적으로 동작</p>
쿠기 > 쿠키

2024-07-17 08:21 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +**`iOS앱이 메모리 정리되는 시점에 백그라운드에서 있는 웹의 세션쿠키를 손실 시킨다. 이를 유지하기 위해서는 지속쿠키로 이용할 수 있게 기간을 정의해준다.`**
iOS 앱은 백그라운드에서 메모리가 정리될 때 웹의 세션 쿠키가 손실된다.
이를 막기 위해서는 지속 쿠키로 이용되도록 기간을 정의해주면 된다.

제안입니다.

2024-07-17 08:21 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +해결 방법은 간단했지만 원인을 분석하고 가설을 도출한 후 테스트 진행하는 과정에서 많은 시간이 소요되었습니다. 그러나 이 과정을 통해 문제의 근본적인 원인을 찾아내고 해결함으로써 개발자로서 한 층 더 성장할 수 있었습니다. 또한, iOS 공식 문서에 해당 이슈에 대한 해결 방법을 제안해 보는 귀중한 경험도 가질 수 있었습니다. (\*위에 첨부한 버그 리포
한 층 > 한층
또한, > 또한
제안해 보는 > 제안하는
가질 수 있었습니다 > 해볼 수 있었습니다

(\*위에 첨부한 버그 리포트 참고) > 뭘 참고해야할지 모르겠습니다

2024-07-17 08:21 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +title: "iOS 웹 뷰 세션쿠키 소실되는 이유"
iOS 웹뷰의 세션쿠키가 사라지는 이유
왜 iOS 웹뷰의 세션쿠키가 사라졌을까
도 제목으로 제안드려봅니다. 고생하셨습니다. 참고만 하십시요~

2024-07-17 08:21 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +> 해당 이슈는 오래전부터 존재했지만 비중이 낮아 주목받지 못했습니다. 이 문제를 발견하고 이슈화해주신 팀장님과 내부 제보자들, 문제 해결에 도움을 주신 동료들, 네이티브 개발자분들께 감사드립니다.
두 문단으로 나누지 않고 하나로 이렇게 쓰는건 어떨지 제안해봅니다.

쏘카의 모든 웹 서비스에 영향을 미칠만큼 파급 효과가 컸습니다. 안정적인 서비스에 기여할 수 있어서 뿌듯했습니다.
오래 전부터 있었음에도 주목받지 못했던 이슈인데 많은 분들이 도와주셨습니다.
팀장님과 내부 제보자들, 동료분들 특히 네이티브 앱 개발자분들께 감사드립니다.

2024-07-19 06:52 UTC, socar-abel approved these changes

2024-07-22 02:39 UTC, socar-rio commented on _posts/2024-07-16-ios-webView-cookie.md
> +<p style='text-align: center; color: #646f7c;'> 웹 뷰 백그라운드 → 특정 시간 후 포그라운드 → 웹 뷰 리프레시 → 서버 호출 시 에러</p>
포편적으로 사용하는 말이어서 직관적이게 요 부분은 한글로 표기하겠습니다! 의견 감사합니다!

2024-07-22 02:58 UTC, socar-raphael commented on _posts/2024-07-16-ios-webView-cookie.md
> +여느 때처럼 쏘카 서비스를 개발하고 있었는데, 팀장님이 저희가 개발했던 서비스에서 에러가 발생한다고 말씀해 주셨습니다.
@socar-rio 저희가 팀장이라는 직책은 공식적으로 없지요. TL이라는 표현을 쓰는게 맞지않을까...싶습니다 ^^

2024-07-22 02:59 UTC, socar-kj requested changes

2024-07-22 02:59 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +어떤 상황에서 발생했는지 여쭤보니, 쏘카 앱 내의 웹뷰 서비스를 이용한 후, 앱을 백그라운드 상태에 두고 한참 후에 다시 열었을 때 에러가 발생한다고 말씀해 주셨습니다.<br>
안해도 됨: 말씀해 주셨습니다. 두 번 반복은 글이 부자연스럽게 느껴집니다.
컴마도 빼봤습니다.

===
여느 때처럼 쏘카 서비스를 개발하는데 팀장님께서 저희가 개발했던 서비스에서 에러가 발생한다고 말해주셨습니다.

어떤 상황에서 발생했는지 여쭤보니 쏘카 앱 내의 웹뷰 서비스를 이용한 후, 앱을 백그라운드 상태에 두고 한참 후에 다시 열었을 때 에러가 발생한다고 하셨습니다.

2024-07-22 02:59 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +<p style='text-align: center; color: #646f7c;'> 웹뷰 백그라운드 → 특정 시간 후 포그라운드 → 웹뷰 리프레시 → 서버 호출 시 에러</p>
포그라운드 보다 포어그라운드를 많이 쓰는 거 같은데 확인해주시겠어요?

2024-07-22 02:59 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +- **iOS 기기에서만 발생(안드로이는 발생하지 않음)**
안드로이 > 안드로이드로 안 바뀌었습니다

2024-07-22 02:59 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +안녕하세요 쏘카에서 프론트엔드 개발을 담당하고 있는 리우입니다.<br>
안녕하세요 다음에 마침표가 들어가야합니다.

2024-07-22 02:59 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +해결 방법은 간단했지만 원인을 분석하고 가설을 도출한 후 테스트 진행하는 과정에서 많은 시간이 소요되었습니다. 그러나 이 과정을 통해 문제의 근본적인 원인을 찾아내고 해결함으로써 개발자로서 한 층 더 성장할 수 있었습니다. 또한, iOS 공식 문서에 해당 이슈에 대한 해결 방법을 제안해 보는 귀중한 경험도 해볼 수 있었습니다. (\*위에 첨부한 [버그 리
한 층 더 가 아니라 한층 더가 맞습니다

2024-07-22 02:59 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +  - `iOS safari에서도 동일하게 세션쿠키가 소실`되는 것을 확인함
Safari 첫글자 대문자로 바꿔주세요

2024-07-22 02:59 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +AS-IS : 하루 평균 약 246건 이슈 발생 => TO-BE : 하루 평균 약 0.85건 발생
개발자 도구→애플리케이션→쿠키탭
부분의 특수문자 화살표로 통일하는게 낫겠습니다.

2024-07-22 02:59 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +<p style='text-align: center; color: #646f7c;'>포그라운드 -> 웹뷰 리프레시 -> 쿠키 유지 -> 서버 호출 시 정상적으로 동작</p>
개발자 도구→애플리케이션→쿠키탭
부분의 특수문자 화살표로 통일하는게 낫겠습니다.

2024-07-22 02:59 UTC, socar-kj commented on _posts/2024-07-16-ios-webView-cookie.md
> +- **iOS 기기에서만 발생(안드로이는 발생하지 않음)**
iOS 기기에서만 발생(안드로이는 발생하지 않음)
이 말은 빼야합니다. 문제 원인이 아닙니다. 굳이 넣고 싶으면 위 단락 상황에 남겨야합니다.

2024-07-22 07:36 UTC, socar-kj approved these changes

2024-07-22 07:38 UTC, socar-raphael commented on _posts/2024-07-16-ios-webView-cookie.md
> +> - iOS 메모리 정리 시점은 공개된 바가 없어서 정확히는 모르지만, 테스트 결과 앱을 여러 개 실행시켜 메모리를 많이 사용하는 경우 발생합니다.
역시 전 iOS 팀장님 👍

2024-07-22 07:48 UTC, socar-rio reviewed
코멘트 반영 완료!

2024-07-23 01:29 UTC, merged