post: <에셋팀 레거시 개선 (2) 쏘카존 관리 시스템 - 차량재배치 리펙터링>
socar-inc/socar-inc.github.io pull request #202
Opened 2024-07-24 08:18 UTC by socar-onestone

# 개요
> web에서 해당 포스트를 확인할 수 있는 url 을 남겨주세요.
ex.) `socar-onestone.github.io`

# PR 리뷰 전 Checklist

> PR 시, 아래 부분을 확인해주세요! 

- [x] PR 제목을 `post: <글_제목>` 으로 해주셨나요? 
- [x] 파일명과 metadata의 date가 현재 시점 전으로 설정 되었나요? (현재 시점 이후라면 웹에서 확인이 되지 않습니다)
- [x] fork 한 repository의 url 로 확인이 가능한가요?  
- [x] 웹에서 이미지가 깨지지 않고 확인이 잘 되나요? (만약 깨진다면 경로를 다시 확인해주세요!)
- [x] 목차가 컨벤션을 맞춰서 잘 설정되어 있나요? (1, 1.1, 1.1.1 ...)

# 배포 전 Checklist

> 아래 부분이 모두 체크 되면 배포 준비가 완료됩니다!

- [x] 파일명과 metadata의 date가 배포 날짜로 설정되어 있는지 확인
- [x] 보안 관련 내용 최종 확인
- [x] 웹상에서 이미지 크기 및 화질, 저작권 확인
- [x] 목차 컨벤션 확인 
- [x] 맞춤법/비문 확인
- [x] 제목/부제 최종 확정
- [x] Background image 확정 및 저작권 확인

# TO DO 
> 머지하기 전 추가로 의논해야 될 점이 있다면 남겨주세요. 

제목 수정했습니다. (존관리시스템 차량재배치 Spring for Apache Kafka -> 쏘카존 관리 시스템 - 차량재배치 리펙터링)

2024-07-25 05:25 UTC, socar-kj requested changes

2024-07-25 05:25 UTC, socar-kj commented on _posts/2024-07-24-legacy-car-relocation.md
> +title:  에셋팀 레거시 개선 (2) 쏘카존 관리 시스템 - 차량재배치 리펙터링
리펙터링과 리팩터링이 혼재되어서 쓰이고 있는 거 같은데요, 리팩터링이 맞는 표현 같습니다.

2024-07-25 05:25 UTC, socar-kj commented on _posts/2024-07-24-legacy-car-relocation.md
> +title:  에셋팀 레거시 개선 (2) 쏘카존 관리 시스템 - 차량재배치 리펙터링
에셋과 애셋도 혼재되어있어서 애셋으로 통일이 어떨까합니다.

2024-07-25 05:25 UTC, socar-kj commented on _posts/2024-07-24-legacy-car-relocation.md
> + 지속 성장하는 소프트웨어를 만들기 위한 코드의 품질 개선 노력들을 글로 풀어내려고 합니다. 먼저 차량재배치의 레거시 개선 작업이 필요했던 이유와 차량재배치 비즈니스의 도메인 지식과 코드 리펙터링을 순차적으로을 소개하겠습니다.
순차적으로을 > 순서대로

2024-07-25 05:25 UTC, socar-kj commented on _posts/2024-07-24-legacy-car-relocation.md
> +차량재배치는 오래전 개발되어 방치돼 있었습니다. 코드 레벨에서의 문제로 일부 기능 수정 또는 오류 발생 시 수정해야 하는 부분이 명확하지 않았습니다. 하나의 거대 클래스로 이루어진 모든 코드를 파악한 뒤 일부분을 수정하는 방식으로 유지보수하고 있어 사이드이펙트에 대한 두려움이 존재했습니다. 기술 레벨에서의 문제로 기술조직 대부분이 사용 중인 AWS DMS
이렇게 문단을 구분하는건 어떤가요?

===

차량재배치는 오래전 개발되어 방치되어 있었고 크게 두 가지 문제가 있었습니다.
1) 코드 레벨에서의 문제로 일부 기능 수정 또는 오류 발생 시 수정해야 하는 부분이 명확하지 않았습니다.
하나의 거대 클래스로 이루어진 모든 코드를 파악한 뒤 일부분을 수정하는 방식으로 유지보수하고 있어 사이드이펙트에 대한 두려움이 존재했습니다.

2) 기술 레벨에서의 문제로 기술조직 대부분이 사용 중인 AWS DMS와 카프카를 이용하지 않고 맥스웰과 키네시스를 이용하고 있었습니다.
맥스웰을 사용할 줄 아는 개발자는 극히 드물었고 사용하는 곳도 몇 군데 없었습니다. 문제가 발생했을 때 참고 문헌이 없어 해결하기가 쉽지 않았습니다. 맥스웰 기능에 문제가 생기면 수동으로 작업을 처리해야 했는데 해당 문제는 자주 발생했습니다. 결국 PM, 개발자, 사업부 모두의 동의를 얻어 일감으로 처리하게 됐습니다.

2024-07-25 05:25 UTC, socar-kj commented on _posts/2024-07-24-legacy-car-relocation.md
> +쏘카는 공간인 존을 갖고 있습니다. 존에는 차량이 존재하고 그 차량을 서비스합니다. 매출 지표를 참고하거나 침수 등의 사유가 발생하면 한 존에서 다른 존으로 차량 이동을 수행하고 있습니다. 그것을 차량재배치로 정의합니다. 내부 시스템인 존관리시스템에서 차량재배치를 요청하고 실제 운전자가 차량을 이동시키면 이벤트를 받아 차량재배치를 수행합니다.
제안드려봅니다.

===

쏘카는 존이라는 차량이 존재하는 공간을 갖고 있습니다. 매출 지표를 참고하거나 침수 등의 사유가 발생하면 한 존에서 다른 존으로 차량 이동을 수행합니다. 그것을 차량재배치로 정의합니다. 내부 시스템인 존관리시스템에서 차량재배치를 요청하고, 실제 운전자가 차량을 이동시키면 이벤트를 받아 차량재배치를 수행합니다.

2024-07-25 05:25 UTC, socar-kj commented on _posts/2024-07-24-legacy-car-relocation.md
> +기존 코드는 다음과 같이 하나의 클래스에 모든 로직이 있었습니다. 키네시스와 스프링 로직이 비즈니스 로직에 침투해 있어 분석하기 힘들었고, 키네시스를 다른 기술로 변경하면 모든 코드를 수정해야 했습니다. 게다가 테스트코드도 부재한 상황이었습니다.
한자어를 빼봤는데 안 고쳐도 됩니다. 참고만 해주세요.

침투해 있어 > 들어가 있어서
변경하면 > 바꾸면
수정해야 했습니다 > 고쳐야했습니다
부재한 상황이었습니다 > 없었습니다

2024-07-25 05:25 UTC, socar-kj commented on _posts/2024-07-24-legacy-car-relocation.md
> +거대 클래스를 기능 및 비즈니스 로직별로 나누어 클래스를 작성하였습니다. 덕분에 테스트코드를 작성하기 쉬워졌고 기술이 바뀌더라도 비즈니스 로직을 가진 클래스는 변경될 필요가 없어졌습니다. 게다가 책임을 나눠 어느 부분에서 오류가 발생하더라도 어떤 책임을 가진 클래스에서 문제가 발생했는지 금방 찾을 수 있게 됐습니다. 뒤에서는 클래스 확장성을 고려하며 리팩
문단 나눠봤는데 참고만 해보십시요. 수고하셨습니다!

===

거대 클래스를 기능 및 비즈니스 로직별로 나누어 클래스를 작성했습니다.
테스트코드를 작성하기 쉬워졌고, 기술이 바뀌더라도 비즈니스 로직을 가진 클래스는 변경될 필요가 없어졌습니다.
게다가 책임을 나눠 어느 부분에서 오류가 발생하더라도 어떤 책임을 가진 클래스에서 문제가 발생했는지 금방 찾을 수 있게 됐습니다. 뒤에서는 클래스 확장성을 고려하며 리팩터링하다보니 전략패턴과 유사한 UML다이어그램이 만들어졌습니다.

객체지향 원칙을 적용해 코드의 품질을 적절히 관리해야만 지속 성장하는 소프트웨어를 만들 수 있습니다.
문제의 해법을 도출하기 위해 다양한 디자인패턴을 적용하고, 코드의 품질을 높이기 위한 고민을 함께 하고 싶은 분들은
쏘카 애셋(Asset)팀에 지원해 주세요!

2024-07-25 06:28 UTC, socar-onestone commented on _posts/2024-07-24-legacy-car-relocation.md
> +title:  에셋팀 레거시 개선 (2) 쏘카존 관리 시스템 - 차량재배치 리펙터링
감사합니다!

2024-07-25 06:41 UTC, socar-onestone commented on _posts/2024-07-24-legacy-car-relocation.md
> +거대 클래스를 기능 및 비즈니스 로직별로 나누어 클래스를 작성하였습니다. 덕분에 테스트코드를 작성하기 쉬워졌고 기술이 바뀌더라도 비즈니스 로직을 가진 클래스는 변경될 필요가 없어졌습니다. 게다가 책임을 나눠 어느 부분에서 오류가 발생하더라도 어떤 책임을 가진 클래스에서 문제가 발생했는지 금방 찾을 수 있게 됐습니다. 뒤에서는 클래스 확장성을 고려하며 리팩
"거대 클래스를 기능 및 비즈니스 로직별로 나누어 클래스를 작성했습니다."와 "객체지향 원칙을 적용해 코드의 품질을 적절히 관리해야만 지속 성장하는 소프트웨어를 만들 수 있습니다." 이게 각 문단의 제목이 되는걸까요 ㅎㅎ?

2024-07-25 07:18 UTC, socar-kj approved these changes

2024-07-25 07:59 UTC, merged

2024-07-31 04:17 UTC, socar-onestone commented
/맞춤법

2024-08-07 09:06 UTC, socar-onestone commented
/맞춤법

2024-08-07 09:09 UTC, socar-onestone commented
/맞춤법