팀내 공통코드 관리 변천사
socar-inc/socar-inc.github.io pull request #57
Opened 2021-06-01 05:02 UTC by socar-dorma

+ Post 상단 이미지들 optimizer 돌려서 용량 줄였어요.

2021-07-12 07:48 UTC, socar-hardy commented
웹 렌더링 버전은 여기입니다.

https://socar-dorma.github.io/dev/2021/05/27/common-code-management.html

2021-07-16 01:54 UTC, socar-hardy requested changes
글 잘 보았습니다! 읽다보니 개인적으로 궁금한게 있었는데, 이는 DM으로 여쭈어보겠습니다 ㅎㅎ

리뷰를 간략히 요약하면

- 초반에 공통 코드에 대한 설명(기존 쏘카에서 공통 코드가 없을 때는 어땠는지? 공통 코드라는 개념이 뭔지? 간단한 예시(쏘카 도메인에 좀 더 맞추어서)?) 에 대한 내용이 좀 더 들어가면 좋을거 같아요.
- 상단에 목차를 추가해주시면 좋을거 같습니다.
- 타이틀이 따로 있는데, h1은 뺴도 되지 않을까 싶습니다.

고생하셨습니다 :)

2021-07-16 01:54 UTC, socar-hardy commented on _posts/2021-05-27-common-code-management.md
> +     * A개발자가 공통코드 변경이 필요한 개발건을 진행하고 그 코드가 머지된 이후 다른 B개발자가 pull을 받은 후 이어서 다른 개발을 진행하려고 할때 로컬 DB에는 아직 신규 코드가 추가 되지 않아 매번 에러를 확인 후 notion에 있는 변경된 insert 쿼리를 로컬 DB에 실행 하게됩니다.
```suggestion
   * kotlin enum 코드와 로컬 DB의 값이 서로 달라서 에러 발생.
     * A개발자가 공통코드 변경이 필요한 개발건을 진행하고 그 코드가 머지된 이후 다른 B개발자가 pull을 받은 후 이어서 다른 개발을 진행하려고 할 때, 로컬 DB에는 아직 신규 코드가 추가 되지 않아 매번 에러를 확인하게 됩니다. 이 때 B개발자는 notion에 있는 변경된 insert 쿼리를 로컬 DB에 실행해야 하는데, 이 과정이 번거롭게 느껴졌습니다.
```

긴 문장을 조금 잘라보았습니다.

2021-07-16 01:54 UTC, socar-hardy commented on _posts/2021-05-27-common-code-management.md
> +   * 코드 컨벤션을 깔끔하게 유지하고 싶어하는 팀원들이 많아기도하고 코딩시에 해당 코드의 실제값을 DB나 kotlin 쪽 코드에서 찾아서 복사해서 써야 하는 것이 불편함.
```suggestion
   * 코드 컨벤션을 깔끔하게 유지하고 싶어하는 팀원들이 많기도하고, 코딩시에 해당 코드의 실제값을 DB나 kotlin 코드에서 찾아 복사해서 써야 하는 것이 불편합니다.
```

2021-07-16 01:54 UTC, socar-hardy commented on _posts/2021-05-27-common-code-management.md
> +   * 간혹 복사하지 않고 직접 타이핑시 오타로 인한 버그도 발생.
```suggestion
   * 또한 복사하지 않고 직접 타이핑시 오타로 인한 버그도 발생할 수 있었습니다.
```

2021-07-16 01:54 UTC, socar-hardy commented on _posts/2021-05-27-common-code-management.md
> +프론트엔드(vue.js)에서 일반적으로 `select`나 `raido`를 표시할때 데이터로 사용하고 서버(kotlin)에서는 비지니스 로직을 작성할때 사용하게 되고 DB에도 저장되게 됩니다.
여기 아래 부분에, 실제로 쏘카에서 어떤 공통코드를 사용하는지 예시를 들어주시면 좋을거 같아요.

2021-07-16 01:54 UTC, socar-hardy commented on _posts/2021-05-27-common-code-management.md
> +# 공통코드를 어떻게 관리 및 사용 할 것인가?
이 주제가 나오기 전에, 공통코드에 대해 좀 더 설명해주시면 좋을거 같습니다.

2021-08-12 00:26 UTC, socar-kyle commented
제가 금요일 내로 도마 글 모두 확인하겠습니다!!!!! 차주에 한번 수정하고, 업로드하는거로 가시죠..! 🙏

2021-08-12 01:51 UTC, socar-dorma commented on _posts/2021-05-27-common-code-management.md
> +# 공통코드를 어떻게 관리 및 사용 할 것인가?
아래에 팀소개 & 기술스택 소개 이후에 나오는 내용이 공통코드에 관련된 설명이라 추가로 설명을 더 하기가 애매하네요.

2021-08-12 01:51 UTC, socar-dorma commented on _posts/2021-05-27-common-code-management.md
> +프론트엔드(vue.js)에서 일반적으로 `select`나 `raido`를 표시할때 데이터로 사용하고 서버(kotlin)에서는 비지니스 로직을 작성할때 사용하게 되고 DB에도 저장되게 됩니다.
간단하게 몇가지 공통코드 추가했습니다.

2021-08-13 08:29 UTC, socar-kyle requested changes
피드백 드렸습니다!!! :) 용어 통일이나 문맥 정리 위주로 진행했습니다!

2021-08-18 01:50 UTC, socar-kyle approved these changes

2021-08-18 01:51 UTC, merged