배터리 종합관리 프로젝트 part1 머지
socar-inc/socar-inc.github.io pull request #59
Opened 2021-07-02 01:17 UTC by socarcharlie

2021-07-04 05:04 UTC, socar-kyle reviewed
일단 한번 봤는데, 다음 부분 추가해주시면 좋을 것 같아요!

- 말투가 갑자기 바뀌는 부분이 있습니다
- 글이 한 부분에 너무 많아서, 쪼개주시면 좋을 것 같아요
- 이미지는 Figure 3 이렇게 끝내지 말고 <그림 3> ~~~ 그래프 이렇게 해주시면 좋을 것 같아요
- 글을 한번 읽어보니 한번에 이해되진 않아서, 한번 더 읽으면서 질문드릴게요(조금 더 용어에 대해 추가하면 좋겠네요!)
- 처음에 글의 정보를 추가해주시면 좋습니다

참고로 지금 글에 "Please Take Warm Care For Socar" 글도 같이 올라와서, 이 내용은 삭제해주셔야 좋을 것 같아요!

2021-07-04 05:04 UTC, socar-kyle commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +			- 위의 두 리스트의 배터리 전압과, 신호가 들어오지 않는 시간 간격을 추출 <br>
```suggestion
	- 개발 당시 누적 데이터를 기준으로 배터리 방전 여부를 판단하는 알고리즘 제작
		- 예약 직전의 모든 배터리 전압(V)과 단말 신호주기(dt)를 추출하여 배터리 방전 신고 확률을 구합니다. 이때, 신고가 올 확률이 임계 확률보다 높아지면 사전 정비를 통해 이득을 얻을 수 있습니다. 이 **임계 확률 구하기가 결국 과제의 중요 목표 중 하나**입니다.
		- 연구 과정
			- 모든 예약 내역 데이터 추출
			- 예약 점유 시간동안 배터리 관련 신고가 없고, 시동이 한번이라도 켜진 예약 리스트를 추출
			- 예약 점유 시간동안 배터리 관련 신고가 있는 예약 리스트 추출
			- 위의 두 리스트의 배터리 전압과, 신호가 들어오지 않는 시간 간격을 추출 <br>
```

2021-07-04 05:04 UTC, socar-kyle commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +			- 서울 경인과 그 외 지역의 관리 비용 차이로 인해 Contour가 조금 달라질 수 있어서 아래와 같이 분리해서 추출했고, 정상 배터리 전압영역 (12.4V) 이하를 이상영역으로 명확히 보면 아래와 같음. 위의 Contour와 다르게 아래는 확률 분포가 무시된 Binary Contour임 (Figure 5, 6)
```suggestion
			- 서울 경인과 그 외 지역의 관리 비용 차이로 인해 Contour가 조금 달라질 수 있어서 아래와 같이 분리해서 추출했고, 정상 배터리 전압영역 (12.4V) 이하를 이상 영역으로 명확히 보면 아래와 같습니다. 위의 Contour와 다르게 아래는 확률 분포가 무시된 Binary Contour입니다(Figure 5, 6)
```

2021-07-04 05:04 UTC, socar-kyle commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +			- Binary Contour는 아래의 수식(Figure 7)을 기초로 하며, 운영 데이터를 통해 구해진 합리적 수치보다 Precision이 큰 영역을 Highlight 하여 만들어짐
```suggestion
			- Binary Contour는 아래의 수식(Figure 7)을 기초로 하며, 운영 데이터를 통해 구해진 합리적 수치보다 Precision이 큰 영역을 Highlight 하여 만들어집니다
```

여기서 말투가 바뀌네요. 통일해주시면 좋을 것 같습니다!

2021-07-04 05:04 UTC, socar-kyle commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +			- 샘플로 추출된 특정 기간동안 데이터를 바탕으로 Confusion Matrix를 계산하면 아래와 같음. 단, 113대 중 일부는 과잉정비가 아닐 수 있고 그 값을 정확히 알 수 없어 alpha 로 두었음
```suggestion
			- 샘플로 추출된 특정 기간동안 데이터를 바탕으로 Confusion Matrix를 계산하면 아래와 같습니다. 단, 113대 중 일부는 과잉정비가 아닐 수 있고 그 값을 정확히 알 수 없어 alpha로 두었습니다.
```

여기서 alpha라는 정의를 추가 설명하면 좋을듯해요

2021-07-04 05:04 UTC, socar-kyle commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +			- 자동차 시동용 배터리나 지게차 배터리로 널리 사용되는 납산전지는 이차전지의 한 종류입니다.  완전히 충전된 상태에서 음극판은 완전한 납으로만 구성되어 있고, 양극판은 이산화납으로 구성되어 있습니다. 전해액은 고농도의 황산인데 화학적 에너지를 가득 품고 있습니다. 시간이 지남에 따라 음극판이 고농도의 황산과 반응하여 황산납과 2개의 전자를 방출합니
여기 글이 너무 하나가 길어서, 쪼개는게 필요하겠어요!

2021-07-12 07:15 UTC, socar-hardy commented
이거 웹에서 보려면 어디서 봐야햐죠?

2021-07-12 07:16 UTC, socar-hardy commented
https://socarcharlie.github.io/mechanical%20engineering,%20chemical%20engineering/2021/07/08/socar-mobility-lab-battery-management-process-first-stage.html

여기 군요

2021-07-12 07:46 UTC, socar-hardy requested changes

2021-07-12 07:46 UTC, socar-hardy commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +쏘카 모빌리티Lab의 Charlie(하철수) 입니다. 기술 블로그에 올리는 저의 첫 포스트 입니다. 이 글을 보시는 분들에게 도움이 되었으면 좋겠습니다. 이번 글에서는 10,000대가 넘는 차량을 운영하는 쏘카의 차량 관리에 어떤 기술이 어떻게 적용되는지 공유드리고자 합니다.
```suggestion
안녕하세요. 쏘카 모빌리티Lab의 Charlie(하철수) 입니다. 이번 글에서는 10,000대가 넘는 차량을 운영하는 쏘카에서 차량 관리에 어떤 기술을 어떻게 적용하고 있는지 공유하고자 합니다.
```

첫 단락에 `안녕하세요` 만 툭튀하고 있어서, 바로 뒤에 소개하는 문장이랑 단락을 안 나누는게 나아 보입니다!  
또한 수동 형태의 문장을 능동 형태로 바꾸어서, 좀 더 적극적이고 자신감 있는 문장으로 수정했습니다.

2021-07-12 07:46 UTC, socar-hardy commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +쏘카의 모빌리티Lab은 모두 높은 수준의 기계 공학 지식을 보유한 인력으로 이루어졌으며, 쏘카의 풍부한 차량 데이터에 기계 공학 지식을 녹여 운영에 필요한 최적 솔루션을 만들고 있습니다. (우리에게 힘을 더해주실 우수한 분을 모시고 있습니다. 언제든지 지원해주세요.)
이 내용은 이 맥락에 등장하는게 어색하다고 느껴졌습니다.  
글 가장 마지막 단락에 넣는게 어떨까요?

2021-07-12 07:46 UTC, socar-hardy commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +
여기 바래 아래에 아래 내용에 대한 목차가 있었으면 좋겠습니다!

2021-07-12 07:46 UTC, socar-hardy commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +- 개인이 관리하는 일반적인 차량의 경우 3년간 600~800회의 시동 시도가 기록되고 배터리 제조사의 보증 시동 횟수도 600~800회 정도입니다. 그러나 쏘카가 운영하는 차량은 년간 2,200~2,800회 정도의 시동 시도가 발생합니다. 특히 2,200회를 넘어가는 시점에서는 배터리 관련 고장으로 인해 공업사에 차량이 입고될 확률이 급격히 높아집니다.
```suggestion
- 개인이 관리하는 일반적인 차량의 경우 3년간 600~800회의 시동 시도가 기록되고 배터리 제조사의 보증 시동 횟수도 600~800회 정도입니다. 그러나 쏘카가 운영하는 차량은 년간 2,200~2,800회 정도의 시동 시도가 발생합니다. 특히 2,200회를 넘어가는 시점에서는 배터리 관련 고장으로 인해 공업사에 차량이 입고될 확률이 급격히 높아집니다. 그러므로** 이 시기가 도래하기 전에 적절한 관리를 통해 배터리의 수명을 관리해주어야 합니다.**
```

소주제별 중요한 문장에 볼드를 넣어주시는건 어떤가요?

2021-07-12 07:46 UTC, socar-hardy commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +### 2. 문제 해결을 위한 접근 방법
`### 2. 문제 해결을 위한 접근 방법`

이 나오기 전에, `1. 배경` 후에 **문제 정의** 가 나와야 자연스러울거 같아요.  
배경을 읽고, 음 그렇군~ 하고 읽다가 문제가 무엇인지 명확히 알려주지 않고, 해결에 접근하니 부자연스럽다고 느꼈습니다.
배경 이후에 

```
따라서 다음과 같은 문제를 해결해고자 했습니다~
```

와 같은 문제 정의를 해주는 부분이 있으면 좋을거 같습니다.

2021-07-12 07:46 UTC, socar-hardy commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +- 현재 수집 가능하고 수년간 누적된 데이터 분석작업부터 시작
명사로 끝내지 않고 동사로 끝내는게 더 명확할거 같습니다.
다른 부분들도요!

2021-07-12 07:46 UTC, socar-hardy commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +	- 방전 의심 차량의 관리 방법
이쯤 오니 bullet 이 너무 긴데, 이 정도 depth 를 가지는 bullet 은 h3 로 빼는건 어떤가요?

2021-07-12 07:46 UTC, socar-hardy commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +## 배터리 종합 관리
h2 가 아래 둘 뿐인거 같습니다.

- `## 배터리 종합 관리`
- `## 맺으며`

차라리 이 부분을 지우고 (제목이랑 어차피 겹치므로) 현재 h3를 -> h2로 올리는게 depth 관리에 더 용이할거 같습니다.

2021-07-12 07:46 UTC, socar-hardy commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +쏘카 모빌리티Lab의 Charlie(하철수) 입니다. 기술 블로그에 올리는 저의 첫 포스트 입니다. 이 글을 보시는 분들에게 도움이 되었으면 좋겠습니다. 이번 글에서는 10,000대가 넘는 차량을 운영하는 쏘카의 차량 관리에 어떤 기술이 어떻게 적용되는지 공유드리고자 합니다.
여기 아래 대상 독자가 들어가야 할거 같은데, 아래까지 다 읽어보고 와서 다시보니 일반인이 대상 독자는 아니군요.  
데이터 + 차량 관리하는 전문 엔지니어들이 대상일 듯한데... 어떤 분들에게 도움이 될지 좀 더 스코핑하여 적어주시면 좋을거 같습니다.

마찬가지로 어떤 내용을 다루는지 간략히 소개해주는 것도 있으면 좋을듯 해요.

2021-07-12 07:52 UTC, socar-hardy commented
그리고 소주제 (h2) 단락 간에 `<br>` 태그를 넣어주시면 좋을거 같아요.
너무 단락간에 따닥붙어 있어서 여백을 좀 더 주면 가독성이 올라갈 거라고 생각합니다.

2021-07-12 12:20 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +쏘카의 모빌리티Lab은 모두 높은 수준의 기계 공학 지식을 보유한 인력으로 이루어졌으며, 쏘카의 풍부한 차량 데이터에 기계 공학 지식을 녹여 운영에 필요한 최적 솔루션을 만들고 있습니다. (우리에게 힘을 더해주실 우수한 분을 모시고 있습니다. 언제든지 지원해주세요.)
이 부분은 팀 소개를 약간은 해야할 듯 해서 팀의 설립 목적과 소개를 가미한 부분입니다.

2021-07-12 12:21 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +
목차는 한번 넣어보겠습니다.

2021-07-12 12:21 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +- 개인이 관리하는 일반적인 차량의 경우 3년간 600~800회의 시동 시도가 기록되고 배터리 제조사의 보증 시동 횟수도 600~800회 정도입니다. 그러나 쏘카가 운영하는 차량은 년간 2,200~2,800회 정도의 시동 시도가 발생합니다. 특히 2,200회를 넘어가는 시점에서는 배터리 관련 고장으로 인해 공업사에 차량이 입고될 확률이 급격히 높아집니다.
좋습니다.

2021-07-12 12:54 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +쏘카 모빌리티Lab의 Charlie(하철수) 입니다. 기술 블로그에 올리는 저의 첫 포스트 입니다. 이 글을 보시는 분들에게 도움이 되었으면 좋겠습니다. 이번 글에서는 10,000대가 넘는 차량을 운영하는 쏘카의 차량 관리에 어떤 기술이 어떻게 적용되는지 공유드리고자 합니다.
어떤 내용을 다루는 지는
"모빌리티Lab을 대표하여 ... ** 자동차 배터리관리 ** 에관한 이야기입니다." 에서 다루었습니다.

대상 스코핑에 대해서는 추가하겠습니다.

2021-07-12 13:04 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +	- 방전 의심 차량의 관리 방법
이게 참 애매한데... 이게 문제 해결을 위한 접근 방법 아래에 들어가야하는 내용은 분명히 맞습니다. 그런데 위에 카일과 이야기 나눈 내용을 바탕으로 글을 쪼개고 쪼개다보니 depth가 좀 길어졌어요. 
이건 depth에도 불구하고 내용 전개상 이대로 붙어 있는게 나을듯 합니다.
안될까요?

2021-07-12 13:12 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +## 배터리 종합 관리
이 부분은 글 구성이 바뀌면서 다른 방식으로 해결이 될 수 있을 듯 합니다.

2021-07-14 01:09 UTC, socar-hardy requested changes
고생하셨습니다 찰리! 이전보다 글이 훨씬 매끄러워진거 같습니다.  
글 Depth 관련해서 제가 따로 PR 넣어볼게요. 확인 부탁드립니다!

2021-07-14 01:09 UTC, socar-hardy commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +  	- 방전 초입을 포착해도 이동, 회수, 배터리 관리, 재 장착 과정을 거치면서 발생하는 추가 관리 비용은 필연적이므로 선제적 관리가 기존 관리 방법에 비해 이득을 보장하는 영역을 찾아내는 알고리즘이 필요합니다.
더불어, `영역` 이라고 표현하셨는데 이게 무엇인지 와닿지 않습니다.
혹시 조금만 더 설명해주실 수 있을까요?

2021-07-14 01:09 UTC, socar-hardy commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +  	- 방전 초입을 포착해도 이동, 회수, 배터리 관리, 재 장착 과정을 거치면서 발생하는 추가 관리 비용은 필연적이므로 선제적 관리가 기존 관리 방법에 비해 이득을 보장하는 영역을 찾아내는 알고리즘이 필요합니다.
바로 뒤에 내용을 더 읽어보니, 저는 아래처럼 이해했습니다. 

```suggestion
  	- 방전 초입을 포착해도 이동, 회수, 배터리 관리, 재 장착 과정을 거치면서 발생하는 추가 관리 비용은 필연적으로 발생합니다. 따라서 방전 초입 이전에 방전이 발생할지를 미리 예측해야 합니다.
```

제가 이해한게 맞나요?

2021-07-14 07:03 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +
정보 삽입 완료했습니다.

2021-07-14 07:03 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +쏘카 모빌리티Lab의 Charlie(하철수) 입니다. 이 곳에서 처음 인사드립니다. 블로그에 글을 남기는게 처음이라 참 어색합니다. 그럼에도 만대가 넘는 차량을 운영하는 쏘카의 차량 관리에 어떤 기술이 어떻게 적용되는지 공유드리고자 용기내어 글을 남겨봅니다.
수정 했습니다.

2021-07-14 07:03 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +그래도 공학자는 문제를 풀어내야 공학자이지요! 지금부터 쏘카는 어떻게 이 문제를 풀어가는지 최대한 쉽게 나누려고 합니다.
맞춤법을 전반적으로 다시 확인했습니다.

2021-07-14 07:03 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +<p align="center"> Figure 1 </p>
피규어 형태 다 바꾸었습니다.

2021-07-14 07:09 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +- 차량에서 받을 수 있는 배터리 상태정보의 한계가 명확합니다. 별도의 정보 수집 장치가 없다면 시간, 전압, 시동상태 외에 차량에서 받을 수 있는 배터리 관련 정보는 없습니다.
"차량에서 받을 수 있는 배터리 상태 데이터 종류에 한계가 있습니다. 별도의 데이터 수집 장치가 없다면 시간, 전압, 시동 상태 외에 차량에서 받을 수 있는 배터리 관련 데이터는 없습니다. "
로 수정했습니다.

2021-07-14 07:09 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +- 일부 고객의 배터리 사용 패턴에 따라 정상적 컨디션의 배터리가 방전되는 경우도 다수 존재합니다. 통계적으로 실제 방전 신고의 60%는 현 고객 혹은 직전 고객의 과실로 인한 문제였습니다.
수정했습니다.

2021-07-14 07:15 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +		- 배터리 상태가 어느정도 보존된 상태의 방전 초입의 배터리는 물리 화학적 관리를 거치면 배터리 수명을 연장 시킬 수 있습니다.
1. 수년간 누적된 데이터 분석 작업부터 시작→수년간 누적된 데이터 중 현재도 수집이 되고 있는 Feature에 대한 분석작업부터 시작합니다. (현재 수집이 가능한 Feature를 사용해야 과거 데이터를 통해 만들어진 모델을 앞으로도 활용할 수 있습니다.)
2. 배터리 상태가 어느정도 보존된 상태의 방전 초입의 배터리는 물리 화학적 관리를 거치면 배터리 수명을 연장시킬 수 있습니다→배터리 상태가 어느정도 보존된 상태의 방전 초입의 배터리는 물리 화학적 관리를 거치면 배터리 수명을 연장시켜 교체하지 않아도 좀 더 사용할 수 있습니다.

2021-07-14 07:15 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +		- 배터리 상태가 어느정도 보존된 상태의 방전 초입의 배터리는 물리 화학적 관리를 거치면 배터리 수명을 연장 시킬 수 있습니다.
정확하게 전달되어야 하는 부분이라 최소수정+설명추가로 바꿨습니다.

2021-07-14 07:16 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +		- 방전 초입을 어떻게 잡아내는가에 따라 관리 가능 여부가 갈립니다.
초입은 초반보다 더 이른 구간을 말하는 단어입니다.
초반은 초기구간의 전반적 영역을 커버하지만 초입은 초기구간 중에서도 극히 앞부분을 이야기합니다.

2021-07-14 07:17 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +		- 방전 초입을 어떻게 잡아내는가에 따라 관리 가능 여부가 갈립니다.
初入

2021-07-14 07:17 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +		<p align="center"> Figure 2 <br> </p>
일괄 변경 다 했습니다.

2021-07-14 07:20 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +		- 방전 초입을 포착해도 이동, 회수, 배터리 관리, 재 장착 과정을 거치면서 발생하는 추가 관리 비용은 필연적이므로 선제적 관리가 기존 관리 방법에 비해 이득을 보장하는 영역을 찾아내는 알고리즘이 필요합니다.
1. 선제적 관리는 필수 워딩입니다. 신고 이전에 먼저 찾아내어 관리하자가 중요한 포인트입니다.
2. 운영팀과 이야기할 때 운영쪽에서도 강조하던 워딩이 바로 **기존 관리 방법 대비 "이득"이 보장되는가** 였습니다. 따라서 이득이란 단어도 유지하는게 좋을 듯 합니다.
3. 대신 문체를 다듬겠습니다,

2021-07-14 07:21 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +		- 방전 초입을 포착해도 이동, 회수, 배터리 관리, 재 장착 과정을 거치면서 발생하는 추가 관리 비용은 필연적이므로 선제적 관리가 기존 관리 방법에 비해 이득을 보장하는 영역을 찾아내는 알고리즘이 필요합니다.
방전 초입을 포착해도 이동, 횟수, 배터리 관리, 재 장착 과정을 거치면서 발생하는 추가 관리 비용이 필요합니다. 따라서 선제적 관리가 기존 관리 방법에 비해 사업 및 운영상의 이득을 보장하는 영역을 찾아내는 알고리즘이 필요합니다.

2021-07-14 07:23 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +			- 위의 두 리스트의 배터리 전압과, 신호가 들어오지 않는 시간 간격을 추출 <br>
수정 완료 했습니다.

2021-07-14 07:23 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +			- Binary Contour는 아래의 수식(Figure 7)을 기초로 하며, 운영 데이터를 통해 구해진 합리적 수치보다 Precision이 큰 영역을 Highlight 하여 만들어짐
말투는 일괄 수정했습니다.

2021-07-14 07:24 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +			- 샘플로 추출된 특정 기간동안 데이터를 바탕으로 Confusion Matrix를 계산하면 아래와 같음. 단, 113대 중 일부는 과잉정비가 아닐 수 있고 그 값을 정확히 알 수 없어 alpha 로 두었음
미지수 alpha라는 명확한 설명을 넣었습니다.

2021-07-14 07:24 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +			- 자동차 시동용 배터리나 지게차 배터리로 널리 사용되는 납산전지는 이차전지의 한 종류입니다.  완전히 충전된 상태에서 음극판은 완전한 납으로만 구성되어 있고, 양극판은 이산화납으로 구성되어 있습니다. 전해액은 고농도의 황산인데 화학적 에너지를 가득 품고 있습니다. 시간이 지남에 따라 음극판이 고농도의 황산과 반응하여 황산납과 2개의 전자를 방출합니
쪼갰습니다.

2021-07-14 07:32 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +			- 서울 경인과 그 외 지역의 관리 비용 차이로 인해 Contour가 조금 달라질 수 있어서 아래와 같이 분리해서 추출했고, 정상 배터리 전압영역 (12.4V) 이하를 이상영역으로 명확히 보면 아래와 같음. 위의 Contour와 다르게 아래는 확률 분포가 무시된 Binary Contour임 (Figure 5, 6)
수정했습니다.

2021-07-14 07:33 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +- 개인이 관리하는 일반적인 차량의 경우 3년간 600~800회의 시동 시도가 기록되고 배터리 제조사의 보증 시동 횟수도 600~800회 정도 입니다. 그러나 쏘카가 운영하는 차량은 년간 2200~2800회 정도의 시동 시도가 발생합니다. 특히 2200회를 넘어가는 시점에서는 배터리 관련 고장으로 인해 공업사에 차량이 입고될 확률이 급격히 높아집니다. 그
수정했습니다.

2021-07-14 07:34 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +  	- 방전 초입을 포착해도 이동, 회수, 배터리 관리, 재 장착 과정을 거치면서 발생하는 추가 관리 비용은 필연적이므로 선제적 관리가 기존 관리 방법에 비해 이득을 보장하는 영역을 찾아내는 알고리즘이 필요합니다.
1. 선제적 관리는 필수 워딩입니다. 신고 이전에 먼저 찾아내어 관리하자가 중요한 포인트입니다.
2. 운영팀과 이야기할 때 운영쪽에서도 강조하던 워딩이 바로 기존 관리 방법 대비 "이득"이 보장되는가 였습니다. 따라서 이득이란 단어도 유지하는게 좋을 듯 합니다.
3. 대신 문체를 다듬겠습니다.
4. 그래서 다음과 같이 썼습니다. → 방전 초입을 포착해도 이동, 횟수, 배터리 관리, 재 장착 과정을 거치면서 발생하는 추가 관리 비용이 필요합니다. 따라서 선제적 관리가 기존 관리 방법에 비해 사업 및 운영상의 이득을 보장하는 영역을 찾아내는 알고리즘이 필요합니다.

2021-07-14 07:35 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +<br>
제거했습니다.

2021-07-14 07:35 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +- 방전과 관련된 문제는 월 100건 이상 접수됩니다.  어떤 경로로 접수되어 수리를 받는가에 따라 다르지만 준중형차량(대표적으로 아반떼)  기준 수리비가  25만원까지 청구되기도 합니다.  방전문제는 회사의 관리 손실을 일으키는 중요 요소입니다.
볼드 반영했습니다.

2021-07-14 07:35 UTC, socarcharlie commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +  - 고객 신고가 들어오면 점프 혹은 배터리 교환을 했던 기존 프로세스를 배터리 상태를 바탕으로 한 프로세스로 바꾸었습니다.
반영 했습니다.

2021-07-14 08:11 UTC, socar-hardy requested changes
중간에 서제션 하나가 반영이 안된거 같습니다 ㅎㅎ

2021-07-14 08:11 UTC, socar-hardy commented on _posts/2021-06-08-socar-mobility-lab-battery-management-process-first-stage.md
> +- 방전과 관련된 문제는 월 100건 이상 접수됩니다.  어떤 경로로 접수되어 수리를 받는가에 따라 다르지만 준중형차량(대표적으로 아반떼)  기준 수리비가  25만원까지 청구되기도 합니다.  방전문제는 회사의 관리 손실을 일으키는 중요 요소입니다.
반영이 안된거 같아용

2021-07-14 08:25 UTC, socar-hardy commented
고생하셨습니다 찰리.

현재 뒤에 커버이미지가 보이지 않는데, 이 부분도 추가해주시면 좋겠습니다.
리드미에 보시면 추가하는 방법에 대해 설명되어 있습니다 ㅎㅎ

![image](https://user-images.githubusercontent.com/62049738/125589344-3fa3b3d3-b432-47e5-b925-f0da80b69001.png)

2021-07-14 09:41 UTC, socar-hardy approved these changes
고생하셨습니다.
@socar-kyle 카일이 한 번더 확인 해주세요~!

2021-07-15 02:59 UTC, merged