쏘카 안드로이드팀 신입 개발자 미뇽의 입사기
socar-inc/socar-inc.github.io pull request #63
Opened 2021-08-09 07:24 UTC by socar-mignon

신입개발자가 회사를 고를 때, 어떠한 기준으로 회사를 바라봐야할지 경험을 통해 제공

안드로이드팀 신입 개발자로서 바라본 쏘카의 모습과 개발 문화 기술

2021-08-09 10:31 UTC, arngard commented on _posts/2021-08-09-join-in-socar-android.md
> +안드로이드팀은 좋은 방향으로 성장하기 위해 항상 노력하고 있습니다. 물론 안드로이드 팀뿐만 아니라 쏘카의 모든 팀이 한 발짝 더 나아가기 위해 노력하고 있습니다. 항상 노력하고자 하는 모습도 좋지만, 쏘카에 와서 가장 만족한 것은 좋은 사람들입니다. 지금은 코로나 4단계로 전사 재택근무 중이라 어렵지만, 이전에 회사에 출근해서 얘기하고, 함께 식사하는 시
```suggestion
안드로이드 팀은 좋은 방향으로 성장하기 위해 항상 노력하고 있습니다. 물론 안드로이드 팀뿐만 아니라 쏘카의 모든 팀이 한 발짝 더 나아가기 위해 노력하고 있습니다. 항상 노력하고자 하는 모습도 좋지만, 쏘카에 와서 가장 만족한 것은 좋은 사람들입니다. 지금은 코로나 4단계로 전사 재택근무 중이라 어렵지만, 이전에 회사에 출근해서 얘기하고, 함께 식사하는 시간이 너무나도 즐거웠습니다. 아래의 사진처럼 벚꽃이 이쁘게 핀 날 피크닉 가듯이 식사를 하기도 했습니다.
```

2021-08-09 10:31 UTC, arngard commented on _posts/2021-08-09-join-in-socar-android.md
> +title: "쏘카 안드로이드팀 신입 개발자 미뇽의 입사기"
```suggestion
title: "쏘카 안드로이드 팀 신입 개발자 미뇽의 입사기"
```

2021-08-09 10:31 UTC, arngard commented on _posts/2021-08-09-join-in-socar-android.md
> +팀마다 규칙이 다르지만, 안드로이드팀은 전체 팀원 중 3명 이상에게 approve를 받아야 merge를 할 수 있습니다. 아무리 바쁘다고 하더라도 리뷰를 대충하지 않습니다. 안드로이드 팀은 "빠르게 Merge를 해야 하는 Pull Request라면 리뷰를 대충하는 것이 아니라 리뷰에 더 많은 시간을 투자해야 한다"라는 마인드를 가지고 있습니다. 이 문화
```suggestion
팀마다 규칙이 다르지만, 안드로이드 팀은 전체 팀원 중 3명 이상에게 approve를 받아야 merge를 할 수 있습니다. 아무리 바쁘다고 하더라도 리뷰를 대충하지 않습니다. 안드로이드 팀은 "빠르게 Merge를 해야 하는 Pull Request라면 리뷰를 대충하는 것이 아니라 리뷰에 더 많은 시간을 투자해야 한다"라는 마인드를 가지고 있습니다. 이 문화 속에서 저는 더 도움 되는 리뷰를 남겨보고자 노력 중입니다.     
```

2021-08-09 10:31 UTC, arngard commented on _posts/2021-08-09-join-in-socar-android.md
> +위 사진은 입사 이후 제가 지금까지 작성한 Pull Request입니다. 네이밍부터 로직 상에 더 좋은 아이디어를 제안하는 것까지 다양한 코멘트를 작성 받아서 한 PR에 최대 84개의 코멘트를 받은 적도 있습니다. 쏘카 안드로이드팀이 코드리뷰 하는 방법이 더 궁금하다면 [해당 링크](https://speakerdeck.com/socar/kodeu-riby
```suggestion
위 사진은 입사 이후 제가 지금까지 작성한 Pull Request입니다. 네이밍부터 로직 상에 더 좋은 아이디어를 제안하는 것까지 다양한 코멘트를 작성 받아서 한 PR에 최대 84개의 코멘트를 받은 적도 있습니다. 쏘카 안드로이드 팀이 코드리뷰 하는 방법이 더 궁금하다면 [해당 링크](https://speakerdeck.com/socar/kodeu-ribyu-jeogeunggi)를 확인해주세요.
```

2021-08-09 10:31 UTC, arngard commented on _posts/2021-08-09-join-in-socar-android.md
> +안드로이드팀의 경우는 매주 금요일에 `개수다` 라는 것을 진행합니다. 기술적인 것도 공유하지만 이외에 팀원들에게 도움이 될만한 내용이라면 서로 공유하는 시간을 갖는 것입니다. 개수다에서 공유된 내용이 실제 쏘카 앱에 적용되어 좀 더 나은 코드를 생성하는 것으로 연결되는 경우도 있습니다.
```suggestion
안드로이드 팀의 경우는 매주 금요일에 `개수다` 라는 것을 진행합니다. 기술적인 것도 공유하지만 이외에 팀원들에게 도움이 될만한 내용이라면 서로 공유하는 시간을 갖는 것입니다. 개수다에서 공유된 내용이 실제 쏘카 앱에 적용되어 좀 더 나은 코드를 생성하는 것으로 연결되는 경우도 있습니다. 
```

2021-08-09 10:31 UTC, arngard commented on _posts/2021-08-09-join-in-socar-android.md
> +현재 쏘카 안드로이드팀은 **주니어, 시니어와 무관하게 채용 중**입니다. 안드로이드 팀 외에도 쏘카의 채용은 현재진행형입니다. 카쉐어링 분야와 쏘카에 관심 있고, 수평적 문화 속에서 좋은 사람들과 즐겁게 일할 분을 기다리고 있습니다.
```suggestion
현재 쏘카 안드로이드 팀은 **주니어, 시니어에 무관하게 채용 중**입니다. 안드로이드 팀 외에도 쏘카의 채용은 현재진행형입니다. 카쉐어링 분야와 쏘카에 관심 있고, 수평적 문화 속에서 좋은 사람들과 즐겁게 일할 분을 기다리고 있습니다.
```

2021-08-12 00:03 UTC, socar-hardy requested changes
글 깔끔하게 잘 써주셨네요! 

https://socar-mignon.github.io/2021/08/09/join-in-socar-android.html
들어가보면 상단에 메타 데이터 깨져있는데, 이 부분은 @socar-kyle 이 봐주셔야 할거 같아요!

2021-08-12 00:03 UTC, socar-hardy commented on _posts/2021-08-09-join-in-socar-android.md
> +저는 흔히 말하는 대기업, 공기업보다는 자체 서비스를 가진 회사를 가고 싶었습니다. 내가 개발한 기능을 내가 직접 사용하고 싶었기 때문입니다. 하지만 대기업과 공기업에 비해 제가 가고자 원하는 회사들의 정보는 턱없이 부족했고, 대학 내에서는 해당 방향으로 취업을 한 사례 또한 찾기 힘들었습니다. 이 글은 이전의 저와 같은 상황에 있는 취업준비생분들에게 조
aron 서제션이 덧붙입니다.

```suggestion
저는 흔히 말하는 대기업, 공기업보다는 자체 서비스를 가진 IT 회사를 가고 싶었습니다. 내가 개발한 기능을 내가 직접 사용하고 싶었기 때문입니다. 하지만 제가 가고자 하는 IT 회사들의 정보는 턱없이 부족했고, 대학 내에서는 해당 방향으로 취업을 한 사례를 찾는 것도 힘들었습니다. 

이 글에서는 제가 취업을 준비할 당시 어떤 기준으로 지원할 회사를 생각했는지, 그리고 쏘카 안드로이드 팀에 합류한 이후 신입 개발자로서 어떤 것들을 느꼈는지 소개합니다. 이 글이 이전의 저처럼 IT 서비스 회사로 취업을 준비하시는 분들에게 조금의 도움이라도 되었으면 좋겠습니다.
```

2021-08-16 09:44 UTC, socar-kyle requested changes
고생하셨습니다! 몇 피드백만 확인해주시고(아릉, 하디, 카일) 수정하시면 바로 업로드 가시죠! :)

2021-08-16 09:44 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +회사에서 운영하는 서비스가 "내가 사용하고 싶은 서비스인가?"에 대해 고민해봐야 한다고 생각합니다. 회사에서 운영하는 서비스는 결국 내가 개발해야 하는 서비스입니다. 내가 사용하고 싶은 서비스를 개발할 때, 그렇지 않았을 때 비해 개발이 완료되었을 때, 만족도가 더 크다고 생각합니다. 또한 실제 서비스를 사용해볼 가능성도 높으므로 실사용을 통해 서비스의
```suggestion
회사에서 운영하는 서비스가 **'제가 사용하고 싶은 서비스인가?'**에 대해 고민해봐야 한다고 생각합니다. 회사에서 운영하는 서비스는 결국 제가 개발해야 하는 서비스입니다. 제가 사용하고 싶은 서비스를 직접 개발하고 배포하면 만족도가 더 크다고 생각합니다. 또한 직접 서비스를 사용하기도 하므로, 서비스의 개선할 점과 방향성에 대한 파악이 손쉽다고 생각합니다.
```

저도 위에 두분꺼에 덧붙입니다..!

2021-08-16 09:44 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +개발자가 회사에 얻고자 하는 것은 월급뿐만 아니라 좋은 코드에 대한 경험도 있다고 생각합니다. 하지만 회사가 좋은 코드를 위해 리소스를 투자하는 것은 당연하지 않습니다. 회사의 목적은 이익이고, 좋은 코드와 아키텍처에 대한 투자는 리소스 낭비가 될 수 있기 때문입니다. 당연하지 않은 일이기에 코드와 아키텍처에 투자하는 회사는 이에 대해 관심이 많은 회사이
```suggestion
### 3. 단순한 기능(Feature) 개발 외에 코드의 장기적인 생산성을 생각해주는 회사

개발자가 회사에 얻고자 하는 것은 월급뿐만 아니라 **좋은 코드에 대한 경험**도 있다고 생각합니다. 하지만 회사가 좋은 코드를 위해 리소스를 투자하는 것은 당연하지 않습니다. 회사의 목적은 이익이고, 좋은 코드와 아키텍처에 대한 투자는 리소스 낭비가 될 수 있기 때문입니다. 당연하지 않은 일이기에 코드와 아키텍처에 투자하는 회사는 이에 대해 관심이 많은 회사이고, 개발자로서 좋은 코드에 대한 경험을 얻을 수 있다고 생각했습니다.
```

Feature라는 표현이 일하는 사람에겐 익숙한데, 학생분들에게 익숙하지 않을 수도 있어서 기능(Feature)라고 하면 어떨까요? 혹은 다른 표현도 좋아요!

2021-08-16 09:44 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +쏘카는 3가지 기준에 부합하는 회사입니다. 100명 이상의 규모를 갖고 있고, 카쉐어링이라는 매력적인 분야에 큰 입지를 가진 회사이며, 현재 안드로이드 팀의 인원이 5명 이상입니다. 회사의 코드와 아키텍처에 대한 정보를 온라인상에서 얻기는 어려웠으나 면접 과정에서 쏘카의 코드에 대해 자신 있게 설명하는 모습에서 좋은 코드에 투자하는 회사임을 알았습니다.
```suggestion
쏘카는 3가지 기준에 부합하는 회사입니다. 임직원이 300명 이상이고 카쉐어링이라는 매력적인 분야에 큰 입지를 가진 회사인 동시에 안드로이드 팀의 인원이 5명 이상입니다. 회사의 코드와 아키텍처에 대한 정보를 온라인상에서 얻기는 어려웠으나 면접 과정에서 쏘카의 코드에 대해 자신 있게 설명하는 모습에서 좋은 코드에 투자하는 회사임을 알았습니다.
```

2021-08-16 09:44 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +3가지 기준 외에도 쏘카는 데이터라는 매력 포인트를 가지고 있습니다. 쏘카는 많은 사용자를 보유한 서비스로 다양한 데이터를 가지고 있으며, 이를 활용하고자 독립적인 데이터 팀을 구성하고 있습니다. 데이터 팀에서 데이터를 분석하여 제공한 객관적인 수치를 통해 다각도로 사용자의 니즈를 파악하고 있습니다. 이러한 객관적인 자료는 내가 개발하는 기능이 어떤 영향
```suggestion
3가지 기준 외에도 쏘카는 데이터라는 매력 포인트를 가지고 있습니다. 쏘카는 많은 사용자를 보유한 서비스로 다양한 데이터를 가지고 있으며, 이를 활용하고자 독립적인 데이터 조직을 운영하고 있습니다. 데이터 팀에서 데이터를 분석하여 제공한 객관적인 수치를 통해 다각도로 사용자의 니즈를 파악하고 있습니다. 이러한 객관적인 자료로 제가 개발하는 기능이 어떤 영향을 끼치는지 확인할 수 있습니다. 다양한 데이터와 이를 분석하여 이용할 수 있는 능력을 갖추고 있는 것이 쏘카의 또 다른 매력 포인트입니다.

데이터 조직이 궁금하시면 [쏘카 데이터 그룹 - 데이터 사이언티스트 인턴 9개월 후기](https://tech.socarcorp.kr/data/2020/08/19/socar-data-group-intern-review.html) 글을 읽어보시는 것을 추천드립니다.

```

2021-08-16 09:44 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +쏘카를 알아볼 때 아쉬웠던 점은 지원하는 팀의 기술적인 내용이나 개발문화를 외부에서 알기 어렵다는 점입니다. 회사에서 기술 블로그를 운영하고 있으나 실질적으로 사용하는 기술 혹은 개발문화에 관해 서술된 게시글이 없었습니다. 입사 이후 알아보니 쏘카에서 발표한 일부의 자료를 공개한 [사이트](https://speakerdeck.com/socar)도 있었고,
```suggestion
쏘카에 입사 지원할 때 아쉬웠던 점은 팀의 기술적인 내용이나 개발 문화를 외부에서 알기 어려웠다는 점입니다. 회사에서 기술 블로그를 운영하고 있으나 실질적으로 사용하는 기술 혹은 개발문화에 관해 서술된 게시글은 없었습니다. 입사 이후 알아보니 쏘카에서 발표한 일부의 자료를 공개한 [사이트](https://speakerdeck.com/socar)도 있었고, 회사에서 블로그 작성을 장려하기 위해 다양한 혜택을 마련하고 있습니다. 이러한 회사의 노력은 블로그의 활성화를 가져오고 있습니다. 앞으로 [블로그](https://tech.socarcorp.kr)를 통해 쏘카의 기술적인 이야기를 전달해 드릴 수 있을 것 같습니다.
```

2021-08-16 09:44 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +![](/img/join-in-socar-android/talk-in-slack.png){: width="100%"}
저도 하디 의견처럼 질문에 대한 여러 커뮤니케이션은 그냥 노출해도 괜찮다고 생각해요! 아릉과 한번 이야기해보셔도 좋겠네용!

2021-08-16 09:44 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +팀마다 규칙이 다르지만, 안드로이드팀은 전체 팀원 중 3명 이상에게 approve를 받아야 merge를 할 수 있습니다. 아무리 바쁘다고 하더라도 리뷰를 대충하지 않습니다. 안드로이드 팀은 "빠르게 Merge를 해야 하는 Pull Request라면 리뷰를 대충하는 것이 아니라 리뷰에 더 많은 시간을 투자해야 한다"라는 마인드를 가지고 있습니다. 이 문화
```suggestion
팀마다 규칙이 다르지만, 안드로이드 팀은 전체 팀원 중 3명 이상에게 Approve를 받아야 Merge 할 수 있습니다. 아무리 바쁘다고 하더라도 리뷰를 대충 하지 않습니다. 안드로이드 팀은 "빠르게 Merge 해야 하는 Pull Request라면 리뷰를 대충 하는 것이 아니라 리뷰에 더 많은 시간을 투자해야 한다"라는 마인드를 가지고 있습니다. 이 문화 속에서 저는 더 도움 되는 리뷰를 남겨보고자 노력 중입니다.  
```

2021-08-16 09:44 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +위 사진은 입사 이후 제가 지금까지 작성한 Pull Request입니다. 네이밍부터 로직 상에 더 좋은 아이디어를 제안하는 것까지 다양한 코멘트를 작성 받아서 한 PR에 최대 84개의 코멘트를 받은 적도 있습니다. 쏘카 안드로이드팀이 코드리뷰 하는 방법이 더 궁금하다면 [해당 링크](https://speakerdeck.com/socar/kodeu-riby
@arngard 아릉 요 PR은 공개되어도 괜찮다고 보시는거죠? (이런 내용은 팀에서 결정하면 된다고 하네요!)

2021-08-16 09:44 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +더 많은 사람을 쏘카로 꼬셔보고자 안드로이드 팀원들이 새로운 쏘팸에게 남기고 싶은 한마디를 작성해보았습니다.
```suggestion
더 많은 사람을 쏘카로 모시고자 안드로이드 팀원들이 새로운 쏘팸에게 남기고 싶은 한마디를 작성해보았습니다.
```

꼬시다보단 모시다라는 표현이 더 격이 좋을 것 같아서 수정해봅니다!

2021-08-16 09:44 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +현재 쏘카 안드로이드팀은 **주니어, 시니어와 무관하게 채용 중**입니다. 안드로이드 팀 외에도 쏘카의 채용은 현재진행형입니다. 카쉐어링 분야와 쏘카에 관심 있고, 수평적 문화 속에서 좋은 사람들과 즐겁게 일할 분을 기다리고 있습니다.
```suggestion
현재 쏘카 안드로이드 팀은 **주니어, 시니어에 무관하게 채용 중**입니다. 안드로이드 팀 외에도 쏘카의 채용은 모두 열려있습니다. 카쉐어링 분야와 쏘카에 관심 있고, 수평적 문화 속에서 좋은 사람들과 즐겁게 일할 분을 기다리고 있습니다.
```

2021-08-16 09:44 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +[[쏘카는 채용 중](https://www.notion.so/d458b6b77a2243fb873d1ac800c321f7)]
```suggestion
```

Footer에 다음 내용이 있어서 삭제해도 괜찮을 것 같네요!

```
쏘카는 언제나 쏘카 서비스를 함께 만들며 기술적인 문제를 함께 풀어나갈 능력있는 개발자/디자이너/기획자/데이터 사이언티스트 등을 모시고 있습니다. 자세한 내용은 쏘카 채용공고 페이지를 확인 부탁드립니다 :)
```

2021-08-16 09:44 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +<br />
```suggestion
```

여백이 없어도 괜찮을 것 같네요!

2021-08-17 06:38 UTC, socar-mignon commented on _posts/2021-08-09-join-in-socar-android.md
> +![](/img/join-in-socar-android/talk-in-slack.png){: width="100%"}
질문에 대한 답변이 답긴 슬랙이기도 한데... 잡담도 섞여있어서 별도로 블러처리했습니다. 무관하게 블러 제거하고 넣을까요?

2021-08-17 06:54 UTC, socar-mignon commented
공개해도 괜찮은 내용이 담긴 슬랙을 찾아보겠습니다! (모든 대화내용에... 드립들이 조금씩 있어서...구별해봐야겠네요)

2021-08-18 02:49 UTC, arngard commented on _posts/2021-08-09-join-in-socar-android.md
> +위 사진은 입사 이후 제가 지금까지 작성한 Pull Request입니다. 네이밍부터 로직 상에 더 좋은 아이디어를 제안하는 것까지 다양한 코멘트를 작성 받아서 한 PR에 최대 84개의 코멘트를 받은 적도 있습니다. 쏘카 안드로이드팀이 코드리뷰 하는 방법이 더 궁금하다면 [해당 링크](https://speakerdeck.com/socar/kodeu-riby
네 문제없습니다.

2021-08-18 08:24 UTC, socar-kyle reviewed
date 관련 의견 하나 추가합니다!

2021-08-18 08:24 UTC, socar-kyle commented on _posts/2021-08-09-join-in-socar-android.md
> +category: android
```suggestion
category: dev
```

category는 본부 단위로 하고, tag를 팀별로 하려고 해요! 이 부분만 확인 부탁드려요!

2021-08-18 08:25 UTC, socar-kyle commented
https://socar-mignon.github.io/2021/08/09/join-in-socar-android.html

여전히 위에서 깨지는데, 이거 제가 체크아웃해서 확인해볼게요!!

2021-08-19 00:34 UTC, merged