AWS IoT 파이프라인 구축기 #1
socar-inc/socar-inc.github.io pull request #69
Opened 2021-11-23 05:56 UTC by socar-spock

2021-11-28 13:32 UTC, socar-hardy requested changes
글 잘 읽었습니다 스팍.

모비딕 팀의 차량 단말 상태 데이터 송수신 시스템의 변화에 대한 내용이군요. 어떤 내용을 전달하고자 하시는지 명확히 볼 수 있어서 좋았습니다.

몇 가지 아쉬움 + 추가되었으면 하는 점이 있는데요. 바로 다음입니다.

1. 기존 문제에 대안으로 MQTT을 선택하셨는데, 이게 왜 더 좋은지, 어떤 원리인지 설명해주시면 좋을거 같습니다.
2. 현재 글만 읽으면 "매니지드 서비스인 AWS IoT Core를 도입했고, 이로 기존 문제를 해결했다." 로 내용이 단순합니다. 이를 가져와 실제로 어떻게 구축하였으며, 내부 서비스와 컴포넌트, 아키텍처는 어떻게 되어있고, 이 과정 중에 어떤 것들이 힘들었는지 적어주시면 좋을거 같습니다.
3. 이렇게 바꾸며 아마 뿌듯하기도, 힘든점도, 후회되는 점도 있을텐데요. 이런 내용들도 적어주시면 좋을거 같습니다.

마지막에 다음 글에서 이런 과정을 따로 써주신다고 하셨는데, 위에서 제가 말씀드린 부분이 바로 이 과정들이 아닐까 싶네요.
스팍 의견 주시면 감사하겠습니다.

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +쏘카가 서비스를 제공하기 위해서는 차량의 상태에 대한 정보가 필수적입니다. 사용이 끝난 차량이 정상적으로 제위치에 안전한 상태로 돌아왔는지 알지 못하면 무인으로 서비스를 운영할 수 조차 없지요.
```suggestion
쏘카가 서비스를 무인으로 제공하기 위해서는 **차량의 상태 정보**가 필수적입니다. 예를 들어, 사용이 끝난 차량이 정상적으로 제위치에 안전한 상태로 돌아왔는지 언제든지 확인할 수 있어야 합니다.```

조금 더 부드럽게 어조를 바꾸어보았습니다.

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +따라서 차량의 정보를 수집하여 서버에 전달하며 고객의 요청에 따라 차량을 제어해주는 장치가 필수적으로 필요합니다.
```suggestion
따라서 차량의 상태 정보를 실시간으로 수집하여 서버에 전달하며, 고객의 요청에 따라 차량을 제어해주는 장치가 필요합니다.
```

실시간을 좀 더 강조해보았습니다. (실시간 맞겠죠?)

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +하지만 서비스를 시작하던 시점의 기술이 가진 한계성 때문에 단말은 잠재적인 문제를 갖고 있었습니다. 그 중 큰 몇가지를 꼽아보자면,
```suggestion
하지만 이 단말은 잠재적인 문제를 갖고 있었습니다. 그 중 몇 가지를 꼽아보자면 다음과 같습니다.
```

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +서비스 초기부터 쏘카는 차량 내에 서비스를 위한 단말을 장착하여 사용하고 있었습니다. 그리고 서비스가 급격하게 성장하던 시절에도 이 단말은 그럭저럭 제 역할을 해주었죠.
이 구형 단말에 대한 설명을 이 단락 아래에서 좀 더 다뤄주시면 좋을거 같습니다.
아래에서 갑자기 SMS, HTTP 등에 대해 나오는데, 구형 단말에 대한 설명이 없어 갑작스러운 느낌이 조금 있었습니다.
구형 단말의 기술적인 동작 과정을 살짝 설명해주시면 좋을거 같아요.

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +그래서, 서비스 초창기에 없던 많은 기술적 대안과 진보를 활용하기 위해 새로운 단말을 만들기로 결정하였습니다.
```suggestion
이러한 문제를 해결하기 위해 새로운 단말을 만들기로 결정하였습니다.
서비스 초창기에 없던 많은 기술적 대안과 진보가 등장했기 때문에 이를 활용해보면 좋을것 같았습니다.
```

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +- SMS를 통한 차량 제어를 더이상 하지 않는다.
음.. 제 생각에는 이 둘은, 목표라기 보다는, 하나의 원칙이나 방법론이라고 느껴집니다.
앞 내용에서 기존의 문제와 해결 방향을 정리해보면

1. 통신하는데 기존의 SMS는 너무 느리다 -> 지금보다 더 빠른 속도의 통신 프로토콜을 사용하자.
2. 별도의 웹서버가 필요하다 -> 웹서버 조차 필요없는 심플한 환경을 만들자.
3. 데이터 전달 요청이 급등할 때 지연이 발생한다 -> 트래픽에 유연한 구조를 설계하자.

정도가 되지 않을까 싶습니다. 스팍 생각은 어떠신지요?

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +새로운 단말을 만들때 기존 단말이 갖고 있던 한계점과 문제를 보완하기 위해 아래와 같은 기술 목표를 수립하였습니다.
```suggestion
새로운 단말을 만들때 기존 단말이 갖고 있던 한계점과 문제를 보완하기 위해 아래와 같이 요구사항을 정리했습니다.
```

아래 내용을 읽어보고 보니, 목표가 아니라 요구사항인거 같군요.

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +해서, 위와같은 요구사항에 맞춰 신규 단말은 [MQTT](https://ko.wikipedia.org/wiki/MQTT) 프로토콜 기반의 통신 방식을 채택하였습니다. MQTT 자체가 제한적인 IoT 기기에서 대용량의 데이터를 전송하기 위한 프로토콜이므로 기존 방식 대비 훨씬 적합한 프로토콜이라 하겠습니다.
```suggestion
위와 같은 요구사항에 맞춰 신규 단말은 [MQTT](https://ko.wikipedia.org/wiki/MQTT) 프로토콜 기반의 통신 방식을 채택하였습니다. MQTT 자체가 제한적인 IoT 기기에서 대용량의 데이터를 전송하기 위한 프로토콜이므로 기존 방식 대비 훨씬 적합한 프로토콜이라 하겠습니다.
```

HTTP가 아닌 MQTT는 뭔가 일반적인 사람들은 처음 들어볼거 같은데요. 이에 대해 좀 더 설명해주시면 좋을거 같습니다.

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +- 보안 설정이 차량 제어라는 특수성을 고려할때 부족한 부분이 있습니다.
```suggestion
- 메시지 브로커들을 직접 관리해야 하는 운영적인 부담이 있습니다.
- 대부분의 브로커들이 스스로에 대한 모니터링 방법은 제공하지만 어떤 단말이 연결중인지에 대한 정보까지는 제공해주지 않습니다.
- 서비스 안정성을 위해서 클러스터링 할 수 있어야 하지만 이것을 지원해주지 않는 브로커도 있습니다.
- 차량 제어라는 특수성을 고려할때 보안적으로 부족한 부분이 있습니다.
```

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +그리하여 이 고민을 해결하기 위해 관리되는 메시지 브로커 서비스를 사용하기로 결정하였고, [AWS IoT Core](https://aws.amazon.com/ko/iot-core/)를 사용하기로 결정하였습니다.
```suggestion
그리하여 저희 팀에서는 직접 브로커를 관리 및 운영하기 보다는, 클라우드 관리형 메시지 브로커 서비스인 [AWS IoT Core](https://aws.amazon.com/ko/iot-core/)를 사용하기로 결정하였습니다.
```

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +AWS IoT Core를 쓸때 서비스를 운영하는 입장에서 가장 주요한 부분은 "관리되는 서비스"라는 점입니다. 카셰어링 서비스의 특성상 시간이나 시즌마다 데이터량이 달라지는 이슈를 피할수 없습니다. 그리고 서비스에 부하가 걸리더라도 항상 단말은 명령 수신과 상태 보고에 있어 준비된 상태를 유지해야 합니다. 브로커의 상태가 불안정하면 단말 자체에 문제가 없
```suggestion
AWS IoT Core를 쓸때 서비스를 운영하는 입장에서 가장 주요한 부분은 "관리되는 서비스"라는 점입니다. 카셰어링 서비스의 특성상 시간이나 시즌마다 데이터량이 크게 달라지는 이슈를 가지고 있습니다. 그리고 서비스에 부하가 걸리더라도 항상 단말은 명령 수신과 상태 보고에 있어 준비된 상태를 유지해야 합니다. 단말 자체에 문제가 없어도 브로커의 상태가 불안정하면 서비스의 운영 안정성에 크게 영향을 미치므로, 관리되는 서비스가 주는 이점은 강력하다 하겠습니다.
```

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +AWS IoT Core를 쓸때 서비스를 운영하는 입장에서 가장 주요한 부분은 "관리되는 서비스"라는 점입니다. 카셰어링 서비스의 특성상 시간이나 시즌마다 데이터량이 달라지는 이슈를 피할수 없습니다. 그리고 서비스에 부하가 걸리더라도 항상 단말은 명령 수신과 상태 보고에 있어 준비된 상태를 유지해야 합니다. 브로커의 상태가 불안정하면 단말 자체에 문제가 없
표현을 좀 더 유하게 (부정 표현을 중의적 표현으로) 바꾸었습니다.

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +### AWS IoT Core 쓰면 끝?
요 위에 AWS IoT 코어를 어떻게 활용했는지에 대한 전체 아키텍처와 설계 내용이 들어가면 좋을 듯 합니다.
이에 대해서는 마무리 리뷰 코멘트에 좀 더 적어보겠습니다.

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +AWS IoT Core를 활용하여 데이터 수집을 하는것에서 더 나아가 각 부서(도메인)의 관점에 따른 유연한 데이터 활용이 가능해야 합니다. 과거에는 단말 데이터를 전부 DB에 저장하여 활용하는 방식을 사용했지만, 이 방식은 DB 부하를 불러온다는 단점을 가지고 있습니다.
```suggestion
AWS IoT Core를 활용하여 단순히 차량 상태 데이터를 수집을 하는것에만 머무르기엔 아쉽습니다. 여기서 더 나아가 각 부서(도메인)에서 수집된 데이터를 유연하게 활용하면 더 좋을 것입니다. 
```

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +모비딕 팀에서는 이 단점을 극복하기 위해 AWS IoT Core로부터 수집한 데이터를 [Amazon MSK](https://aws.amazon.com/ko/msk/)를 활용하여 흘려보내고 있습니다. 이러한 구조가 갖는 이점은 데이터활용을 위해 DB에 데이터를 굳이 저장할 필요가 없으며, MSK를 구독하는 컨슈머를 만들어 각 비즈니스 영역에 맞는 데이터 셋
```suggestion
기존에는 단말 데이터를 전부 DB에 저장하여 활용하는 방식을 사용했습니다. 그러나 이 방식은 DB 부하를 불러온다는 단점을 가지고 있습니다.  
저희 팀에서는 이 단점을 극복하기 위해 AWS IoT Core로부터 수집한 데이터를 [Amazon MSK](https://aws.amazon.com/ko/msk/)를 활용하여 흘려보내고 있습니다. 이러한 구조로 인해 굳이 DB에 데이터를 저장할 필요가 없으며, 데이터가 필요한 각 비즈니스 영역에서 MSK를 구독하는 컨슈머를 만들기만 하면 수집된 차량 상태 데이터를 활용할 수 있게 됩니다.
```

2021-11-28 13:32 UTC, socar-hardy commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +모비딕 팀에서는 이 단점을 극복하기 위해 AWS IoT Core로부터 수집한 데이터를 [Amazon MSK](https://aws.amazon.com/ko/msk/)를 활용하여 흘려보내고 있습니다. 이러한 구조가 갖는 이점은 데이터활용을 위해 DB에 데이터를 굳이 저장할 필요가 없으며, MSK를 구독하는 컨슈머를 만들어 각 비즈니스 영역에 맞는 데이터 셋
사내에 모비딕 팀 외에 이 MSK에 컨슈머 꽂은 서비스가 있을까요?

2021-11-29 02:03 UTC, socar-spock commented
"이런 과정"은 좀 다릅니다. 컨셉상의 이야기가 아닌 구현상의 이야기를 쓸 예정입니다.

2021-11-29 08:02 UTC, socar-spock commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +따라서 차량의 정보를 수집하여 서버에 전달하며 고객의 요청에 따라 차량을 제어해주는 장치가 필수적으로 필요합니다.
아주 실시간이라 할수는 없으니 `실시간` 이라는 말은 오해의 소지가 없도록 제하는게 좋겠습니다 :)

2021-11-29 08:18 UTC, socar-spock commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +모비딕 팀에서는 이 단점을 극복하기 위해 AWS IoT Core로부터 수집한 데이터를 [Amazon MSK](https://aws.amazon.com/ko/msk/)를 활용하여 흘려보내고 있습니다. 이러한 구조가 갖는 이점은 데이터활용을 위해 DB에 데이터를 굳이 저장할 필요가 없으며, MSK를 구독하는 컨슈머를 만들어 각 비즈니스 영역에 맞는 데이터 셋
없습니다.

2021-12-01 01:03 UTC, socar-hardy commented
resolve가 안된 커멘트들이 아직 남아있는데, 확인 부탁드립니다.

2021-12-01 03:16 UTC, socar-bada commented on _posts/2021-11-22-socar-iot-pipeline-1.md
> +안녕하세요. 모빌리티 시스템 그룹 - 모비딕 팀의 스팍입니다.
모빌리티플랫폼그룹입니다!

2021-12-06 05:35 UTC, socar-kyle commented
스팍 글 작성하시느라 고생하셨습니다!!

IoT 파이프라인 어떻게 구축했는지 궁금해지는 글이네요!! 다음 글이 빠르게 나오면 좋을 것 같단 생각이 들었어요!


맞춤법 교정을 한번 해주시면 좋을 것 같아요 :) 
http://speller.cs.pusan.ac.kr/

예)
- 제위치에 => 제 위치에 또는 제자리에, 확인할수 => 확인할 수, 구형단말 => 구형 단말
- 단말을 제어할때는 => 제어할 때는, 식별할수 => 식별할 수, 보낼때에는 => 보낼 때에는, 하다보니 => 하다 보니, 오래걸리는 => 오래 걸리는 등.. 띄어쓰기 고칠 부분이 꽤 많네요


- .gitignore, Gemfile 삭제해주셔요!
- assets의 iamge mkie-benna-X로 되어있는데 깔끔하게 수정하면 좋을 것 같네요
- img/iot-pipeline-1 에도 MQTT 1280px 파일 이름 수정해도 좋겠네요
- posts의 파일명 2021-11-22인데 업로드하기 전에 날짜 신경써주세요~(마크다운 파일 내의 요일과 posts 파일 모두 수정하긴 해야해요)

카테고리는 조직별로 운영하고 있어서 아래와 같이 고치면 어떨까 싶어요
- 카테고리 : mobility 
- 태그 : iot, dataengineering

2022-01-06 05:17 UTC, socar-hardy approved these changes

2022-01-06 06:51 UTC, socar-kyle approved these changes

2022-01-06 06:58 UTC, merged