카셰어링 서비스를 가능하게 하는 기술
socar-inc/socar-inc.github.io pull request #72
Opened 2021-12-03 09:12 UTC by socar-juno

쏘카의 관제장치 개발에 대해 다루었습니다.

2021-12-03 09:57 UTC, socar-pauljay commented on _posts/2021-12-03-socar-mobility-system.md
> +이번 글에서는, 1만 6천대 규모의 넘는 차량을 운영하는 쏘카의 차량에 장착된, 다양한 기기들 중 관제 장치에 관해 다루고자 합니다.
공유 가능한 수치(팩트 시트와) sync up 하시지요. 1만 7천대 입니다. https://docs.google.com/document/d/1wghXvppWQVwdvzaUITRUb2N0mttN3kEU9rboHlkKpGw/edit#

2021-12-03 09:59 UTC, socar-pauljay commented on _posts/2021-12-03-socar-mobility-system.md
> + 220V 콘센트가 아니라 차량의 배터리를 사용할 수 밖에 없는 차량 내 전자장치들은 전기를 공급 받는 것 조차도 엄청나게 힘든 일일 수 밖에 없습니다. 모든 전자장비는 회로에서 전자기 노이즈가 발생하며, 이 정도가 심한 경우 다른 전자기기가 영향을 받아 오작동을 하거나 고장날 수도 있습니다. 차량에 설치되는 장치들인 만큼, 장착된 장비들이 전자파 노이즈
전자기 노이즈 vs 전자파 노이즈 vs 혹은 다른 더 적절한 단어 없나요? 묘하게 외래어와 섞인 표현이라서요

2021-12-03 10:00 UTC, socar-pauljay commented on _posts/2021-12-03-socar-mobility-system.md
> +쏘카 차량 내부에는 쏘카에서 직접 제작한 관제단말기기 뿐만 아니라 고객이 보다 편하게 차량을 이용할 수 있도록, 그리고 보다 효율적으로 차량을 운영할 수 있도록 하기 위해 특별한 장치들이 장착되어 있습니다. 다음 글에서는, 운전 편의를 위한 장치에 대해서 소개드리겠습니다.
해당 글이 시리즈로 이어진다는 것을 독자로 하여금 직관적으로 이해시키고 싶다면, 제목이나 부제에서 연재임을 나타내주어야한다고 생각합니다. (1), (2) 등의 표기를 쓴다던지요.

2021-12-06 05:02 UTC, socar-hardy commented
웹 주소: https://socar-juno.github.io/mobility/2021/12/03/socar-mobility-system.html

2021-12-06 05:22 UTC, socar-juno commented on _posts/2021-12-03-socar-mobility-system.md
> +이번 글에서는, 1만 6천대 규모의 넘는 차량을 운영하는 쏘카의 차량에 장착된, 다양한 기기들 중 관제 장치에 관해 다루고자 합니다.
좋은 의견입니다!

2021-12-06 05:52 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +이번 글에서는, 1만 6천대 규모의 넘는 차량을 운영하는 쏘카의 차량에 장착된, 다양한 기기들 중 관제 장치에 관해 다루고자 합니다.
```suggestion
이번 글에서는 쏘카에서 운영하는 1만 7천대의 차량에 장착된 다양한 기기들 중 관제 장치에 관해 다루고자 합니다.
```

비문을 바꾸어보았습니다.

2021-12-06 05:52 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +세계 최고의 기술력이 집약된, 다양한 기술들이 쏘카 차량에 담겨있다는 사실 혹시 알고 계셨나요?
```suggestion
```

사실 전 정량적으로 드러낼 수치가 없다면 이런 표현은 차라리 빼는게 더 낫지 않을까 싶습니다.

2021-12-06 05:52 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +
여기 아래로 바로 관제 장치의 "역할" 을 나타내는 1, 2, 3, 4가 순서대로 나오는군요.
역할로 바로 들어가기 전에, "관제 장치의 개념"이 무엇인지 한번 가볍게 설명해주시면 좋을거같아요.
왜 관제 장치가 필요하고, 이 관제 장치는 어떤 목표를 가지고 어떤일을 어떻게 수행하는 지 등에 대해서요 ㅎㅎ

2021-12-06 05:52 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +비대면으로도 차량의 예약 / 운행 / 반납이 가능하도록 쏘카의 차량에는 일반 차량과 달리 다양한 IoT 장치들이 있습니다.
글을 끝까지 읽고 보니, 이 글은 다양한 IoT 장치에 대한 시리즈 글 중 첫번째군요.
다양한 IoT 들이 어떤 것이 있는지 한번 불릿으로 나열해주시고 (총론 시작의 느낌으로), 이 중에서 이 번글에서는 "관제 장치"에 다룬다고 작성해주시면 읽어나가는데 더 도움이 될거 같습니다.

2021-12-06 05:52 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +뿐만 아니라 차량의 데이터를 사용한, 다양한 연구들이 진행 중입니다. 그 중 하나의 예시로는 건전성예측 및 관리기술(PHM, Prognostics and Health Management) 연구가 있습니다. PHM이란, 운용 중인 시스템이나 장치에 대하여, 결함상태를 지속관찰하고, 이상 징후를 진단하여, 언제 치명적 수준에 도달할지 예지(prognosis)
차량의 데이터를 이용한 다양한 연구는 다른 단락으로 빼면 좋을거 같아요. 이 단락에서는 "차량의 데이터를 수집한다"에만 치중하면 될거 같습니다.

2021-12-06 05:52 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +뿐만 아니라 차량의 데이터를 사용한, 다양한 연구들이 진행 중입니다. 그 중 하나의 예시로는 건전성예측 및 관리기술(PHM, Prognostics and Health Management) 연구가 있습니다. PHM이란, 운용 중인 시스템이나 장치에 대하여, 결함상태를 지속관찰하고, 이상 징후를 진단하여, 언제 치명적 수준에 도달할지 예지(prognosis)
따로 빼게 되면 각 연구하고 계신 것, 했던 것들에 대해서 좀 더 상세하게 써주시면 좋을거 같아요.

2021-12-06 05:52 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +쏘카에는 40여 종에 달하는, 다양한 차종들이 있습니다. 차량의 위치는 어디에 있는지, 반납시 차량 시동은 잘 꺼져있는지, 주유량이나 전기차 충전량은 충분한지, 문은 제대로 잘 잠기고 열리는지, 원격에서 실시간으로 확인이 되어야 비대면 카셰어링 서비스가 가능합니다.
```suggestion
비대면으로 예약 / 반납이 가능할 수 있도록 차량의 데이터를 수집합니다. 수집하는 데이터는 예를 들면 다음과 같습니다.

- 차량의 위치는 어디에 있는지, 
- 반납시 차량 시동은 잘 꺼져있는지, 
- 주유량이나 전기차 충전량은 충분한지, 
- 문은 제대로 잘 잠기고 열리는지
```

2021-12-06 05:52 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +쏘카에는 40여 종에 달하는, 다양한 차종들이 있습니다. 차량의 위치는 어디에 있는지, 반납시 차량 시동은 잘 꺼져있는지, 주유량이나 전기차 충전량은 충분한지, 문은 제대로 잘 잠기고 열리는지, 원격에서 실시간으로 확인이 되어야 비대면 카셰어링 서비스가 가능합니다.
이 데이터들이 어떻게 수집되나요? 어떻게 보면 위 내용들은 너무나 잘 알려진 내용이라... 관제 장치의 How에 대해서 간단하게라도 설명해주시면 좋을거 같습니다.

2021-12-06 05:52 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +고객의 소중한 개인정보, 위치 정보 뿐만 아니라 차량의 데이터 또한 당연 보안의 대상입니다.정보보호 및 개인정보보호 관리체계인증 (ISMS-P)에 따라, 아무나 접근이 불가능 하도록, 보안을 철저히하여 숨겨져 있으며, 권한을 가진 일부 직원들만 해당 정보를 조회할 수 있습니다.
```suggestion
데이터를 수집할 때 있어 보안에도 신경을 써야하는데요. 특히 고객의 개인정보, 위치 정보 데이터가 대표적으로 그렇습니다. 이런 데이터는 정보보호 및 개인정보보호 관리체계인증(ISMS-P)에 따라 보안을 철저히하여 숨겨져 있으며, 권한을 가진 일부 직원들만 해당 정보를 조회할 수 있습니다.
```

2021-12-06 05:52 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +title: "카셰어링 서비스를 가능하게 하는 기술 "
```suggestion
title: "카셰어링 서비스를 가능하게 하는 IoT 기술 "
```

기술이라는 표현에서 좀 더 스코핑을 줄여보았습니다.

2021-12-06 05:56 UTC, socar-juno commented on _posts/2021-12-03-socar-mobility-system.md
> + 220V 콘센트가 아니라 차량의 배터리를 사용할 수 밖에 없는 차량 내 전자장치들은 전기를 공급 받는 것 조차도 엄청나게 힘든 일일 수 밖에 없습니다. 모든 전자장비는 회로에서 전자기 노이즈가 발생하며, 이 정도가 심한 경우 다른 전자기기가 영향을 받아 오작동을 하거나 고장날 수도 있습니다. 차량에 설치되는 장치들인 만큼, 장착된 장비들이 전자파 노이즈
1. 전자기 노이즈와 전자파 노이즈가 혼재되어 있어
전자기 노이즈로 통일하는게 좋을  것 같습니다.

2. (EMI/EMC)의 경우 전자기기간 간섭으로 설명하면 될 것 같습니다.
https://ko.dict.naver.com/#/entry/koko/c6e5364472674074b3c040155885d468

2021-12-06 06:02 UTC, socar-juno commented on _posts/2021-12-03-socar-mobility-system.md
> +세계 최고의 기술력이 집약된, 다양한 기술들이 쏘카 차량에 담겨있다는 사실 혹시 알고 계셨나요?
좋은 의견 감사들드립니다. 
비대면으로 카셰어링을 운영하기 위해, 다양한 기술들이 쏘카 차량에 담겨있다는 사실 혹시 알고 계셨나요?
정도로 수정해보면 어떨까요?

2021-12-06 06:06 UTC, socar-juno commented on _posts/2021-12-03-socar-mobility-system.md
> +쏘카에는 40여 종에 달하는, 다양한 차종들이 있습니다. 차량의 위치는 어디에 있는지, 반납시 차량 시동은 잘 꺼져있는지, 주유량이나 전기차 충전량은 충분한지, 문은 제대로 잘 잠기고 열리는지, 원격에서 실시간으로 확인이 되어야 비대면 카셰어링 서비스가 가능합니다.
우리는 잘 알고 있지만,  생각외로 이쪽 필드에 있지 않으신 분들은 잘 알지 못하는 내용이라 작성을 하였습니다.
글 전반에 걸쳐, How에 관해 적곻 싶었으나, 일부 보안에 해당하거나 다소 우려될 수도 있는 사항이 있어 아쉽게도 자세히 기술하지는 못하였습니다.

차량의 (유선 통신으로부터) 데이터를 습득한다! 정도의 내용만 노출해도 될지 문의드립니다.

2021-12-06 06:07 UTC, socar-juno commented on _posts/2021-12-03-socar-mobility-system.md
> +
좋은 의견 감사드립니다!!
도입부에서 간단히나마 알려주면 좋을 것 같습니다!

2021-12-06 06:08 UTC, socar-juno commented on _posts/2021-12-03-socar-mobility-system.md
> +비대면으로도 차량의 예약 / 운행 / 반납이 가능하도록 쏘카의 차량에는 일반 차량과 달리 다양한 IoT 장치들이 있습니다.
다른 기기들에 대해서도 나열 해볼게요!

2022-01-25 06:36 UTC, socar-hardy requested changes

2022-01-25 06:36 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +# 카셰어링 서비스를 가능하게 하는 기술 : 쏘카의 관제 기기
```suggestion
```

2022-01-25 06:36 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +## 1. 차량의 데이터를 수집합니다.
```suggestion
---

## 1. 차량의 데이터를 수집합니다.
```

2022-01-25 06:36 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +## 2. 차량의 문을 잠그고 열 수 있습니다.
```suggestion
---

## 2. 차량의 문을 잠그고 열 수 있습니다.
```

2022-01-25 06:36 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +![img](/img/socar-mobility-system-sts/sts-2-data.jpg){: width="90%" height="90%" style="display: block; margin: 0 auto"}
```suggestion
![img](/img/socar-mobility-system-sts/sts-2-data.jpg)
```

2022-01-25 06:36 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +![img](/img/socar-mobility-system-sts/sts-0-schematic.jpg){: width="90%" height="90%" style="display: block; margin: 0 auto"}
```suggestion
![img](/img/socar-mobility-system-sts/sts-0-schematic.jpg)
```

2022-01-25 06:36 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +![img](/img/socar-mobility-system-sts/sts-3-app.png){: width="90%" height="90%" style="display: block; margin: 0 auto"}
```suggestion
![img](/img/socar-mobility-system-sts/sts-3-app.png)
```

2022-01-25 06:36 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +## 3. 다양한 통신 방법으로 데이터를 교환합니다.
```suggestion
---

## 3. 다양한 통신 방법으로 데이터를 교환합니다.
```

2022-01-25 06:36 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +## 4. 외부에 노출된, 차량이라는 악조건을 견뎌야만 합니다.
```suggestion
---

## 4. 외부에 노출된, 차량이라는 악조건을 견뎌야만 합니다.
```

2022-01-25 06:36 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +![img](/img/socar-mobility-system-sts/sts-5-soldering.png){: width="90%" height="90%" style="display: block; margin: 0 auto"}
```suggestion
![img](/img/socar-mobility-system-sts/sts-4-env.png)

![img](/img/socar-mobility-system-sts/sts-5-soldering.png)
```

2022-01-25 06:36 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +## 맺으며
```suggestion
---

## 맺으며
```

2022-01-25 06:42 UTC, socar-juno commented on _posts/2021-12-03-socar-mobility-system.md
> +세계 최고의 기술력이 집약된, 다양한 기술들이 쏘카 차량에 담겨있다는 사실 혹시 알고 계셨나요?
해당 내용 본문에 반영되어 있습니다!

2022-01-25 06:43 UTC, socar-juno commented on _posts/2021-12-03-socar-mobility-system.md
> +비대면으로 카셰어링을 운영하기 위해, 다양한 기술들이 쏘카 차량에 담겨있다는 사실 혹시 알고 계셨나요?
해당 내용 본문에 반영을 해 두었습니다.

2022-01-25 06:53 UTC, socar-hardy approved these changes

2022-01-25 06:53 UTC, socar-hardy commented on _posts/2021-12-03-socar-mobility-system.md
> +
```suggestion
---

```

2022-02-14 09:22 UTC, socar-hardy commented
이 PR을 #127로 옮깁니다.

2022-02-14 09:22 UTC, closed without merging