feat(.github/workflows/korean_grammar.yaml): 액션을 추가한다
socar-inc/socar-inc.github.io pull request #99
Opened 2022-01-08 08:35 UTC by socar-hardy

2022-01-08 11:35 UTC, socar-kyle approved these changes

2022-01-08 11:35 UTC, socar-kyle commented on .github/workflows/korean_grammar.yaml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```suggestion
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

마지막줄 요렇게?

2022-01-09 02:41 UTC, socar-humphrey requested changes

2022-01-09 02:41 UTC, socar-humphrey commented on .github/workflows/korean_grammar.yaml
> +  build:
```suggestion
  grammar_check:
```
해당 라인이 github Action 로그 볼 때 display name입니다. 명시적으로 위와 같이 하면 좋을 듯여

2022-01-09 10:21 UTC, merged